newsboat/newsboat

README.md

Without asciidoc the man-pages are not created

added asciidoc to dependencies

---

test/configparser.cpp

While 'bc' is a very common piece of software a lot of distributions,
like Debian, do not include it by default. I don't see a reason to have
it as a test dependency when bash can serve the exact same purpose.

Drop test dependency on bc

---

Makefile

These sed commands fail on FreeBSD as they're interpreted as extended
regular expressions. At least, that's what the error message suggests to
me. As it turns out using the -e option was wrong in the first place as
I thought this switch enables extended regex, which it doesn't. Correct
is either -r (GNU sed) or -E (BSD sed). Both implementations support the
other's flag as well, so it shouldn't matter which we actually use.
* https://www.freebsd.org/cgi/man.cgi?query=sed&sektion=&n=1
* https://stackoverflow.com/a/3139925
Thanks to imm_ on IRC for reporting this and confirming the fix!

Fix building of docs on FreeBSD

---

rss/atom_parser.cpp

Fix compilation issue:
```cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10-74-g7901\" -I/usr/include/x86_64-linux-gnu -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -o src/download.o -c src/download.cpp
rss/atom_parser.cpp: In member function ‘rsspp::item rsspp::atom_parser::parse_entry(xmlNode*)’:
rss/atom_parser.cpp:106:9: error: ‘utils’ has not been declared
if (utils::is_valid_podcast_type(type)) {
^~~~~
```
introduced in ef929a9c3bda2f58ce300ac2e9d5e4a4159026c9

Add missing newsboat namespace

---

Makefile
doc/generate.cpp
doc/generate2.cpp
doc/keycmds.dsv
doc/newsboat.txt

If the DSV input files are broken regarding their number of columns in a
row (missing some or defining too many), this will now fail the build.
Reordering the dependencies for the 'doc' target will cause the
doc/generate{,2} binaries to be executed prior to creating the HTML
documentation. Previously the HTML build failed with a meaningless
xmllint error. In order to aid fixing the problem a bit faster, the DSV
error will now be presented instead. See also #30.

Fail if DSV files are malformed

---

Makefile

Using the conditional variable assignment for RANLIB and AR allows cross compilation to work by overriding these variables.

Use conditional assignment for RANLIB and AR

---

rss/parser.cpp

This is a bugfix for a bug reported by Håkan Jerning on IRC on 4th November 2017, who reported that the cookie-cache option did not work as expected. According to the reporter, the bug is fixed by this patch.
When resetting a curlhandle, this also discards the `CURLOPT_COOKIEJAR` option, which means that no cookies get persisted even though the "cookie-cache" config option is enabled.
In the url-parser, we reset the curl_handle after each request, which according to the libcurl documentation "[r]e-initializes all options previously set on a specified CURL handle to the default values" and seems like a good idea to not leak old settings into new connections.
Some handle-data, like cookies remain untouched by this operation, which is important, because we (optionally) use those cookies to …

Bugfix: Set CURLOPT_COOKIEJAR after reset of curlhandle

---

test/catch.hpp

After upgrading Catch to 2.0.1, then compiling and running tests, I get:
All tests passed (1517 assertions in 172 test cases)
which is the same as with the old version.

Update Catch version to v2.0.1

---

config.sh

Alpine Linux has a downstream patch for [newsbeuter](https://github.com/alpinelinux/aports/blob/master/main/newsbeuter/newsbeuter-2.9-ncurses6.patch) and hopefully soon for [newsboat](https://github.com/alpinelinux/aports/pull/2937/files#diff-66b0ab3ce7ee080e38cf45115524a1fc) to allow building with ncurses 6. I've tested that this approach works on Alpine Linux and would like to integrate it into newsboat so Alpine can remove their patch.

Allow ncurses6

---

src/utils.cpp

This is the last patch to upstream from Alpine Linux before they can build without any downstream patches. Once this is accepted I'll maintain the patches in the Alpine tree till the next version ships then remove them.
----
This fixes an Alpine Linux has building newsbeuter because the distro
uses MUSL instead of glibc. To quote the original patch author:
"If you try to compile newsbeuter without -fpermissive, as ppc64le, it
will not build due to a wrong argument type.
It is wrong because it sets the proper argument if you have Linux with
Glibc. Since we use MUSL, it use the wrong argument.
This patch assure that both musl and glibc uses the same argument type."

Use more portable __linux__ define

---

CHANGELOG.md
include/utils.h
src/textformatter.cpp
src/utils.cpp
test/textformatter.cpp
test/utils.cpp

This PR fixes #71 
CJK (Chinese, Japanese and Korean) don't use a space for
specifying word boundaries in a general. This commit
wraps such text at a screen border at a correct code-point boundary.
Note that this commit doesn't support grapheme clusters;
single grapheme cluster may be split into multiple code points
at a screen border.

Support line wrapping for CJK languages

---

Makefile

`doc/example-config` is procedurally generated so it should be removed in
the clean-doc target.
Debians build system complains about the build directory not being identical to the upstream tarball otherwise.

Remove example config on distclean

---

Makefile

This removes the executable bits from the man pages. The `644` permissions are properly being applied to other docs already, but it was missed for the two man pages.
----
You can see the openSUSE package details with this patch here:
https://build.opensuse.org/package/show/network:utilities/newsboat
https://build.opensuse.org/request/show/560213

Makefile: install docs as non-executable

---

src/configcontainer.cpp

The method is called `handle_action` instead of `handle*r*_action`. The debug log three lines below states the correct method name.

Fix method name typo in warning log

---

rss/parser.cpp

Hello!
On some distributions, libcurl is built without useful TLS certificate information.  This patch allows end users to override the libcurl builtin.

Add support for $CURL_CA_BUNDLE

---

include/formaction.h
include/list_formaction.h
src/feedlist_formaction.cpp
src/formaction.cpp
src/itemlist_formaction.cpp
src/list_formaction.cpp

Currently the best way to move in lists is to use the goto operation byopening the cmdline, typing the number then pressing enter.
In my opinion that's one key too many (especially with the default cmdline which requires to press shift). This commit implements movement in a similar way to mutt i.e. the cmdline is automatically opened when a number is pressed.

Implement mutt-like movement in the feedlist and itemlist

---

include/ttrss_api.h
include/utils.h
src/rss_parser.cpp
src/ttrss_api.cpp
src/utils.cpp

As all feed updates target the same host when an remote API is used, they can benefit from cURL-handle and therefore connection reuse. This is implemented by this commit.
At a cursory glance, it seems to pay off, even though the total payoff is not as siginificant as I've hoped (most of the time seems to be spend waiting for the network, even though the measurements were taken between servers with two symmetric gigabit links. So we save on CPU time, but without ostendable speedups in the actual operation):
```
Old:
for i in $(seq 0 7); do time ./newsboat -x reload; done
./newsboat -x reload  15.29s user 1.32s system 93% cpu 17.766 total
./newsboat -x reload  15.65s user 1.44s system 96% cpu 17.772 total
./newsboat -x reload  15.40s user 1.37s system 59% cpu 27.970 total
./newsboat -x …
```

Reuse handle when bulk-reloading

---

contrib/bookmark-evernote.sh

This adds a bookmark plugin for Evernote to contrib using the geeknote command line tool.
It could use some cleanup so that it doesn't end with an output as a save error in Newsboat even though the bookmark is successfully added to Evernote.

Add basic evernote bookmark plugin

---

src/ocnews_api.cpp

Just taking `enclosure_type` and `enclosure_url` from the API if they exist.

Add rss enclosure support to the ocnews api

---

config.sh

Hi,
This patch allows distribution packagers to override pkg-config in multi-arch scenarios, using the familiar PKG_CONFIG environment variable, if not set assumes "pkg-config".
Thanks,
alown

Enable overriding pkg-config command with arch specific

---

src/ttrss_api.cpp

Hi,
I ran into a slight behavioural difference between newsbeuter and newsboat with my custom (TT-RSS style) server, which hit these exceptions (due to my server sending session_ids as a JSON integer).
I added the below whilst debugging this, and thought it might be useful as a permanent addition (since it only affects logging).
Thanks,
alown

Log caught json exceptions during retrieve_sid

---

src/ttrss_api.cpp

In the ttrss api client was a typo for the attachments field name,
so the attachments wasn't gathered correctly.
Fixes #177

Fix typo in json field name attachements to attachments

---

src/keymap.cpp
test/keymap.cpp

While binding a key using bind-key we didn't verify the return value of
get_opcode to make sure we're binding to a valid operation.
This makes newsboat throw an error when trying to bind to an invalid op
similarly to what happens when trying to use an invalid operation in a
macro.
---
I spent *way* too long trying to find out why `open-all-unread-in-browser-and-mark-read` wasn't working -- turns out I just spelt the operation wrong.

Fix bind-key accepting invalid operations

---

src/oldreader_api.cpp
src/oldreader_urlreader.cpp

The online site theoldreader.com now supports https for all users. It was an paid extra in the past. Better to not send all your information in plain text, right? This simple change seems to work correctly.

Use https for theoldreader.com

---

3rd-party/alphanum.hpp
Makefile
include/utils.h
newsboat.cpp
src/feedcontainer.cpp
src/rss.cpp
src/utils.cpp
test/feedcontainer.cpp
test/rss.cpp
test/utils.cpp

Some feeds post multi-part articles and in that case I expect sorting by
article title to show them in order. But `strcasecmp()` does a simple
character by character comparison which sorts it like so: "1, 10, 11, 2,
3 ...".
Using `strverscmp()` changes it to the natural "1, 2, .., 10, 11"
---
There's another usage of `strcasecmp()` in `utils.cpp::convert_text`:
https://github.com/newsboat/newsboat/blob/b46c7a4bb1f282ec4471d4c1bde15f34dfe383f2/src/utils.cpp#L328
But I'm not sure what it's for so I opted to leave it alone (If it ain't broken...).
---
Note: `strverscmp` manpage says it needs `_GNU_SOURCE` defined but it appears to work without it anyway (is it defined somewhere else?).
I'm not sure if this has any implications with portability.

Use natural sort order

---

src/history.cpp

Just a tiny nitpick that bothered me. If history is disabled there is no need to keep stub files around.

Do not create empty files if history is disabled

---

po/de.po

This adds all missing and fixes the changed strings for the upcoming Newsboat release, so it can be shipped with a complete German translation.

Add missing German translations

---

doc/newsboat.txt
doc/podboat-cmds.dsv
include/pb_controller.h
include/pb_view.h
src/configcontainer.cpp
src/pb_controller.cpp
src/pb_view.cpp

The default format for the display of podcast feeds on podboat extends well off the screen to the where only most of the url is visible.
This branch allows users to choose the format of this display in much the same way as newsboat.
Please consider accepting my pull request.

Add format strings for podboat

---

test/rss.cpp
test/test-helpers.cpp
test/test-helpers.h
test/utils.cpp

It provides a RAII-style way to ensure that the environment variables of the whole tests suite aren't affected by a single test failing.
Tried ["auto to stick" style](https://www.fluentcpp.com/2018/09/28/auto-stick-changing-style/), too. It's interesting, but I haven't found a way declare an `unsigned int` that way. I ended up writing `unsigned{}`, but what if I want an `unsigned long` or `unsigned short`?
Requesting a review from anyone who's interested :)

Add EnvVar test helper

---

src/queueloader.cpp

Podboat does the initial parsing in queues via `tokenize_quoted()` which
returns an empty vector if it comes across a comment, which was never
actually checked in the code and resulted in a segfault.
Since podboat re-writes the file on exit we can not preserve the
comments without a lot of refactoring, so as a middle ground solution
issue an interactive warning to the user instead.

Fix podboat segfault when parsing comment in queue

---

include/itemrenderer.h
include/itemviewformaction.h
src/controller.cpp
src/itemrenderer.cpp
src/itemviewformaction.cpp
test/itemrenderer.cpp

This PR wraps the work started in #311, fixing a number of bugs in the process:
1. item headers were looking differently in internal and external pagers. Now they're the same;
2. `html-renderer` setting was ignored if external pager was in use. Now users can pair any renderer with any pager;
3. `ItemViewFormAction` wasn't displaying the last line of the text rendered by an external renderer.
This refactoring also enabled me to test some of the code, which is nice.
Sorry it's a lot of changes, but I didn't see a clear way to refactor any quicker. The commits are small, though, so should be manageable if reviewed commit-by-commit.
@der-lyse, this is the PR [you were looking forward to](https://github.com/newsboat/newsboat/pull/311#discussion_r224562615); here you go ;)

Re-use ItemRenderer in ItemViewFormAction

---

src/ocnewsapi.cpp

I had been getting a SEGFAULT with feeds such as `https://rss.art19.com/wolverine-the-long-night` which do not provide a `url` field, as they are purely podcasts (not saying I agree with the vendor here, but I'd rather not cause crashes).
The SEGFAULT only occurred when synced via nextcloud, not when using a `urls` file directly.
I did not try any of the other url sources, so this may need to be added there as well, I suppose.
I was able to narrow it down to the url field being `null`, and avoid the line of code which segfaults with an `if`
As a result, opening the item just opens the current working directory in the browser, rather than the feed, which is perhaps not desired behavior, but is consistent with behavior when the url is given directly in a `urls` file.

BUG: avoid null url in ocnews feed parser

---

README.md
doc/code-style.markdown

...as it is [disabled for now](https://github.com/newsboat/newsboat/issues/198#issuecomment-408687556) I think we should not mention it in the docs?

Do not mention pre-commit hook in the contrib docs

---

include/rs_utils.h
include/utils.h
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp

You'll have to let me know if this is done the way we want.
I checked the current codebase and even though consolidate_whitespace has 2 arguments, one has a default arg which is never used. Because of this I just removed it from my implementation.

Add rust implementation of consolidate_whitespace

---

include/strprintf.h

> > Would it help if I added a comment saying "sprintf returns the length of the formatted string. If it's longer than the buffer size, we have to enlarge the buffer in order to get the whole result"?
>
> that comment would really be helpful.
Done.
> > However, you mentioning compile-time checking of format strings made me realise that the code doesn't check if the format string contains more formats than arguments passed to fmt—it only checks that there are enough formats to use all the arguments. So I'll be adding that additional check as well.
Turns out I was confused; the code doesn't check the format string at compile time. All it does is "unroll" a variadic call into a series of ordinary call, each specialized to its own type. The format-string-splitting happen at runtime.
> > I …

Address @noctux' feedback on #343

---

include/rs_utils.h
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/utils.rs
src/utils.cpp

Rand crate requires rustc 1.22 or higher so that shouldn't be a problem.
I can see how the crate import might need to be moved.

Add Rust version of get_random_value function

---

include/rs_utils.h
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/lib.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp

Port `utils::is_valid_color` to rust

---

doc/newsboat.txt
include/download.h
src/download.cpp
src/pbview.cpp

I found that the `%F` specifier was still creating strings that were too long for my liking. 
This adds the `%b` specifier for basename of the path to the download.

Add a basename version of podboats filename display

---

include/itemrenderer.h
src/itemrenderer.cpp
src/itemviewformaction.cpp

In article view, numeric keys open a URL with a given number. I broke that behaviour in 485082f43f49f1c30974621107b1fa197618bf67 because I didn't fill articleview's `links` field, so the view thought that there are no links to open.
@j605, please confirm that this fixes the problem for you. Thanks for reporting it, too!

Fix 0..9 keys in article view

---

test/utils.cpp

Added some tests for utils functions. Should make things go quicker for #334 and increase our coverage a bit.
* `tokenize_nl()`
* `extract_filter()`
* `resolve_tilde()`
* `quote_for_stfl()`
* `get_auth_method()`
* `get_proxy_type()`
I can see an argument for removing `resolve_tilde()` since technically it has a side effect that influences other tests. I did my best to mitigate this effect.

Add tests for util functions.

---

include/rs_utils.h
include/utils.h
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp
test/utils.cpp

Did these together because they were related. Addresses 2/40ths of #334 
I found a crate `urlencoding` which does exactly what we need since the old implementation uses a curllib call which we no longer have access to in Rust.
I can see an argument against this inclusion being the leftpad incident. Since `urlencoding` is licenced under MIT, I could just borrow their code for our purposes.

Add Rust implementation of escape and unescape url

---

include/dialogsformaction.h
include/feedlistformaction.h
include/filebrowserformaction.h
include/formaction.h
include/helpformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
include/listformaction.h
include/selectformaction.h
include/urlviewformaction.h
src/dialogsformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/formaction.cpp
src/helpformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/listformaction.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp

Addresses #382 
I took a quick look through the rest of FormAction's children for redundant members. I did not see any.

Use protected FormAction ConfigPointer in FormAction's children

---

include/itemviewformaction.h
src/itemviewformaction.cpp
src/view.cpp

Since we were getting the RssItem to display and operate on by guid, the guid became a pointer with extra steps negating the advantages of std::shared_ptr
Keeps a copy of RssItem* so if the original goes out of scope ours doesn't get deleted.

Fix bug where feed items could be deleted during view

---

include/queuemanager.h

In file included from src/queuemanager.cpp:1:
include/queuemanager.h:22:9: error: unknown type name 'time_t'
const time_t pubDate,
^

Add missing header and fix build on FreeBSD

---

include/regexmanager.h
src/regexmanager.cpp
test/regexmanager.cpp

Marker extract function, renamed to better indicate new generalfunctionality, rescoped to allow testing.
Highlight now properly reopens tags, rather than always inserting tags at begining of line.

Fixes #401: Highlighting bug

---

Makefile

RUST_TARGET can be set to compile against a specific target.
Void Linux uses it to cross-compile from x86_64 to arm and aarch64.
Problem is that cargo puts the produced objects in
./target/$RUST_TARGET/release instead of ./target/release and linking
will fail because -L./target/$RUST_TARGET/release needs to be passed.
in the meantime also remove extra slash from -L./target/release.
NOTE: The debug version wasn't tested, only the release.

Makefile: add support for cross compiling via RUST_TARGET

---

doc/keycmds.dsv

In the documentation it said that the command is named `revsort`, but in the code it is `rev-sort`: https://github.com/newsboat/newsboat/blob/cfec81542fbeb5d0dc9af890fffef4931f82389c/src/keymap.cpp#L278-L280
This pull-request fixes the name in the documentation.
Alternatively you could also change the command to `revsort`, but this might break the config of multiple users.

Fix name of "rev-sort" command in documentation

---

doc/newsboat.txt
include/controller.h
include/queuemanager.h
src/controller.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/queuemanager.cpp

Introduces an '%N' formatting option to be used in the 'download-path'
and 'download-filename-format' format strings, which exposes the
items original feed-title, even if it is selected through a query-feed.
This allows users to group feeds under a query-feed in newsboat, while
maintaining seperate directories and naming-conventions in the filesystem.
If the item is not selected through a query feed, '%N' and '%n' behave
exactly the same.
Closes #428 
**Note to maintainers**:
This is my first feature to contribute. While the patch is functional, I expect
there to be some issues with regard to style and refactorings I made and
consider this to be WIP awaiting your feedback.

Add format option for feed titles in query-feeds

---

src/pbview.cpp

Fixes #434. The problem was two-fold:
1. a typo: the code was copy-pasted from FeedListFormaction, and
"feeds:w" wasn't changed to "dls:s". I checked, and there are no
other typos of this kind in this file;
2. the first time the loop is run, the widgets aren't painted yet, so
they don't know their size. This can be rectified by force-repainting
them, say, by downloading something. To fix the first run, I stuck
a force-recalculation there. Shouldn't be a performance bottleneck
since repaints don't happen often (every second during downloads, and
as fast as user types commands).

Fix spacer formatter in podlist-format

---

Makefile

This fixes a problem when cross compiling that generators and other
helper binaries should be compiled against the build machine (not the
host machine) since they are meant to be executed.

Makefile: cross compile generator with the build machine toolchain.

---

src/controller.cpp

Setup directories before importing, otherwise the import indicates success but does not succeed unless re-attempted.

Setup directories before attempting to import feeds

---

src/itemlistformaction.cpp
src/rss.cpp

This fixes #456, which turned out to be a two-fold problem:
1. deleting everything in a query feed didn't modify the database. Newsboat tried to delete all items with an "rssurl" of the current feed, but in query feeds, "rssurl" is a query; this didn't match any items, so none were deleted. Fixed by explicitly looping over all items and deleting them one by one.
2. when populating a query feed, Newsboat didn't check if the item is deleted. Fixed by adding such a check.
I also applied the boyscout rule and replaced a bit of home-grown benchmarking code with a `ScopeMeasure` from utils.
My excuse for not writing any tests is that we don't have tests for `FeedListFormAction` yet.
Reviews from anyone are welcome!

Fix purge in query feeds

---

rust/libnewsboat/src/utils.rs
src/remoteapi.cpp

`get_command_output()` used to be implemented in terms of `popen()`, which connects *either* command's stdin or stdout to Newsboat. Our new implementation connected both, and thus broke commands that tried to ask the user something. This commit inherits stdin, mimicking the behaviour of `popen(command, 'r')`.
Fixes #455.

Let user interact with get_command_output()

---

src/itemlistformaction.cpp

Resetting the itempos has the advantage of starting at the first post
when new articles arrive.

reset itempos when marking feed as read

---

src/itemlistformaction.cpp

Do not impact people using desc sorting in article-sort-order.
Previous behaviour might have been confusing if itempos jumped to the
top while new articles appear at the bottom.

reset itempos when marking feed as read only on asc sort order

---

doc/configcommands.dsv
src/configcontainer.cpp
src/formaction.cpp
stfl/dialogs.stfl
stfl/dllist.stfl
stfl/feedlist.stfl
stfl/filebrowser.stfl
stfl/help.stfl
stfl/itemlist.stfl
stfl/itemview.stfl
stfl/selecttag.stfl
stfl/urlview.stfl

Implementation of Issue #375 (Disabling/hiding title bar)
The config option is show-title-bar and it behaves as expected when swap-title-and-hints is also active

Added config option to hide the title bar

---

contrib/colorschemes/nord

A colour scheme for newsboat based on the Nord terminal palette.
Cool, blue, calm, and easy on the eyes.

Nord colour scheme for newsboat.

---

include/urlreader.h
src/fileurlreader.cpp
src/rss.cpp

Fixes #498.
I also made a few small refactors along the way. They don't look controversial to me, so I pushed them along with the fix.
@j605, can you please check if this fixes the bug for you? A review will be appreciated as well :)

Do not rename feeds to the name of their hidden tag

---

src/matcher.cpp

Here's how this bug came to be:
1. `FilterParser::parse_string` considers `title =~ "*A"` a valid filter expression, and returns `true` (success);
2. right after user entered their filter, `ItemListFormAction::prepare` is ran. It tries to compile the regex, fails, but never deallocates the `regex_t` instance;
3. subsequent calls to `prepare` use uninitialized `regex_t` instance, which leads to SIGSEGV.
Easily fixed by deallocating regex_t if regex failed to compile. I also audited the rest of `Matcher` for similar errors, but this was the only place that dynamically allocated resources.
Fixes #501 (@tsipinakis, can you double-check that?).

Deallocate regex_t if regex compilation failed

---

test/strprintf.cpp

This adds tests for all types supported by `strprintf::fmt`, testing minimum and maximum possible values for each (see #447).
The test coverage dind't change, which is very strange. I spent a good while trying to figure out why, but when I try the same thing in a separate minimal project, it works fine there. I couldn't find out what causes the wrong coverage report for Newsboat. I'm giving up on that—I know for a fact that I have those tests and that they're ran every time, and running them is the important part.

Improve test coverage for strprintf

---

Cargo.lock
Cargo.toml
rust/strprintf/Cargo.toml
rust/strprintf/src/lib.rs
rust/strprintf/src/specifiers_iterator.rs
rust/strprintf/src/traits.rs
test/strprintf.cpp

The title says most of it. Reviewers are advised to start by reading the large comment at the beginning of lib.rs, and looking through the docs in the other two modules. That'll give you the overview of goals and the design. I rewrote the history to make it appear like I came up with all the ideas first, and then just implemented them methodically.
Closes #447.

Implement strprintf::fmt as a Rust macro

---

src/utils.cpp
test/test-helpers.h
test/utils.cpp

To test migrations in `ConfigPaths`, I needed a temporary directory that will remove itself at the end of the test. And I also stumbled upon a bug with `utils::make_parents` when the path ends with a slash.  Those changes formed a nice bundle, so I decided to submit them as a separate PR.
`TempDir` contains a questionable choice: I just `rm -rf` the temporary directory using `system()`, instead of writing my own recursive descent with `stat`. I admit this is laziness, but I don't think it matters much: the only way to inject something malicious into that `system()` call is to change the `TEMPDIR` environment variable. Surely the person running the tests won't try to pwn themselves?
Reviews from anyone are welcome!

Test and simplify utils::make_parents

---

contrib/colorschemes/kinda-maia

I created a color scheme based on my current computer's theme
(almost stock Manjaro), and wanted to share it.
it is mostly green with small touches of light blue.
comments and improvements would be much appreciated :)

add color scheme based on Adapta-Maia GTK theme

---

rss/rss09xparser.cpp
test/data/rss_091_with_empty_author.xml
test/data/rss_092_with_empty_author.xml
test/data/rss_094_with_empty_author.xml
test/rsspp_parser.cpp

Fix out-of-bounds access on empty author tag in RSS 0.9x

---

.travis.yml

Fedora and Ubuntu use these options to turn some bugs into compilation
failures and runtime crashes:
- https://fedoraproject.org/wiki/Changes/HardeningFlags28
- https://fedoraproject.org/wiki/Changes/HardenedCompiler
- https://wiki.ubuntu.com/ToolChain/CompilerFlags
I might add "-Wformat -Wformat-security" to the Makefile, because
they're only affecting the compilation. The rest are runtime checks, and
I'm on the fence about enabling them for all downstream users. Let's
keep deferring the decision to distributions for now.
This commit is inspired by #542.

Travis: harden compilation the way Fedora and Ubuntu do

---

include/filebrowserformaction.h
include/scopemeasure.h
rss/item.h
rss/rssparser.cpp
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs

```
In file included from src/scopemeasure.cpp:1:
include/scopemeasure.h:18:17: error: field has incomplete type 'struct timeval'
struct timeval tv1, tv2;
^
include/scopemeasure.h:18:9: note: forward declaration of 'newsboat::timeval'
struct timeval tv1, tv2;
^
include/scopemeasure.h:18:22: error: field has incomplete type 'struct timeval'
struct timeval tv1, tv2;
^
include/scopemeasure.h:18:9: note: forward declaration of 'newsboat::timeval'
struct timeval tv1, tv2;
^
2 errors generated.
[...]
In file included from src/filebrowserformaction.cpp:1:
include/filebrowserformaction.h:43:20: error: unknown type name 'mode_t'; did you mean '__mode_t'?
char get_filetype(mode_t mode);
^~~~~~
__mode_t
/usr/include/sys/_types.h:51:20: note: '__mode_t' declared here
typedef __uint16_t      __mode_t; …
```

Fix build on FreeBSD

---

.cirrus.yml
Makefile
README.md
rust/libnewsboat/build.rs
src/itemrenderer.cpp
test/configpaths.cpp
test/itemrenderer.cpp
test/rsspp_parser.cpp
test/test-helpers.cpp
test/textformatter.cpp
test/utils.cpp

CI builds Newsboat, and runs Rust tests. Some C++ tests for `ConfigPaths` fail, and since we're rewriting this component at the moment, I'm not fixing them. This will be done later, when `ConfigPaths` is moved to Rust completely (see #413, #561).

Build Newsboat on FreeBSD 11.2 and 12.0 with Cirrus CI

---

rust/libnewsboat/build.rs
rust/libnewsboat/src/utils.rs

`if let Some(_) = Command::new().output()` only checks if the command *started*. We also need to check if it *finished*, otherwise we can't trust the output.
Fixes #579.

Do not use GIT_HASH if git-describe failed

---

include/utils.h
src/configparser.cpp
src/utils.cpp
test/utils.cpp

Since the backticks should be evaluated before tokenizing (see https://github.com/newsboat/newsboat/pull/493 for discussion), the comments need to be stripped even before that, so that backticks can be safely used for quoting.
Not doing so can cause various unexpected issues (such as having `` `yes` `` in commented line causing newsboat to crash with out-of-memory errors, as the `/usr/bin/yes` command produces infinite output).
The `/usr/bin/yes` issue was encountered when running newsboat on the example configuration file, which contains several instances of commented `` `yes` `` strings. See https://bugzilla.redhat.com/show_bug.cgi?id=1731224 for the original bug report.
---
As this is my first (code) contribution to newsboat, please have patience if I have put code/tests in wrong place …

Strip comments before the backticks are evaluated

---

include/rssitem.h
src/cache.cpp
src/rssfeed.cpp
src/rssitem.cpp

These changes decrease startup time by about 6%. I wanted to get more precise measurements, but found that e.g. stddev increases after each optimization, and I'm not sure what value I should be comparing—the median, the average, some percentile, or maybe something else entirely. So I just ran old and new version on a 1.4 Gb cache.db stored on tmpfs, and the difference is about half a second, which is 6%.

Speed up Cache::internalize_rssfeed

---

doc/internal/docker.md

Docker containers are ephemeral and don't retain `.cargo` between runs. This means that every `docker run` updates Cargo index and re-downloads all the crates we require—even if none of our code changed and nothing needs to be re-built. Sharing your local ~/.cargo with the container is harmless because that directory only contains the index and a cache of downloaded crates; no build artifacts, no project-specific configs, nothing like that.
@der-lyse, if you have a spare minute, please take a look at the wording. Reviews from everyone else are welcome as well.

Suggest sharing ~/.cargo with the container

---

src/itemlistformaction.cpp

Caused by heap-use-after-free in ItemListFormAction::prepare().
The complete invalidation mode repopulates the listfmt vector, thus it's
not enough to clear the invalidated_itempos only in case of partial
invalidation mode. The fix is to clear the invalidated_itempos vector
also in case of complete invalidation mode.

Crash when opening a url (#189)

---

src/itemlistformaction.cpp

To reproduce the crash:
* Enter a feed with no unread items
* Press `l` to hide all items
* Press N
Edit: I did a quick pass on other operations in the litemlist and feedlist and didn't find any similar bugs - but I didn't take a very close look.

Fix crash on unread toggle in empty feed

---

rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat-ffi/src/fmtstrformatter.rs
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat-ffi/src/logger.rs
rust/libnewsboat-ffi/src/utils.rs

Reviewers in #413 uncovered a number of problems that I kept copy-pasting from module to module:
1. most FFI functions can cause undefined behaviour even if called from a safe code—it's sufficient to pass some rubbish in place of a pointer to cause a SIGSEGV, for example. The functions are now marked `unsafe`, which doesn't affect the code in any way, but reminds us that we should be careful;
2. when deallocating an object allocated by Rust, the code created `Box<c_void>` instead of `Box<TheTypeWeWant>`. We're lucky our Rust structs don't hold resources other than memory, and don't cause many problems if deallocated incorrectly;
3. all modules create a wrapper function that turns `*mut c_void` into a `Box<T>`, and pass a `&mut Box<T>` into a function that does the actual work of …

Clean up other FFI modules

---

include/rs_utils.h
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/configpaths.rs
rust/libnewsboat/src/utils.rs
src/pbcontroller.cpp
src/utils.cpp

See #334. I'm casting mode_t to a signed int before sending it over. Not sure if there was a more appropriate way of going about it.

port `utils::mkdir_parents` to rust

---

rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat/src/cliargsparser.rs
rust/libnewsboat/src/configpaths.rs

As mentioned in #613, we should be using PathBuf instead of Strings for our path fields.

migrate CliArgsParser String paths to PathBuf

---

include/regexmanager.h
src/regexmanager.cpp
test/matcher.cpp
test/regexmanager.cpp

Regular expressions compiled with `regcomp` weren't freed with `regfree` before their memory was `delete`d, leaking a tiny bit of memory (hundreds of bytes at a time). The impact is pretty much nil; most of these regular expressions are part of `highlight` rules, and live for the entire run-time of the program anyway.
Coveralls says that `RegexManager` is fully covered by tests now, but it's actually not, since there are no tests for `get_attrs` and `get_regexes`. I want to concentrate on other memleak issues for now, so I filed #638.
Will merge in three days unless someone stops me for a review.

Fix memory leaks in RegexManager

---

docker/alpine-3.10.2-clang-8.0.0-r0.dockerfile

Created a small alpine docker image for clang-format. Fixed the alpine and clang versions. Image size comes to about 194mb. 
`docker run -v $(pwd):/workspace alpineclang -verbose --style=file -i *.cpp doc/*.cpp include/*.h rss/*.h rss/*.cpp src/*.cpp test/*.h test/*.cpp`
We could also take inspiration from  https://hub.docker.com/r/unibeautify/clang-format/dockerfile. Builds clang and only keeps statically linked clang-format in the final image. Image size comes to 34mb but build time is much longer. 
Last but not least, we could simply pull the built image from `unibeautify/clang-format`. Only issue is that they don't tag the image so we might not stay fixed to clang `8.0.0`.

add clang-format executable in alpine docker image

---

doc/configcommands.dsv
doc/newsboat.txt
rust/libnewsboat/src/fmtstrformatter/mod.rs

f-a on IRC pointed out that we don't say what the format of `cookie-cache` file is; I added a note.
I also updated the instructions for NewsBlur, which requires `cookie-cache` to be set.
@der-lyse, if you have a moment, can you please take a look at this? Is the wording clear? Reviews from anyone else are welcome, of course.
Will merge in three days per my usual routine.

Improve docs regarding cookies

---

doc/chapter-firststeps.txt
include/rs_utils.h
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp
test/configparser.cpp
test/utils.cpp

When reviewing #584, I didn't consider that a pound character can appear inside titles or regexes, not just in front of a comment. This introduced a regression, which was reported in #652 when 2.17 was released.
This PR makes `utils::strip_comments` aware of double quotes and backticks, so it now ignores pound signs inside.
I'd be really happy if someone reviewed this within 20 hours, so I can make a release on Sunday. Otherwise I'll wait my ordinary three days, and release this on Thursday.

Ignore # characters inside double quotes and backticks

---

include/rs_utils.h
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp

This commit ports utils::quote_to_stfl to rust, as outlined in #334. The original tests pass.
As this is my first attemt at production rust, any comments and criticism is welcome :)

Port utils::quote_for_stfl to Rust

---

include/rs_utils.h
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp
test/utils.cpp

This commit ports utils::gentabs to rust, as outlined in #334. The original tests pass.
As this is my first attemt at production rust, any comments and criticism is welcome :)
I'm not really convinced about all that casting in the rust implementation, even though it should not really be any practical problem (both `isize` and `usize` should be able to store all effective tab-values that should occur. Even theory-wisse as stringwidth is bounded by the addressable memory, this implementation should work, but it still seems strange to have all that casting going on).

Port utils::gentabs to Rust

---

include/keymap.h
src/keymap.cpp
test/keymap.cpp

This should fix #454. I don't really have a better idea how to do it, if someone has, please share. Also, it's kind of surprising that `OP_INT_END_CMDLINE` doesn't actually handle this.

Do not unbind command line keybindings for "all" context

---

README.md
doc/newsboat.txt

This fixes #651. An alternative way to fix it would be to keep one list, and turn another into a link. But I think that would have hurt the readability: a person reading README on GitHub or in the tarball might not appreciate being redirected elsewhere for such a basic info, and a person reading /usr/share/doc/newsboat/newsboat.html might not even have our README.md (or it might be in /usr/share/doc/newsboat/README.md, meaning the distribution has to patch newsboat.html).
Those lists aren't changed all that often, and I added comments to further lower the chance of them getting out of sync again. Hope that will be sufficient.

Update dependencies list in HTML docs

---

.travis.yml

As mentioned in #495, Travis CI made Ubuntu Xenial a default some time ago. While updating our config, it occurred to me that we can upgrade straight to the most recent LTS release, Ubuntu Bionic, so I did that. The only job that's left on Xenial is GCC 4.9 builds, because Bionic doesn't ship this version of GCC.
I also added Clang 9. Figured I'd make it part of this PR, because it's not too big of a change.
This fixes #495 and #648. Will merge in three days unless someone—anyone—will stop me for a review.

Move (most of) Travis to Ubuntu Bionic, and add Clang 9

---

rust/libnewsboat/src/utils.rs
test/utils.cpp

This fixes a warning in Rust and (hopefully) makes one of the tests stop sporadically failing on CI.

Miscellaneous edits

---

docker/alpine-3.10-clang-8.0.0-r0-rust-1.38.0.dockerfile

See https://github.com/newsboat/newsboat/issues/654
The rust alpine image on its own is ~ 745MB. That's crazy! 
Running `clang-format` now requires including the executable (since I removed the entrypoint)
```shell
docker run -it --user $(id -u):$(id -g) -v $(pwd):/workspace some_image_tag clang-format -verbose --style=file -i test/*
```
and running `rustfmt`:
```shell
docker run -it --user $(id -u):$(id -g) -v $(pwd):/workspace alpoineclangrust cargo fmt
```
Let me know what you think

combine clang and rust 1.38.0 into single dockerfile

---

Cargo.lock
rust/libnewsboat/Cargo.toml

The issue was found by `cargo audit` tool (see #675 for more details on this).
Will merge in three days unless someone—anyone—stops me for a review (even though I don't think there's much to review here).

Bump smallvec to 0.6.10 to get security fixes

---

test/keymap.cpp

It's undefined behaviour to cast an integer into an enum that doesn't have a corresponding constant. Constants in `Operation` end at 3010, so 30000 cannot be casted.
Issue spotted by Clang's UndefinedBehaviourSanitizer. (There are 88 more issues, all in `filter/`, and all about misaligned accesses. I'd rather work on #631 rather than editing that auto-generated code.)

Do not cast arbitrary integer into enum class

---

docker/ubuntu_18.04-i686.dockerfile

We don't need docs on CI, so let's not install them. The `--profile` option is [a recent addition](https://blog.rust-lang.org/2019/10/15/Rustup-1.20.0.html).

Do not install rust-doc on CI

---

README.md
snap/snapcraft.yaml

I'm certifying Newsboat with BadgeApp (a topic for a future PR), and imm_ on IRC commented that our webpage should focus more on Newsboat itself. I think that's fair; after two years of work, and with recent move to Rust, Newsboat isn't simply "an actively maintained fork" anymore.
I already applied these changes to our website and on Snap store. Doing a pull request here to leave a trace of that change, with an explanation.
Will merge in three days unless someone—anyone—stops me for a discussion.

De-emphasize that Newsboat is a fork of Newsbeuter

---

include/listformaction.h
include/view.h
src/itemlistformaction.cpp
src/listformaction.cpp
src/view.cpp
test/itemlistformaction.cpp

closes #570
One question: is it alright to break early in this switch, specifically before a `invalidate(itempos)`? Not exactly sure what this is doing..

Don't mark as read when browser fails

---

Cargo.lock

libc-0.2.48 is has no support for FreeBSD on archs like powerpc64,
arm64, etc.
openssl-sys-0.9.46 is too old to support LibreSSL 3.x.

Bump libc and openssl-sys crates

---

.travis.yml
include/download.h
include/strprintf.h
src/view.cpp

I was reading [a blog post about interesting compiler flags](https://kristerw.blogspot.com/2017/09/useful-gcc-warning-options-not-enabled.html) and tried them on Newsboat. A few stuck, so I'm adding them ~to Makefile~ to "release build" job on Travis (because optimization makes warnings more precise).
`-Wshadow`, `-Wuseless-cast`, and `-Wold-style-cast` trigger a lot of warnings in filter parser. I'll try them again once #631 is fixed.
The rest didn't produce any warnings, so I decided not to enable them at all.
Will merge in three days unless someone stops me for a review.

Add a few new warning flags and fix resulting warnings

---

src/queueloader.cpp

Podboat: Save and restore "finished" state in queue file

---

rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/cliargsparser.rs
rust/libnewsboat/src/utils.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_cache_file.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_config_file.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_exportfile.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_importfile.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_logfile.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_opmlfile.rs
rust/libnewsboat/tests/cliargsparser_resolves_tilde_to_homedir_in_urlfile.rs
rust/libnewsboat/tests/resolve_tilde.rs
test/cliargsparser.cpp
test/utils.cpp

Resolve tilde in command-line options that take paths

---

.travis.yml
submit-to-coveralls.sh

This replaces cpp-coveralls tool (using gcov under the hood) with grcov and curl. There are both up- and down-sides with this.
Upsides
=======
- grcov creates a single report for C++ and Rust.
Downsides
=========
- grcov only supports LLVM's coverage data -- GCC builds no longer participate in coverage reports.
- rustc support for coverage is not yet stable -- only Nightly Rust generates coverage.
Also, Nightly Rust is a less stable of the branches, so we might have occasional problems with coverage. Eventually I'll look into pinning the Nightly version to avoid this, but I'm exhausted with this particular problem for now.
- Coveralls reports don't have consecutive numbers anymore -- we now use Travis build IDs, which are long integers.
- Coveralls reports no longer contain commit's …

Include Rust in test coverage report

---

include/download.h
include/pbcontroller.h
include/queueloader.h
src/download.cpp
src/pbcontroller.cpp
src/queueloader.cpp

This will simplify writing tests for QueueLoader because it:
- allows testing with different queue file location;
- removes the need for setting up PbController with serveral environment variables.

PB Queueloader: Remove PbController dependency

---

contrib/urls-maintenance.sh

this bash script operates various maintenance tasks on files urls and cache.db for newsboat:
- convert http to https in urls file when https feed is available
- convert feeds urls to their forwarded urls for 3xx http codes
- feeds urls not returning a valid http code 200 are tagged "_dead"
cache.db is also updated to refer to the new url feeds so all read/unread articles and flags are preserved

Convert http to https and update 301 forwarded urls

---

.cirrus.yml
rss/rssparser.cpp
rss/rssparser.h
src/rssparser.cpp
test/rsspp_rssparser.cpp

A few days ago, Cirrus CI started auto-upgrading VMs to latest macOS release, 10.15 Catalina. This led to [one of the tests failing](https://cirrus-ci.com/task/5236688679075840):
```
-------------------------------------------------------------------------------
W3CDTF parser returns empty string on invalid input
-------------------------------------------------------------------------------
test/rsspp_rssparser.cpp:38
...............................................................................
test/rsspp_rssparser.cpp:41: FAILED:
REQUIRE( rsspp::RssParser::__w3cdtf_to_rfc822("-3") == "" )
with expansion:
"Wed, 31 Dec 1969 15:59:59 +0000" == ""
```
With Catalina, `strptime` started accepting negative numbers for `%Y` ("year") format, producing an invalid `struct tm`. This was then fed …

Fix test failure on macOS Catalina

---

include/htmlrenderer.h
src/htmlrenderer.cpp
test/htmlrenderer.cpp

This patch adds basic support for the <audio> and <video> tags emiting a new link for each available <source> (the MediaElement src is included in the available sources).
A feed that can be used to test parts of this patch is the [Factorio Blog](https://www.factorio.com/blog/rss).

Add basic <audio>, <video> and <source> support for HtmlRenderer

---

rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/cliargsparser.rs
rust/libnewsboat/src/configpaths.rs
rust/libnewsboat/src/fmtstrformatter/mod.rs
rust/libnewsboat/src/fmtstrformatter/parser.rs
rust/libnewsboat/src/history.rs
rust/libnewsboat/src/human_panic.rs
rust/libnewsboat/src/logger.rs
rust/libnewsboat/src/utils.rs
rust/strprintf/src/format_specifiers_32bit.rs
rust/strprintf/src/format_specifiers_64bit.rs
rust/strprintf/src/specifiers_iterator.rs

I deliberately didn't add Rust's linter, Clippy, to our CI pipeline, because I don't want to enforce idiomatic Rust yet. For now, I'm happy with whatever we get by simply rewriting C++ to Rust.
However, this doesn't mean I'm not interested in idiomatic Rust. So yesterday I looked through Clippy warnings, and fixed most of them. The remaining ones are either questionable (e,g. rewriting `if` ladders with a more idiomatic but harder-to-understand `match`), or inapplicable (Clippy wants us to document all `unsafe` functions, but we don't expose that interface to anyone, so I don't see a reason to waste time documenting them).
I'll merge these changes in three days unless someone—anyone—stops me for a code review.

Fix some Clippy warnings

---

doc/newsboat.txt

Relevant source locations:
- Positive values result in padding on the left: [fmtstrformatter/parser.rs](https://github.com/newsboat/newsboat/blob/master/rust/libnewsboat/src/fmtstrformatter/parser.rs#L67-L71)
- Padding being applied: [fmtstrformatter/mod.rs](https://github.com/newsboat/newsboat/blob/master/rust/libnewsboat/src/fmtstrformatter/mod.rs#L107-L121)
Related to https://github.com/newsboat/newsboat/pull/744#discussion_r376712119

Fix left/right padding documentation for format specifiers

---

src/controller.cpp
src/reloader.cpp

Fixes #732.
The issue was caused by not updating (replacing) the feed if the number of articles was 0.
Query feeds are explicitly not updated because that would result in unread/total counts to reset to 0 in the feed overview (on `OP_RELOAD`->`Reloader::reload()`).
A different solution to that might be to make the reload function call `View::prepare_query_feed()` [1] for single feeds (make it similar to `Reloader::reload_all` [2]).
[1] https://github.com/newsboat/newsboat/blob/1574cf6c2f615339c4be3030b81a99173daa3e7e/src/view.cpp#L999-L1012
[2] https://github.com/newsboat/newsboat/blob/1574cf6c2f615339c4be3030b81a99173daa3e7e/src/reloader.cpp#L176-L181

Fix "no title on empty feed" issue

---

.travis.yml

This fixes build failures uncovered by a recent PR: https://travis-ci.org/newsboat/newsboat/builds/649481789

Resolve conflict between Python 2 and 3 on macOS Travis CI

---

include/rssparser.h
src/reloader.cpp
src/rssparser.cpp

Fixes #748.
The fix relies on the fact that `rsspp::Feed` stays default-initialized unless something is fetched. Remote APIs (TT-RSS, NewsBlur etc.) store feed titles as part of subscription list, so they always update `rsspp::Feed`, even if the feed doesn't have any items.
If you were affected by #748 and lost some titles, you can forcibly re-fetch them:
1. in the command line, run `sqlite3 ~/.newsboat/cache.db 'UPDATE rss_feed SET lastmodified = 0, etag = ""'` (cache.db might be in ~/.local/share/newsboat/cache.db, or somewhere else if you overrode the location). All your existing items will be kept; this command only makes Newsboat *pretend* like it never fetched feeds, so HTTP servers send the whole feeds again—complete with the titles;
2. start Newsboat and reload all your feeds with …

Do not remove feed titles if update brought no new items

---

README.md

Submitting builds there was always troublesome, so I never did it
regularly. The analyzer is falling behind the times, and now requires
booting Linux with a special parameter.
It did found a number of bugs in our code, but the pain of maintaining
it is not worth it for me.

Remove Coverity badge from the README

---

src/reloader.cpp

Fixes small regression introduced by commit [1] which caused
`oldfeed->set_status(DlStatus::SUCCESS);` to no longer get called.
This results in a `_` being shown for query feeds (`DlStatus::TO_BE_DOWNLOADED`), even after relaoding finished.
Effect can be seen by adding the following line (with `%S` [2]) to the config file:
`feedlist-format "%S %4i %n %11u %t"`
and a queryfeed to the urls file, e.g.:
`"query:Unread Articles:unread = \"yes\""`
[1] https://github.com/newsboat/newsboat/pull/746/commits/46547a749b1a05bfcc1a5e1d93bc93c01e7319d3
[2] https://newsboat.org/releases/2.18/docs/newsboat.html#feedlist-format-S

Update download status for query feed

---

CHANGELOG.md
doc/newsboat.txt
src/colormanager.cpp
src/itemviewformaction.cpp
src/view.cpp
stfl/help.stfl
stfl/itemview.stfl

Fixes #507. 
Let me know if you think of a better name to replace `styleend` (taken from stfl files: [item](https://github.com/newsboat/newsboat/blob/f0a4b9dbe0b0b0a58086938d6cb7469c9e6e703e/stfl/itemview.stfl#L16) and [help](https://github.com/newsboat/newsboat/blob/f0a4b9dbe0b0b0a58086938d6cb7469c9e6e703e/stfl/help.stfl#L18)).
I will see if I can think of a better name after sleeping.

Allow configuring color/attributes for EOT tildes

---

.cirrus.yml

This change has two goals in mind:
1. it puts an upper limit on how much memory our build process takes, so
we can be sure that Newsboat is buildable within those constraints;
2. documentation says that the lower the requirements, the less time it
takes to provision a VM or container.
Code formatting is also limited to one CPU core, since we don't need
more than that. I'd try to lower the memory even further, but at 128MB,
`git clone` fails with OOM.
Will merge in 24 hours.

Cirrus CI: use less memory for jobs

---

.cirrus.yml

What I added in #760 doesn't actually work: no cache is being checked, and it's never uploaded. This PR fixes that by:
- moving the `cargo_cache` section into each task. Cache is not enabled without this
- replacing $CARGO_HOME with $HOME/.cargo, because the former is apparently not defined in Docker containers, and points to /usr/local on FreeBSD
I'll merge this immediately. Submitting this PR just to leave a trace of these changes.

Cirrus CI: actually Cache cargo stuff

---

include/rs_utils.h
include/utils.h
rust/libnewsboat-ffi/src/utils.rs
src/formaction.cpp
src/itemrenderer.cpp
src/rssparser.cpp
src/utils.cpp
test/utils.cpp

The previous implementation used execvp(3), which requires `char* const
argv[]` (constant pointer to modifiable strings). The new implementation
uses std::process::Command, and requires `&[&str]` (constant slice of of
constant strings). Since I'm so bent on const correctness, I decided to
update the signature in C++.
I'll merge this in three days unless someone stops me for a review.

Const-qualify argv in utils::run_program

---

include/rs_utils.h
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/utils.cpp

See #334.
This is the most straightforward translation from the C++ code.
Eventually we could implement a zero copy interface by just returning a
slice from the original string. But I'd leave it as is as long as we need to
provide C wrappers.

Oxidize substr_with_width

---

Makefile

All the credit goes to Anatoly Sablin (@ma1uta): he's the one who told me about Make jobserver and its support in Cargo. I'm merely applying that knowledge to my particular problem.
Fixes #768.
I'll merge this in 24 hours unless someone stops me for a review.

Make Cargo aware of how many jobs Make can run

---

.travis.yml

The rationale is the same as with the similar change to Cirrus CI (cf. 48ecfb911019e37dca0d1da0c7e9a8e993a7681c): slightly faster builds and additional resilience to outages.
Will merge in about 24 hours, unless someone stops me for a review.

Travis CI: cache Cargo's registry

---

.cirrus.yml

FreeBSD VMs on Cirrus CI occasionally stop, saying they've been "signaled to exit":
- https://cirrus-ci.com/task/4911591850246144
- https://cirrus-ci.com/task/5253449772171264
- https://cirrus-ci.com/task/6008502887907328
Someone else had this problem, and it turned out to be an OOM killer: https://github.com/dart-lang/sdk/commit/fcf88fe6faa0b7a63a690a716f914b5400657c2a
Given our Docker containers need 3GB of RAM, perhaps the same applies to FreeBSD; so this commit increases the RAM size in hopes of fixing the intermittern VM crashes.
I'm going to merge this right away, to start testing as quickly as possible. If you have any feedback, please comment here even after the PR was merged.

Cirrus CI: request 3GB of memory for FreeBSD

---

.cirrus.yml

[Turns out](https://github.com/cirruslabs/cirrus-ci-docs/issues/463#issuecomment-589306089) we need that for the cache to work.
I don't expect any controversy on this, and I already saw it working, so I'm going to merge this right away.

FreeBSD on Cirrus CI: set HOME envvar

---

.cirrus.yml

This is something I meant to do ever since filing #540, #620, #621, #622, #623, and #624. 
[AddressSanitizer is a static analysis tool](https://releases.llvm.org/9.0.0/tools/clang/docs/AddressSanitizer.html) built right into the compiler. It adds checks for different memory-related errors: use-after-free, double-free, etc. Tests are a perfect place to apply these checks, since tests are reproducible by design, so any problems spotted by the sanitizer will be easier to fix. On Linux, AddressSanitizer automatically includes [LeakSanitizer](https://releases.llvm.org/9.0.0/tools/clang/docs/LeakSanitizer.html) as well.
Clang and GCC include the same sanitizers, but my understanding is that their upstream is with Clang, so that's what I use to run the checks.
AddressSanitizer [is not expected …

Run tests with {Address,Leak}Sanitizer on Cirrus CI

---

include/rssfeed.h
include/rssitem.h
include/utils.h
src/cache.cpp
src/feedlistformaction.cpp
src/formaction.cpp
src/itemlistformaction.cpp
src/itemrenderer.cpp
src/itemviewformaction.cpp
src/queuemanager.cpp
src/rssfeed.cpp
src/rssitem.cpp
src/rssparser.cpp
src/utils.cpp
test/cache.cpp
test/rssfeed.cpp

In Newsboat, all strings are in UTF-8, but user might've set a different charset for their locale, so we have to convert. Somehow this job was pushed into getters in `RssItem` and `RssFeed`. It doesn't belong there. This PR simplifies interfaces of these classes by removing those methods, and moving the conversions closer to the edge.
Most of the time, I simply replaced calls of `X()` with `utils::utf8_to_locale(X_raw())`, because I assume existing code works correctly. Some places, though, it was obvious that the code wanted the UTF-8 version; there, I simply called `X_raw()`.
The final commit drops the `_raw` suffix, removing confusion and simplifying the names.
I'll merge this in three days unless someone stops me for a review.

Convert UTF-8 to locale's charset at the boundary

---

.cirrus.yml
docker/ubuntu_18.04-build-tools.dockerfile

#786 introduced a check on Cirrus CI that runs `make depslist` and checks that no changes were introduced; if they were, it means the depslist is not up to date. Unfortunately, that check never actually worked. @rnestler [spotted that](https://github.com/newsboat/newsboat/pull/786#discussion_r383173465), and this PR fixes it. Yes, I did verify that it fails as it should: https://cirrus-ci.com/task/4775935220121600?command=main#L161 :)
I'll merge in 24 hours if no-one stops me for a review.

Unbork depslist check on Cirrus CI

---

doc/newsboat.asciidoc
include/regexmanager.h
src/regexmanager.cpp
test/regexmanager.cpp

This fixes several issues related to highlighting:
- Fixes #37 
- Fixes #242 
- Fixes #331 
- Fixes #488 
- Fixes #535 
The main idea in `quote_and_highlight()` now is:
1. Remove all tags (`<…>`) from the to-be-highlighted line (save tag text/position in a separate mapping)
2. Repeatedly:
- Execute regex on the stripped line to find ranges to be highlighted
- Add tags for those ranges in the text/position mapping (no changes to the line itself)
3.  Insert all tags from the mapping into the to-be-highlighted line
Operations on the tag text/position mapping is extracted into separate functions.
Let me know if anything is unclear or needs some descriptive comments.

Fix several highlighting issues

---

src/regexmanager.cpp
test/regexmanager.cpp

Fixes #795 
@Minoru: Thanks for the helpful suggestion (`REG_NOTBOL`)

RegexManager: Stop `^.` from matching after a previous regex match

---

docker/ubuntu_18.04-i686.dockerfile

Fixes #594. See https://github.com/newsboat/newsboat/issues/594#issuecomment-595948701 for explanation.
Will merge in three days unless someone stops me for a review. (I'm AFK for the weekend, so I won't address your comments before Monday.)

Docker i686: use Rust 1.41.1

---

test/htmlrenderer.cpp

@Minoru: I saw you closed #237.
If you are still interested, this PR shows some use of DYNAMIC_SECTION.
There are a few more places where a SECTION is placed in a loop but those don't need formatting to generate a locally unique section name, e.g.:
https://github.com/newsboat/newsboat/blob/4b850932d242cb7c0126ae679ac858f7fdd88d9c/test/htmlrenderer.cpp#L109-L119

Test: Use DYNAMIC_SECTION instead of manually formatting name

---

include/htmlrenderer.h
mk/mk.deps
src/feedlistformaction.cpp
src/itemrenderer.cpp
test/itemrenderer.cpp

Fixes #796 
Also fixes old Newsbeuter issues:
- Fixes https://github.com/akrennmair/newsbeuter/issues/554
- Fixes https://github.com/akrennmair/newsbeuter/issues/589
@Minoru: I haven't forgotten about [your suggestion to introduce a type called StflString](https://github.com/newsboat/newsboat/pull/797#discussion_r388350769).
I'm not yet sure how that will work out so I will postpone it for now.

Escape "<" (into "<>" for stfl) feed/article title and author

---

include/rs_utils.h
include/utils.h
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/htmlrenderer.cpp
src/itemrenderer.cpp
src/textformatter.cpp
src/utils.cpp
test/itemrenderer.cpp
test/utils.cpp

Follow-up to https://github.com/newsboat/newsboat/pull/804#issuecomment-598702621
> The rest of the commits can become a new PR.
I've slightly changed the approach.
Instead of quoting for stfl and then undoing that, now the stfl quoting is not applied at all for plaintext output.

Don't quote for stfl in plaintext output

---

src/htmlrenderer.cpp

Fixes #659 
More info at https://github.com/newsboat/newsboat/issues/659#issuecomment-601465547

HtmlRenderer (<OL>): Guard against pop_back() if vector is empty

---

3rd-party/catch.hpp
test/cliargsparser.cpp
test/itemlistformaction.cpp

That release doesn't suppress warnings inside assertions, so I had to
fix a few of our tests where `int` was compared to `unsigned int`.
Normally I'd commit this directly to master branch, but since I touched tests, I'm submitting a PR. Will merge tomorrow before making 2.19 release. Reviews from everyone are welcome as always!

Update Catch2 to 2.11.3

---

doc/faq.asciidoc

This was adapted from https://github.com/newsboat/newsboat/issues/800#issuecomment-600869425. As a consequence, I also updated our advice about spawning GUI browsers.
Will merge tomorrow before releasing 2.19. Reviews from everyone are welcome!

Add FAQ item on "Browser returned error code …"

---

src/dialogsformaction.cpp
src/helpformaction.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp

Fixes usage of `%>[char]` for format strings in:
- Dialogs form
- Help form
- Select-tag form
- Select-filter form
- URLs form
Related to #88 and PR #815 
There is still a small issue with `selecttag-format` for which `%>[char]` does not yet work.
I expect to fix that together with the resizing issue (#390).
At that time I also expect to move the multiple `f->run(-3);` calls into one generic place (in `FormAction` base class).

Let STFL compute widget dimensions before retrieving those dimensions

---

.cirrus.yml
.travis.yml
README.md
doc/newsboat.asciidoc
rust/libnewsboat/src/utils.rs

relates to https://github.com/Homebrew/homebrew-core/pull/52037
```
--> rust/libnewsboat/src/utils.rs:232:12
|
232 |     rs_str.trim_right_matches(x).to_string()
|            ^^^^^^^^^^^^^^^^^^ help: replace the use of the deprecated item: `trim_end_matches`
|
= note: `#[warn(deprecated)]` on by default
```

trim_right_matches -> trim_end_matches

---

Makefile
README.md
doc/newsboat.asciidoc

This lets users install binaries without installing the docs, which will help e.g. users who don't have a new enough Asciidoc: https://github.com/newsboat/newsboat/issues/829
Reviews welcome! Will merge in three days.

Makefile: install manpages via install-docs target

---

rust/libnewsboat/src/fmtstrformatter/parser.rs

This adds a couple more tests. Since there is no FFI bindings to fmtstrformatter, I didn't add the corresponding C++ tests.
Reviews welcome. Will merge in three days.

fmtstrformatter: Add tests for empty then-else branches

---

rss/atomparser.cpp
test/data/atom10_1.xml
test/rsspp_parser.cpp

From [documentation of `<author>`](http://www.atomenabled.org/developers/syndication/#recommendedEntryElements) element:
> Names one author of the entry. An entry may have multiple authors. An entry must contain at least one author element unless there is an author element in the enclosing feed, or there is an author element in the enclosed source element.

Display all authors for an atom entry

---

.cirrus.yml

FreeBSD 11.2 and 12.0 are unsupported now. 
You will run into trouble sooner or later by continuing to install from the package repository otherwise since packages are only built for supported releases.
AFAICT there are no working freebsd-11-3 images, so use one of the 11.3-STABLE snapshots instead.

cirrus: Use newer FreeBSD versions

---

CHANGELOG.md
src/rssignores.cpp
test/rssignores.cpp

There's really no point in having these without arguments.
Prompted by @dennisschagt during the review in #850: https://github.com/newsboat/newsboat/pull/850#discussion_r401673813
Reviews from everyone welcome. Will merge in three days.

Error on zero params to `always-download` or `reset-unread-on-update`

---

README.md

I recognize the merit of CII Best Practices list, and I think Newsboat should achieve the passing level. [We already have the basics covered](https://bestpractices.coreinfrastructure.org/en/projects/3328), but there's still some work to be done, especially in areas security and analysis. Let's show off our in-progress badge, so people know that we share those values and want to get better at living by them.
There really isn't anything to review here, but if you have some thoughts on the matter, please comment. I'll merge this in three days (perhaps someone only looks at the PR list once in a while, let's give them a chance to notice this).

README: add CII Best Practices badge

---

.cirrus.yml
.travis.yml

This is a workaround for #866.

Let macOS fail on Cirrus, and add it back to Travis

---

CHANGELOG.md
doc/newsboat.asciidoc
rust/libnewsboat/src/fmtstrformatter/mod.rs
src/itemlistformaction.cpp
test/fmtstrformatter.cpp

[Idea](https://github.com/newsboat/newsboat/pull/868#issuecomment-610831063) by @tsipinakis:
> How about ignoring whitespace in conditionals instead, it's technically 'empty'? IMO I'd expect an all whitespace string to be considered empty.
Replaces PR #868.
Also adding format specifiers for unread/deleted/flags to have more control over formatting (`%f` combined some flags [using gen_flags](https://github.com/newsboat/newsboat/blob/09ec32244dca3f5699cb736636c8b5a2105d31ef/src/itemlistformaction.cpp#L1374-L1390).

Ignore whitespace when rendering conditional sequence

---

CHANGELOG.md
include/dialogsformaction.h
include/dirbrowserformaction.h
include/feedlistformaction.h
include/filebrowserformaction.h
include/formaction.h
include/helpformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
include/listformaction.h
include/selectformaction.h
include/urlviewformaction.h
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/formaction.cpp
src/helpformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/listformaction.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
src/view.cpp

I noticed today that macro execution continues when an operation fails. I think it's a no-brainer that I would want to know of an operation failing and act accordingly rather than blindly continuing execution.
Unfortunately somewhere in the pipeline the error bar is cleared (couldn't find the exact place), so currently the error is simply 'Macro execution failed'.

Abort macro execution if open_in_browser fails

---

doc/newsboat.asciidoc

Fixes #876.
Found the operations missing from documentation by looking through [src/keymap.cpp](https://github.com/newsboat/newsboat/blob/7112a9436b292d264649a43af7a5bd66d6cdaa5d/src/keymap.cpp) (searched for `KM_PODBOAT` and `KM_BOTH`).

Podboat: Document operations which were missing

---

include/reloader.h
src/reloader.cpp
src/scopemeasure.cpp

I noticed that the `Reloader` class was still using manual calculations with `time()` instead of `ScopeMeasure`.
While fixing that, I noticed some related code which could use some improvement.

Reloader: Use ScopeMeasure and apply some small refactoring/cleanup

---

src/newsblurapi.cpp

TRUE/FALSE are not defined anymore.  1 and 0 are used instead.

Add support for upcoming json-c 0.14.0.

---

include/controller.h
include/feedhqurlreader.h
include/fileurlreader.h
include/inoreaderurlreader.h
include/newsblururlreader.h
include/ocnewsurlreader.h
include/oldreaderurlreader.h
include/opml.h
include/opmlurlreader.h
include/ttrssurlreader.h
include/urlreader.h
mk/mk.deps
po/newsboat.pot
src/controller.cpp
src/feedhqurlreader.cpp
src/fileurlreader.cpp
src/inoreaderurlreader.cpp
src/newsblururlreader.cpp
src/ocnewsurlreader.cpp
src/oldreaderurlreader.cpp
src/opml.cpp
src/opmlurlreader.cpp
src/ttrssurlreader.cpp
test/fileurlreader.cpp
test/opml.cpp
test/opmlurlreader.cpp

While looking into error handling for `FileUrlReader` I found some unused and/or empty methods.
Created a separate PR for this so it is easier to review (and cherry-pick if any changes are unwanted).

Cleanup UrlReader related classes

---

Cargo.lock
Cargo.toml
Makefile
po/newsboat.pot
rust/regex-rs/Cargo.toml
rust/regex-rs/src/lib.rs

I'm bending my own rules here, adding code that is not used by anything but its own test suite. Motivation for this is the same as with #857: this PR is a stepping stone to new filter parser and matcher implementations, which I split into multiple PRs to make it more reviewable.
This PR adds two creates, regex-sys and regex-rs. The first one is a set of unsafe FFI bindings, the second one is a safe wrapper. I expect that libc create will eventually add their own bindings for POSIX regex, and we will drop regex-sys. For now, it's faster for us to roll our own.
Reviews are welcome as always. Will merge in three days.

Add Rust bindings for regex.h

---

src/formaction.cpp

These operations were ignored when encountered in macros.
For regular keypresses, the actions were already handled by STFL
(configured using STFL variables like `bind_page_up`).
We call `get_form()->run(0)` to let STFL directly process the input.
This is needed to ensure that the commands of a macro are executed in
the correct order.
Fixes #890

Pass up,down,pageup,pagedown,home,end to STFL

---

include/keymap.h
src/helpformaction.cpp
src/keymap.cpp
src/pbview.cpp
test/keymap.cpp

Fixes #843 
I squashed several refactoring commits into one.
If you are interested, the separate small commits can still be found on a temporary branch: https://github.com/newsboat/newsboat/compare/master...dennisschagt:bugfix/issue-843-before-rebase

Fix and improve `KeyMap::get_keymap_descriptions()`

---

newsboat.cpp

In #874 the translator was confused by these descriptions, because they look the same as the file names. This commit changes the wording somewhat to amend this. "Cache" is still a "cache", though; no idea how to improve that one.
Blocked on #873 and #874. Those two PRs change the template and/or translations, I don't want to conflict with them. Generally I'd say that whoever got their PR into a mergeable shape wins, but my changes here are too small to warrant this, so I'll just wait :)
Reviews welcome!

Use wordier file descriptions in --help

---

po/ca.po
po/ja.po
po/sk.po
po/zh.po
po/zh_TW.po

> I: po/ja.po: language-team-equal-to-last-translator 'Japanese <GradyMartin@gmail.com>' 'Grady Martin <GradyMartin@gmail.com>'
> I: po/ca.po: language-team-equal-to-last-translator 'Alejandro Gallo <aamsgallo@gmail.com>' 'Alejandro Gallo <aamsgallo@gmail.com>'
> I: po/zh.po: language-team-equal-to-last-translator 'Chinese <joshyupeng@gmail.com>' 'josh yu <joshyupeng@gmail.com>'
> I: po/sk.po: language-team-equal-to-last-translator 'František Hájik <ferko.hajik@gmail.com>' 'František Hájik <ferko.hajik@gmail.com>'
> I: po/zh_TW.po: language-team-equal-to-last-translator 'Traditional Chinese <aeglos.lin@gmail.com>' 'Aeglos <aeglos.lin@gmail.com>'
These make it harder to notice warnings and errors, so let's fix them by
making the translation team empty if there is only one translator.
I …

Fix all i18nspector info messages

---

doc/faq.asciidoc

Half of these cases could probably be detected automatically, and immediately explained with error messages. That haven't happened yet, though, so let's at least document them.
Sources:
- external API not enabled: https://github.com/akrennmair/newsbeuter/issues/480#issuecomment-275241457
- self-signed certificate: https://github.com/akrennmair/newsbeuter/issues/141#issuecomment-180285191 and https://github.com/newsboat/newsboat/issues/41#issuecomment-340290751
- wrong TT-RSS URL: https://github.com/akrennmair/newsbeuter/issues/141#issuecomment-282405728
- quotes in password not escaped: https://github.com/akrennmair/newsbeuter/issues/172#issuecomment-195735608
Fixes #44.
Reviews from everyone are welcome. Will merge in three days.

FAQ: explain reasons for TT-RSS auth failures

---

Cargo.lock
doc/newsboat.asciidoc
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/filterparser.rs
rust/libnewsboat/src/lib.rs
rust/libnewsboat/src/matchable.rs
rust/libnewsboat/src/matcher.rs
rust/libnewsboat/src/matchererror.rs

These don't replace the C++ implementations because we still have to compare them ­— unit tests alone aren't enough.
Most of this code is by @tsipinakis; he submitted it in #701. I made a lot of small edits on top, and history became an absolutely incomprehensible mess, so I created a new one instead. I still managed to split it in somewhat logically-isolated portions, so it's entirely possible to review commit-by-commit.
See #631.

Add Rust implementations of FilterParser and Matcher

---

src/view.cpp

Fixes #917.
This fixes a regression caused by PR #814.
I guess this is another issue which would have been obvious if https://github.com/newsboat/newsboat/issues/806 was implemented (I might look into implementing that in the near future).

Stop applying STFL encoding to `browser` variable

---

doc/newsboat.asciidoc
src/formaction.cpp

My personal use case is I want to do `:exec open-all-unread-in-browser-and-mark-read`, I don't use this command enough to bind but still need to use it once in a while
See: #892

Add exec command for executing binded commands

---

.cirrus.yml
.travis.yml
docker/ubuntu_16.04-build-tools.dockerfile
docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile

This PR mixes a number of small changes, so I think it's fine to bundle them like this.
First: back when we were only using Travis, we ran all our jobs on the same Ubuntu version. Official repos didn't contain all the C++ compilers we need, so we also added r/test PPA and apt.llvm.org. This made the .travis.yml slightly less complicated than it would've been otherwise.
Now that we're using Cirrus CI and Docker, it's far simpler to run a couple different Ubuntu versions such that they cover the whole range of compilers we support. That's what I did here: Ubuntu 18.04 keeps shouldering most of the load, while 16.04 is used for GCC 4.9, and 20.04 is used for GCC 9, GCC 10, and Clang 10.
Second: .travis.yml had some leftovers from my failed attempt to run builds with more warnings enabled, …

A bit of CI upkeep

---

Makefile

This means that once `make all` finished, a call to `make install-examples` won't try to build anything.
Issue spotted by macports maintainers:
https://github.com/macports/macports-ports/pull/7053#discussion_r422622159
Reviews welcome. Will merge in 24 hours.

Make: `doc` generates example config

---

.travis.yml

`-Zno-landing-pads` got deprecated. This commit replaces it with options suggested by the grcov project: https://github.com/mozilla/grcov/pull/428
Fixes #916.
Reviews are welcome! Will merge in 24 hours.

Fix test coverage job on Travis

---

.cirrus.yml

We've got a couple CI jobs that run additional checks: AddressSanitizer
and extra compilation flags. Newer compilers might bring improvements to
these checks, so let's run them with the latest compilers.
Reviews welcome. This is an uncontroversial, boring change, though, so I'll merge it in 24 hours.

CI: use newest compilers for checks

---

CHANGELOG.md
doc/chapter-snownews.asciidoc
doc/newsboat.asciidoc
src/utils.cpp
test/data/926-urls
test/fileurlreader.cpp
test/utils.cpp

This fixes the issue where every other time, backslash had to be escaped three times instead of one, i.e. to get `\ \ \ \` (four backslashes separated by spaces) one had to write `\\ \\\\ \\ \\\\`. For a detailed explanation of the problem and the solution, see [the commit message here](https://github.com/newsboat/newsboat/commit/8f6b73a33036bb05084c36a9f445c00ed32c672a).
This PR also:
- documents double quotes and how escapes in them work (it doesn't mention `\n`, `\t`, `\v`, and `\r` because #928) (@der-lyse, that's the part I'd like you to take a look at);
- performs a little refactoring of the offending function;
- of course, adds tests for all the issue that this fixes.
Fixes #536
Fixes #642 
Fixes #926
Reviews from everyone are welcome. I'll merge this in three days.

Fix backslash escaping inside double quotes

---

doc/configcommands.dsv
include/listwidget.h
include/pbview.h
src/configcontainer.cpp
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/itemlistformaction.cpp
src/listwidget.cpp
src/pbcontroller.cpp
src/pbview.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp

This will add an optional wrap scroll feature. When enabled, moving down while on the last item in a list will wrap around to the top and vice versa.
There are equivalent features in ranger, lf, etc. https://ranger.github.io/ranger.1.html#wrap_scroll-bool
Note: I'm not sure if you want the Newsboat config added to Podboat as it's currently missing. So I just set the wrap scroll value to `false` for it in `pbview.cpp`.

Add wrap scroll feature

---

doc/docker.md
docker/ubuntu_16.04-build-tools.dockerfile
docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile

During an IRC discussion the other day I realized that our docs for Docker don't mention an important thing: binaries build in- and outside a container might be incompatible. This can lead to linking errors, doc/generate failing to run, or maybe even something weirder.
This PR adds the necessary documentation.
Reviews from everyone are welcome, though I requested one from @der-lyse specifically since I always run my doc edits by him :) Will merge in three days.

Docker: suggest running `make distclean`

---

rust/libnewsboat/src/fmtstrformatter/limited_string.rs
rust/libnewsboat/src/fmtstrformatter/mod.rs
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/itemlistformaction.cpp
src/pbview.cpp
src/queuemanager.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
stfl/dialogs.stfl
stfl/dllist.stfl
stfl/filebrowser.stfl
stfl/selecttag.stfl
stfl/urlview.stfl
test/fmtstrformatter.cpp

Changes:
- Stop FmtStrFormatter from quoting for stfl and don't quote arguments passed to it
- Instead, quote the output of do_format() for stfl wherever necessary
This moves the quoting for stfl closer to the places where we actually interact with stfl.
It also makes it possible (or at least easier) to implement https://github.com/newsboat/newsboat/issues/806.
---
There were 3 different cases of FmtStrFormatter usage:
- lines in listviews (those are the only lines which need quoting for stfl):
- [src/feedlistformactioncpp:1071](https://github.com/newsboat/newsboat/blob/2d4246d4d92e8c432b6aef40c8db27cc31c3c520/src/feedlistformaction.cpp#L1071-L1077)
- [src/itemlistformaction.cpp:1065](https://github.com/newsboat/newsboat/blob/2d4246d4d92e8c432b6aef40c8db27cc31c3c520/src/itemlistformaction. …

Only encode for stfl ('<' -> '<>') after running FmtStrFormatter

---

doc/keycmds.dsv
src/itemviewformaction.cpp
src/keymap.cpp
src/urlviewformaction.cpp

This makes user-defined macros with `open-in-browser-and-mark-read` behave the same way as `open-in-browser` for the URL and item/article views instead of being ignored.
I have a macro like `macro r set browser "rtv"; open-in-browser-and-mark-read ; set browser qutebrowser` and before this fix, it's only usable in the article list.

Add OPENBROWSER_AND_MARK to url and item viewformaction

---

include/strprintf.h

When I wrote our strprintf, I didn't realize that anonymous namespaces have internal linkage, i.e. each .cpp file will have its own implementations. As a result, Newsboat binary contained multiple instantiations for the same types, for the grand total of 191Kb:
```
$ bloaty -d symbols -n 50 newsboat | grep -i fmt_impl
0.2%   191Ki   3.6%   183Ki    newsboat::strprintf::(anonymous namespace)::fmt_impl<>()
```
By moving the function into a named namespace, I'm allowing the linker to throw out duplicates, reducing the amount of code almost twofold:
```
0.1%   108Ki   2.0%  98.7Ki newsboat::strprintf::detail::fmt_impl<>()
```
`bloaty` above is Bloaty McBloatface, a size profiler for binaries: https://github.com/google/bloaty
This commit is inspired by this blog post: …

Move strprintf::(anon)::fmt_impl to a `detail` namespace

---

submit-to-coveralls.sh

#951 changed a few lines that shouldn't have affected coverage at all, but Coveralls said it went up by 0.01%. After looking into it, I noticed that a few previous PR builds are also attribute to master, lowering its coverage. Those PRs were made from a master branch, i.e. the contributor didn't create a feature branch to make their changes in.
This PR (hopefuly) fixes that loophole by adding an "owner_name/repo_name" slug in front of all PR branches. All currently outstanding PRs (#842, #889, #914, #950) are still affected by this problem, so we should either rebase them after merging this one, or just ignore their coverage reports.
I also tried to fix a smaller problem where we apparently didn't pass Coveralls the PR number. No idea how it worked before. I'll have to wait for a report …

Prevent PRs from "master" interfering with this repo's coverage

---

src/itemviewformaction.cpp
src/view.cpp

This fixes the issue described below.
---
The "percentage read" field is no longer updated when scrolling up or down.
Before, when stfl was handling keys like `UP` and `DOWN`, it returned an empty event after processing such a keypress.
Now, stfl instead returns the actual key name and we process it like regular keypresses (changed by https://github.com/newsboat/newsboat/pull/913).
This caused the following piece of code to stop working (`update_percent()` only gets called on a `TIMEOUT` event which happens when no key is pressed for 60 seconds).
https://github.com/newsboat/newsboat/blob/5f1ed85aed15636695f7cfc61fbf93b63a9c5ee5/src/view.cpp#L183-L190

Update read percentage after every operation on ItemViewFormAction

---

include/controller.h
include/feedlistformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
include/listformatter.h
include/listwidget.h
include/view.h
mk/mk.deps
src/controller.cpp
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/listformatter.cpp
src/listwidget.cpp
src/pbview.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
src/view.cpp
test/itemlistformaction.cpp
test/listformatter.cpp

All of those commits are meant to be refactors so there should be no change in behaviour.
Most of the commits are just there to make https://github.com/newsboat/newsboat/commit/f524e9407cc4ef692da7f50c88ace2780ca6e3c1 possible.
https://github.com/newsboat/newsboat/commit/a2ad4b7712360e4791d7b79b8267cbb0524f2baf is just an opportunity I saw while making the other changes, if needed, I can submit that commit separately.
These changes don't have much impact and might take some time to review.
@Minoru: Let me know if you rather don't want me to make these kind of changes (relatively high number of lines changed compared to the amount of improvement).

ListWidget: Accept ListFormatter reference instead of separate <formatted text> and <number of lines>

---

src/keymap.cpp
test/keymap.cpp

A user on IRC showed a config like this:
```
macro a `false`
```
This evaluates to `macro a`, i.e. a macro without a command list. This makes no sense, and docs clearly state that the command list is required, so I upped the check.
Reviews are welcome. Otherwise I'll merge in three days.

macro: require at least two arguments

---

Makefile

Remote fonts are considered a privacy breach by lintian, so it's best to disable them IMO.
```
newsboat_2.19-1_amd64.deb
W privacy-breach-generic usr/share/doc/newsboat/faq.html [<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=open+sans:300,300italic,400,400italic,600,600italic%7cnoto+serif:400,400italic,700,700italic%7cdroid+sans+mono:400,700">] (https://fonts.googleapis.com/css?family=open+sans:300,300italic,400,400italic,600,600italic%7cnoto+serif:400,400italic,700,700italic%7cdroid+sans+mono:400,700)
W privacy-breach-generic usr/share/doc/newsboat/newsboat.html [<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=open+sans:300,300italic,400,400italic,600,600italic%7cnoto+serif:400,400italic,700,700italic%7cdroid+sans+mono:400,700">] …
```

Disable remote fonts in html documentation

---

include/inoreaderapi.h
src/inoreaderapi.cpp

API docs don't mention that token. I assume it's just leftovers from copy-paste of The Old Reader code.
I tested this and it still marks articles as read just fine.
(This fulfils a promise I made in https://github.com/newsboat/newsboat/issues/949#issuecomment-633143294).
Reviews are welcome as always. Otherwise I'll merge in three days.

Inoreader: do not request token

---

src/pbview.cpp

I looked through all of the operations listed in `src/keymap.cpp`.
The only inconsistency I found is the one fixed in this PR.
Fixes https://github.com/newsboat/newsboat/issues/958.

Implement OP_REDRAW in podboat

---

src/itemviewformaction.cpp

Fixes https://github.com/newsboat/newsboat/issues/969
The `HtmlRenderer` did not have the duplication issue because it only added links if the url was not yet in the `links` container.

Clear list of links before rendering article

---

include/poddlthread.h
include/scopemeasure.h
src/matcher.cpp
src/poddlthread.cpp
src/scopemeasure.cpp

[`gettimeofday()` is not a monotonic clock](https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time.html), i.e. it can jump back and forth because of NTP, the administrator adjusting time, changes of timezone, etc. This PR replaces all these calls with a monotonic [`std::chrono::steady_clock`](https://en.cppreference.com/w/cpp/chrono/steady_clock).
Kudos to @tejr for sharing the linked article that prompted this.
Reviews are welcome. Will merge in three days.

Don't use gettimeofday() to measure time

---

Cargo.lock
rust/libnewsboat/Cargo.toml

libnewsboat was the only crate using 0.5 -- everything else uses 0.6.
The current version is 0.7.3, but the changelog doesn't mention anything
that absolutely requires an upgrade, so I'll that off until after
Newsboat 2.20 release.
1. https://github.com/rust-random/rand/blob/master/CHANGELOG.md
Reviews are welcome. Will merge in three days.

libnewsboat: bump rand crate to 0.6

---

Makefile

I wanted to send a newsboat-branded notification and found out the logo isn't installed in any standard location to be used.
This puts it in a standard location so any program that wants to reference newsboat can find it.

Install icon

---

test/feedcontainer.cpp

Fixes #558.
I'd be happy if someone could review my test descriptions: do they adequately explain what each sort-order does? Unfortunately, we got directions mixed up, so "ascending" and "descending" are sometimes confusing; that's why I tried to use different words in descriptions, to hopefully make it clear what the expected behaviour is. (I hope to fix "asc" and "desc" in 3.0 sometime in the future).
Will merge in three days.

Split large FeedContainer test into multiple ones

---

.cirrus.yml

FreeBSD 11.4 [just came out](https://www.freebsd.org/news/newsflash.html#event20200616:01). We've been running a snapshot of that version for a while now; time to upgrade to the real thing!
There's nothing to review here, really, so I'll merge once CI is green.

Cirrus CI: update FreeBSD 11.3 to 11.4

---

doc/faq.asciidoc

This summarizes my findings from #825.
I tested it with a simple C program: `int main() { return 1; }`. If I use that as a `browser` on r2.18 tag, navigate to some feed, and try to open an articlce, Newsboat says "Browser returned error code 1". If I wrap the program in a script as described in the FAQ, the message doesn't appear.
I considered re-arranging the questions somehow, but with just five of them, it's hard to see any useful structure. Let them be a list for now. I definitely *don't* want to combine the two browser questions into one, because I think answers should be laser-focused on a particular problem; it's better to have two similar, but simple, answers than to have a single complicated one.
I requested a review from @der-lyse since I run all the docs by him, but everyone …

Add FAQ item about browser errors in 2.18

---

Makefile

GNU install -D and BSD install -D are not equivalent.

Make install-icon portable and unbreak it on FreeBSD

---

.cirrus.yml
docker/ubuntu_16.04-build-tools.dockerfile
docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile

Just a regular update of our CI jobs. I missed the 1.44 release, so we go straight to current stable.
To be clear, this PR does *not* bump the *minimum* supported version. It just updates the CI to check that Newsboat can be built with current stable Rust.
Will merge once CI is green.

Bump Rust to 1.44.1 on CI

---

.cirrus.yml

This should help with catching problems like #1011 (where we used a GNU-specific flag to `install`, breaking installation on BSD).
I've reverted the commit that fixed that issue to check that CI will catch the error. Will remove that before merging, of course.
Reviews are welcome! Will merge no later that Wednesday.

CI: test `make install`

---

include/feedcontainer.h
src/feedcontainer.cpp

Fixes #1025.
Thanks to @dennisschagt for investigating that issue to a point where the problem was rather obvious.
Reviews are welcome! Asking for one from @dennisschagt, since he reproduced the original issue and should be able to easily double-check the fix.
Will merge for 2.20.1 tomorrow.

Make FeedContainer methods thread-safe

---

po/es.po

They are incomplete ("random" is missing), but I can't update them because I don't speak Spanish. Reverting to English for now.
Kudos to @dennisschagt for triaging this.
Fixes #1028.
I intend to release 2.20.1 ASAP, so I'll merge this once I've seen the CI pass.

es.po: revert sort-keys translations

---

.github/workflows/email.yml

Workflow copied from https://cirrus-ci.org/guide/notifications/.
I never used GitHub Actions before, so I'm not sure how this is supposed to work. According to [this forum post](https://github.community/t/who-receives-notifications/17680), the emails are sent to whoever triggered the action; that's whoever submitted the PR or created a merge commit. I'm not entirely happy with that, since I'd like to know about *everything* that's going on in this repo, but oh well, still better than nothing.
The workflow file also doesn't mention email itself. As far as I understand, this is because the workflow generates a *notification*, which is then delivered over web and/or email [depending on your personal preferences](https://help.github.com/en/github/managing-subscriptions-and-notifications-on-git …

Send emails on CI failures

---

.github/dependabot.yml

Dependabot will update dependencies in our Cargo.lock, GitHub Actions, and Docker files.
The presence of this file doesn't affect the build, and it does nothing while on a feature branch, so I'm going to merge this pretty much immediately to get some effect.

Add GitHub Dependabot to the repo

---

.cirrus.yml
README.md
doc/newsboat.asciidoc

All in accordance with the schedule agreed upon in #709. I also took an opportunity to bump the GCC against which MSRV is tested.

Bump minimum supported Rust version

---

src/ttrssapi.cpp

Adding `content_type` check when fetching from ttrss API.
see [#941](https://github.com/newsboat/newsboat/issues/941)

Fix issue 941

---

include/listformaction.h
include/rs_utils.h
include/utils.h
include/view.h
mk/mk.deps
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/feedlistformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/listformaction.cpp
src/utils.cpp
src/view.cpp
test/utils.cpp

This fulfills the promise I made in https://github.com/newsboat/newsboat/issues/825#issuecomment-645615319.
For testing, I used the following config:
bind-key O open-in-browser-and-mark-read
bind-key w open-all-unread-in-browser
bind-key W open-all-unread-in-browser-and-mark-read
Then I ran through these in three configurations:
1. `browser "firefox"` -- to test the happy path;
2. `browser "false"` -- to test the error path where the browser returns a non-zero error code (1, in this case);
3. `PATH= ./newsboat …` -- to test the error path where `sh` itself didn't start.
Reviews are welcome! I'll merge this in three days if no issues are raised.

Make utils::run_interactively return Option<u8>

---

include/view.h
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/view.cpp

There is no null-checking so make sure we can't ever pass a nullptr to these methods.

Pass ItemListFormAction instances as reference

---

include/matcher.h
rust/libnewsboat/src/filterparser.rs
rust/libnewsboat/src/matcher.rs
src/matcher.cpp
test/filterparser.cpp
test/matcher.cpp

As described in https://github.com/newsboat/newsboat/issues/631#issuecomment-651060230, I believe it's best to keep C++ and Rust implementations of `FilterParser` and `Matcher` identical for now. This PR achieves that by removing the only difference between the two: the way the right-hand-side values are stored. Rust now mimics C++, storing everything as a string and converting to a more appropriate type upon evaluation.

Rust FilterParser: store values as strings

---

include/scopemeasure.h
mk/mk.deps
rust/libnewsboat-ffi/src/scopemeasure.rs
rust/libnewsboat/src/scopemeasure.rs
rust/libnewsboat/tests/scopemeasure_dropping_writes_a_line_to_the_log.rs
rust/libnewsboat/tests/scopemeasure_stopover_adds_an_extra_line_to_the_log_upon_each_call.rs
src/scopemeasure.cpp
test/scopemeasure.cpp

Only tests specified that argument; the rest of the code relied on the
default. Rust doesn't have default arguments, though, relying instead on
the builder pattern. It's far better to drop code than to add it, so I'm
removing the argument altogether.
Should have done it before porting ScopeMeasure to Rust, but oh well.

Drop LogLevel argument from ScopeMeasure c-tor

---

.cirrus.yml

CI builds sometimes fail to download the registry from GitHub, which is annoying. This commit extends the cache to include the registry. If I understand Cargo's layout correctly, CI won't touch GitHub anymore unless there is a new dependency that hasn't been fetched yet.

Cirrus CI: cache more of ~/.cargo

---

.cirrus.yml

Tasks on Cirrus CI can be roughly split into the following categories:
1) "ordinary": Linux, different compilers, run both C++ and Rust test   suites;
2) "extra checks": Linux, latest Clang and GCC, run C++ test suite;
3) "platform-specific": FreeBSD, macOS, Linux i686, run both test    suites.
All of these build Newsboat in release mode, since that's how the program is going to be built by the end users. Rust tests are always built in debug mode because they're more useful this way (arithmetic overflow causes panics, making it easier to spot bugs).
Unfortunately, building Rust tests in debug mode means we have to compile most of Rust's stuff *twice*: once in release mode for libnewsboat.a, once in debug mode for tests. Furthermore, release builds take longer than debug builds. Combined, …

Cirrus: use debug config for most Linux builds

---

po/newsboat.pot
rust/libnewsboat/src/filterparser.rs
rust/libnewsboat/src/matcher.rs

This is another step towards implementing #631.
It probably makes sense to tell a bit of a story behind my decisions here. I learned quite a bit about Nom from working on this.
We use Nom crate that implements monadic parsing: our parser is composed of smaller parsers, which in turn rely on even smaller parsers, all the way down to primitive parsers that "parse a character" or "take characters from the stream until a condition is met". Smaller parsers can be combined into larger ones either by sequencing them ("parse a number, then a string") or trying each in turn ("parse a number, *or* a string"). Sequence of parsers fails if any of them fail; a list of alternatives fail if none of the alternatives succeed.
When our parser fails, we get a stack of errors that looks like this:
```
0: at …
```

Add helpful error messages to Rust FilterParser

---

rust/libnewsboat/src/history.rs
test/history.cpp

`History.lines` stores history sorted from most recent to least recent.
We now only reverse the order after taking the `limit` most recent items.
Fixes #1081.

Store most recent history

---

Makefile

For PR https://github.com/newsboat/newsboat/pull/1092 I had to update `doc/keycmds.dsv`.
When invoking make, it did not update `doc/xhtml/newsboat.html`.
The first commit fixes the issue by specifying the missing dependencies.
The other commits are added to slightly improve readability.

Add missing make dependency + various small Makefile improvements

---

doc/keycmds.dsv
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/filebrowserformaction.cpp
src/keymap.cpp
src/pbview.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
test/itemlistformaction.cpp

Related to a question by a user (ruhrdolf) on irc:
```
<ruhrdolf> hi. I updated to 2.20.1 and now the arrows are not working anymore in the Tags menu (key t)
<ruhrdolf> arrows up/down
<ruhrdolf> arrows left/right work
<ruhrdolf> in config i got: bind-key "UP" prev
<ruhrdolf> bind-key "DOWN" next
<ruhrdolf> bind-key j next
<ruhrdolf> bind-key k prev
<ruhrdolf> but neither up/down arrows, nor j/k work in that menu. both work fine in any other context
```
It looks like this configuration is "broken" since https://github.com/newsboat/newsboat/commit/18ddc5a0f96e4833b28022731043ed7f7c6a57ba (PR #913, first included in Newsboat 2.20).
Before that commit, the `UP` and `DOWN` keys were handled directly by STFL (`bind-key` commands had no effect for those keys).

Implement OP_PREV and OP_NEXT for all dialogs containing a ListWidget

---

snap/snapcraft.yaml

I tried building with `snapcraft` but it failed because `g++` could not be found.
Relevant part of the output:
```
Building newsboat 
make -j2
g++ -std=c++11 -O0 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -I/usr/include/libxml2  -I/usr/include/json-c  -D_GNU_SOURCE -D_DEFAULT_SOURCE  -DHAVE_OPENSSL=1  -o src/controller.o -c src/controller.cpp
make: g++: Command not found
Makefile:136: recipe for target 'src/controller.o' failed
make: *** [src/controller.o] Error 127
Failed to run 'make -j2' for 'newsboat': Exited with code 2.
Verify that the part is using the correct parameters and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

Snap: Specify 'g++' build dependency

---

src/inoreaderapi.cpp

Remove unnecessary parameters from the URL request made to Inoreader
to mark articles as 'read/unread', as these parameters are making the
requests invalid. Altough marking articles as read still works, marking
them as unread does not.
Fixes: #1109

Fix Inoreader's 'mark as unread' not working issue

---

include/cache.h
include/rssitem.h
mk/mk.deps
src/cache.cpp
src/rssitem.cpp

Fixes https://github.com/newsboat/newsboat/issues/111.
Fixes https://github.com/newsboat/newsboat/issues/218.
Still needs some testing, marking as draft for now.
I expect to have time for testing during the weekend.
This loads article content from the sqlite database one at a time.
Performance is relatively bad (when testing with cache containing ~30000 items) but at least matching on `content` can be used.
I'm pretty sure this does not slow down query feeds and ignore-article rules which do not use the `content` attribute.

Load article text when trying to match on `content` attribute.

---

.cirrus.yml

Cirrus sometimes fails to unpack the cache archive, and removes the "cache folder" before retrying. When we used ~/.cargo as a "cache folder", these failures wiped out ~/.cargo/bin and broke the build.
This commit moves cacheable stuff to ~/cargo-cache, hopefully making the tasks immune to cache unpacking failures.
I plan to merge this once CI is green, but I'm open to discussions even after that.

Cirrus: keep cacheable stuff in a separate directory

---

CHANGELOG.md
doc/configcommands.dsv
include/keymap.h
include/view.h
src/controller.cpp
src/keymap.cpp
src/view.cpp
test/data/test-config.txt
test/keymap.cpp

Related to (but not necessarily a complete fix for):
- https://github.com/akrennmair/newsbeuter/issues/402
- https://github.com/akrennmair/newsbeuter/issues/41
- https://github.com/newsboat/newsboat/issues/888
Obsoletes https://github.com/newsboat/newsboat/pull/889

Add a "run-on-startup" option

---

doc/chapter-tagging.asciidoc
src/rssfeed.cpp
test/feedcontainer.cpp
test/rssfeed.cpp

Fixes #1128 
Please check the commit messages for all the needed information.

Fix for "Make Inoreader 'sort by firsttag' useful" #1128

---

include/dirbrowserformaction.h
include/filebrowserformaction.h
include/listformatter.h
include/utils.h
mk/mk.deps
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/itemlistformaction.cpp
src/listformatter.cpp
src/pbview.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
src/utils.cpp
stfl/dialogs.stfl
stfl/dllist.stfl
stfl/feedlist.stfl
stfl/filebrowser.stfl
stfl/selecttag.stfl
stfl/urlview.stfl
test/listformatter.cpp

Fixes https://github.com/newsboat/newsboat/issues/72.
Fixes https://github.com/newsboat/newsboat/issues/1126.
This works around [an stfl bug](https://github.com/dennisschagt/stfl/issues/3) by just not using the (slightly) broken feature.

Stop using `pos_name` attribute in stfl

---

src/feedcontainer.cpp
test/feedcontainer.cpp

This PR supersedes #1121.
This affects:
- `-x print-unread` CLI option
- notifications that are displayed after reloads (configured via `notify-*` settings)
Fixes #444.
Fixes #1120.
Reviews are welcome! If no issues are raised, I'll merge this on Saturday.

Do not double-count unread items

---

contrib/feedgrabber.rb

The feedgrabber.rb script was using ~/.newsbeuter/ as directory to store
the cache file. Change it to ~/.newsboat.

contrib: change feedgrabber.rb cachedir from newsbeuter to newsboat

---

.cirrus.yml
.travis.yml

1. FreeBSD 11.4 build is failing because [the "rust" package is missing](https://cirrus-ci.com/task/5392278598451200?command=install#L129). It's present in a "quarterly" repo, but is absent from "latest". I allowed this build to fail for now, and disabled notifications so GitHub doesn't see the failing build at all.
2. Code coverage build on Travis [fails because the C++ test suite segfaults](https://travis-ci.com/github/newsboat/newsboat/jobs/379049336#L957). This appears to be caused by Rust Nightly migrating to LLVM 11 (https://github.com/rust-lang/rust/issues/76085). Everything works fine if I build the C++ part with Clang 11 (which also uses LLVM 11), so that's the fix I apply here.
I intend to merge this as soon as the builds finished, to get "master" back to green. But if you have …

Fix CI builds

---

.cirrus.yml
docker/ubuntu_16.04-build-tools.dockerfile
docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile

This is nothing fancy, just mundane updates, so I'll merge this once CI builds pass.

Bump Rust to 1.46.0 on CI

---

src/htmlrenderer.cpp
test/htmlrenderer.cpp

Fixes https://github.com/newsboat/newsboat/issues/1158.
Resulting output of item mentioned in that issue:

Display correct type of numbers in nested list's items

---

.cirrus.yml

This reverts commit 25d5ff744b931caf4f4571937be6d1b2bfd5d94c.
The build with FreeBSD 11.4 succeeds now: https://cirrus-ci.com/task/5515721159475200

Revert "Cirrus: Allow FreeBSD 11.4 to fail"

---

include/colormanager.h
include/controller.h
include/pbcontroller.h
include/pbview.h
include/view.h
mk/mk.deps
src/colormanager.cpp
src/controller.cpp
src/pbcontroller.cpp
src/pbview.cpp
src/view.cpp
test/colormanager.cpp

Improvements:
- Don't handle 0 color rules as a special case (related to `colors_loaded`)
- Make it explicit that there are always the same amount of foreground colors, background colors and attribute vectors
- Remove code duplication between `ColorManager::set_pb_colors()` and `View::apply_colors()`

Refactor ColorManager

---

include/cache.h
include/controller.h
include/feedcontainer.h
include/rssfeed.h
src/cache.cpp
src/controller.cpp
src/feedcontainer.cpp
src/feedlistformaction.cpp
src/opml.cpp
src/reloader.cpp
src/rssfeed.cpp
test/feedcontainer.cpp

While investigating #1163, I found that `newsboat -r` segfaults for me with the following backtrace:
```
#0  0x000056442a4a8976 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size (this=0x98) at /usr/include/c++/10/bits/basic_string.h:2833
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_check (__s=0x56442a705270 "basic_string::substr", __pos=0, this=0x98) at /usr/include/c++/10/bits/basic_string.h:312
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr (__n=6, __pos=0, this=0x98) at /usr/include/c++/10/bits/basic_string.h:2835
#3  newsboat::RssFeed::is_query_feed (this=0x0) at include/rssfeed.h:142
#4  newsboat::Reloader::reload (this=0x56442bd73690, pos=1, max=567, …
```

Fix SIGSEGV when running `newsboat -r`

---

src/rssfeed.cpp
test/rssfeed.cpp

This bugfix is inspired by https://github.com/newsboat/newsboat/issues/1167. While trying to reproduce that issue, I created the following query feed:
"query:only interest:title =~ \"vivid:\""
To my surprise, Newsboat then failed to start:
> Error while loading feed 'query:only interest:title =~ "vivid:"': `title =~ "vivid:' is not a valid filter expression
Note how the closing quote is missing at the end of the filter expression.
The problem was in RssFeed::set_rssurl(), which splits the query line into three components: "query:" prefix, the title, and the filter expression. set_rssurl() used utils::tokenize_quoted() for that, with colon as a delimiter.
If we just split the query on a colon, we get four tokens:
1. query
2. only interest
3. title =~ "vivid
4. "
But "_quoted" means that …

Fix query feeds with colons in quoted regex

---

doc/keycmds.dsv

While trying to figure out the command to open a specific URL in the browser, I found that the keybindings `0-9` were not properly documented.
In my case, I wanted to create a macro to send podcast audio URLs to mpv. The commands `one`, `two`, `three`, etc. are exactly what I was looking for (I actually found them in the article view help dialog). Here's an example:
```sh
browser firefox
macro p set browser "mpv"; one ; set browser "firefox"
```
In this PR, I add the missing commands under the "Available Operations" section of the docs.
Please note that i'm not setup to test the end result. Feel free to modify as needed.

Add documentation to open specific URLs in browser

---

test/utils.cpp

PR #1172 changed the implementation of utils::run_command(), which
caused this function to sometimes take more than a second to execute,
failing the test:
test/utils.cpp:634: FAILED:
REQUIRE( runtime.count() < 1000 )
with expansion:
1087 (0x43f) < 1000 (0x3e8)
I couldn't reproduce this locally even though I ran the tests in a loop
for half an hour. This makes me think that this is a peculiarity of the
CI environment, not an actual bug in utils::run_command().
Since the test spawns `sleep 5`, it should be sufficient to check that
the function's runtime didn't exceed five seconds. Anything under that
guarantees that the function *didn't* wait for the `sleep` to finish.
I intend to merge this once the CI passes, but feel free to leave any comments you have even once this is merged — we can …

Make utils::run_command() test less flaky

---

doc/internal/howto-release.md
po/ca.po
po/de.po
po/es.po
po/fr.po
po/hu.po
po/it.po
po/ja.po
po/nb.po
po/newsboat.pot
po/nl.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sk.po
po/sv.po
po/tr.po
po/uk.po
po/zh.po
po/zh_TW.po

This updates the POT file, as well as the translations for the two languages that I maintain.
I used to write "Call for translations" emails, but they never resulted in more translations, so I'm trying something new today: I've created @newsboat/translators team and invited everyone who translated something since 2017 onwards. From now on, I'll update the POT file two weeks before the release, and highlight that team. You all will get emails, and will have two weeks to update your translations and submit PRs. I'm open to suggestions on how to improve that, of course.
Since not everyone accepted the invite to the team yet, I'm mentioning everyone directly too: @adiel-mittmann @alejandrogallo @der-lyse @carno @deob83 @bitigchi @programandala-net @esteban123456789 @tkerdonc @dennisschagt …

Update Russian and Ukrainian translations

---

.cirrus.yml

The names said we're using Rust 1.45, whereas in reality we are using
1.46.0. I think they got out of sync because the names use MAJOR.MINOR
numbers, while Dockerfiles use the full MAJOR.MINOR.PATCH numbers. When
I update the version, I usually just grep for the previous one and
replace all occurrences. Since "1.45" didn't match "1.45.0", I didn't
replace it, leading to the discrepancy.
This patch changes all the numbers to the full version, so I shouldn't
fall into the same trap ever again.
(This shouldn't break CI, but I'll still wait for it to pass before merging.)

Fix Rust version in CI task names

---

README.md
doc/newsboat.asciidoc

I added an email forward from security@newsboat.org to my email, and would like to encourage people to report vulnerabilities there.
In addition to these changes to the docs, I added the following paragraph to [the website](https://newsboat.org/):
> If you have found a vulnerability, please email security@newsboat.org, and use the aforementioned PGP key if at all possible.
I'm open to suggestions on how to better phrase this, where to put it etc. Also open to feedback on the overall process. (I requested a review from @der-lyse because I run all the docs PR by him, and because I want to make sure at least one other person took a look at this.)
Will merge in three days if this is approved by @der-lyse and no-one else raised any issues.

Explain where to send vulnerability reports

---

include/pbcontroller.h
podboat.cpp
src/pbcontroller.cpp

9c720413519aa29b1bb1ef3be9fff5e1696bba55 introduced a bug: `podboat
--help` segfaults after printing out the help message.
That commit split out some initialization code from
`PbController::run()` into a new method, `initialize()`. That new method
didn't *always* initialize the object; if --help or an unknown option
was passed into Newsboat, the method would print out the usage message
and return EXIT_SUCCESS.
However, this same EXIT_SUCCESS value was used to indicate that the
initialization was successful. As a result, Podboat proceeded to use
unitialized PbController, and crashed.
To fix this, I changed `PbController::initialize()` to call `exit(3)`
directly when it wanted to quit Podboat.
Requesting a review from @dennisschagt because he's the last one to change that code. Will merge …

Fix segfault in podboat --help

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/filterparser.rs

Kudos to @dennisschagt for spotting the missing i18n calls:
https://github.com/newsboat/newsboat/pull/1189#discussion_r490950023

Internationalize errors in Rust FilterParser

---

doc/configcommands.dsv
doc/newsboat.asciidoc

Passwords may contain double quotes and backslashes, which require
quoting when inside double quotes. Our docs had notes about the double
quotes, but didn't mention backslash -- the user had to click through
a link and read a section to find out about backslashes. To my
knowledge, this didn't cause anyone any trouble, but I think it's best
to forestall the problem by always mentioning both characters.

Note that both " and \ need quoting

---

doc/cmdline-commands.dsv
doc/keycmds.dsv

This commit fixes a couple issues:
1. it doesn't use the name of the operation to describe it. This
helps searchability, as there are now two keywords in the text
("save" and "export");
2. it mentions that the output format is plain text. Commandline doc
already hinted at that via ".txt" extension, but I made it clear in
the text as well.
Inspired by #1210.
Comments are welcome! As usual, @der-lyse can merge this if he approves, or I'll merge this in three days myself.

Improve docs for `save` and `save-all`

---

doc/keycmds.dsv
src/keymap.cpp

I understand that:
- From the feed list, `open-in-browser` opens feed link.
- From the article list, `open-in-browser` opens article link.
- From the article view, `open-in-browser` opens article link.
- From the url view, `open-in-browser` opens selected link.
That's why I clarify that `open-in-browser` can be also be used for those tasks.

docs: clarify open-in-browser operation

---

.cirrus.yml
Makefile

Just like `-D warning` for Rust and `-Werror` for C++, we should treat warnings as errors for Asciidoctor. This will safeguard from errors [like this one](https://github.com/newsboat/newsboat/pull/1201#discussion_r501855441).

CI: fail on Asciidoctor warnings and errors

---

include/view.h
src/view.cpp

Fixes https://github.com/newsboat/newsboat/issues/893.

Support tab-completion and ^U/^K/^G/^W for cmdline in modal forms

---

newsboat.cpp
src/pbcontroller.cpp

The `--help` option to both `newsboat` and `podboat` executables will now display support information along will their usage.
This resolves issue #1233

Added support info in --help output

---

src/rssitem.cpp
test/rssitem.cpp

Fixes https://github.com/newsboat/newsboat/issues/1227.
This only removes duplicate spaces when displaying titles.
It might make sense to remove duplicate whitespaces on a lower level (e.g. in getters like `title()`/`get_title()` or even when retrieving titles in `Cache`) but I'm not sure it is a good idea.

Remove duplicate whiespace from item titles when displaying in list/head

---

contrib/exportOPMLWithTags.py

As discussed in #871, I add this script. It's useful to export the urls file to OPML including tags.

Add contrib/exportOPMLWithTags.py

---

.cirrus.yml
docker/ubuntu_20.10-build-tools.dockerfile

Also migrate the "more checks" and "sanitizer" jobs to Clang 11, since it makes sense to run those with the latest-and-greatest compiler.
Reviews are welcome! I'll merge this in three days if no issues are raised.

Add Clang 11 to CI

---

.cirrus.yml

FreeBSD 12.2 came out [today](https://www.freebsd.org/releases/12.2R/relnotes.html), let's upgrade!
Will merge once the CI checks pass.

CI: upgrade to FreeBSD 12.2

---

include/download.h
src/download.cpp
src/pbview.cpp
src/poddlthread.cpp

When the user is highlighting a failed download, the reason will now be
reported in the status line. #1209

Display reason of download failure in podboat

---

src/controller.cpp

This fixes a regression introduced by https://github.com/newsboat/newsboat/pull/1245.
Before the regression, the `urls` file could be omitted when importing an OPML file or when using an online service (e.g. miniflux).
This commit restores that behaviour.
It still prints the error message to help users diagnose issues in case of missing urls or if there are still 0 urls configured.
Relevant file/change in which I introduced the regression:
https://github.com/newsboat/newsboat/pull/1245/files?file-filters%5B%5D=.cpp#diff-53fc727c3acacc0c0b7c531be394c8074b1211826f68cff4e8217b65c536ab8f

Continue execution, even when loading urls file fails

---

src/controller.cpp
src/feedhqurlreader.cpp
src/inoreaderurlreader.cpp
src/minifluxurlreader.cpp
src/newsblururlreader.cpp
src/ocnewsurlreader.cpp
src/oldreaderurlreader.cpp
src/ttrssurlreader.cpp

Fixes https://github.com/newsboat/newsboat/issues/1273.
Tested with a local Nextcloud setup to verify that this actually works (I should have done that before submitting https://github.com/newsboat/newsboat/pull/1269).

Continue loading feeds from external services even when `urls` file can't be opened

---

src/controller.cpp

Fixes https://github.com/newsboat/newsboat/issues/220.

Mark items read on remote service when using mark-feed-read in query feed

---

src/controller.cpp

@arjan-s at https://github.com/newsboat/newsboat/issues/220#issuecomment-725632690:
> There is one bug in the current code: it also performs the API call for articles that were already marked read. Changing this to only mark unread articles as read would improve the performance a lot.
Good idea, implemented in this PR.

External APIs: Only mark unread items as read

---

.travis.yml

I forgot to edit .travis.yml when I introduced this Make target in
81895ba20b12db3d0c4f0e51956d672d62f6f748 (#1265).

Use `make ci-check` on Travis

---

src/pbcontroller.cpp

Fixes https://github.com/newsboat/newsboat/issues/1288

Register (and ignore) `run-on-startup` option in podboat

---

include/ocnewsapi.h
include/remoteapi.h
src/controller.cpp
src/ocnewsapi.cpp
src/remoteapi.cpp

Supersedes https://github.com/newsboat/newsboat/pull/1283, using @Minoru's idea https://github.com/newsboat/newsboat/pull/1283#issuecomment-726965670:
> I also wonder if it would make more sense to add mark_all_read() to RemoteAPI. We can provide a default implementation that calls mark_read() in a loop, and OcNewsApi can provide an optimized implementation. This neatly avoids the problem with shared state.

Nextcloud: Mark multiple items read in single request

---

src/itemlistformaction.cpp

Pull request which aims to fix https://github.com/newsboat/newsboat/issues/657
Remove `yes to all` and `no to all` option when only one single file is found as candidate for conflict while saving feeds.
Although, the new conflict prompt still allows usage of `a` and `q` option, it will not create any undesired side effects. Therefore, I did not handle key press event in both branches and thereby keep the implementation simple.
Thanks @Minoru for providing a detailed instruction about how to reproduce this issue.

Modify option set for single conflict case while saving feeds

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/filterparser.rs

fixes #1077
I made a new error type for the parser and a combinator called `expect` which resembles the `context` combinator.

Replace string constants with a proper enum in FilterParser

---

include/logger.h
rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat-ffi/src/logger.rs
rust/libnewsboat/src/cliargsparser.rs
rust/libnewsboat/src/logger.rs
src/cliargsparser.cpp
src/logger.cpp
src/pbcontroller.cpp
test/test-helpers/loggerresetter.cpp

This PR removes the NONE/None logging level as those enum constants/variants are never used by the client code.

Remove "none" logging level

---

include/rssitem.h
rss/atomparser.cpp
rss/atomparser.h
rss/item.h
rss/medianamespace.cpp
rss/rss09xparser.cpp
rss/rss10parser.cpp
src/cache.cpp
src/itemlistformaction.cpp
src/itemrenderer.cpp
src/rssitem.cpp
src/rssparser.cpp
test/cache.cpp
test/itemlistformaction.cpp
test/itemrenderer.cpp
test/rssitem.cpp
test/rsspp_parser.cpp

This can be used as part of a solution for:
- https://github.com/newsboat/newsboat/issues/468
- https://github.com/newsboat/newsboat/issues/1010
- https://github.com/newsboat/newsboat/issues/1022
- https://github.com/newsboat/newsboat/issues/1176 (maybe related)
Fixing the above issues might require per-feed `text-width` configuration.

Store mime-type together with each article's content

---

.cirrus.yml
.travis.yml
docker/i18nspector.dockerfile

This brings us one step closer to ditching Travis entirely. Cirrus CI, with its built-in handling of Dockerfiles, is just perfect.
I'm already working on moving the Coveralls job as well, so I'll merge this PR after just one day. Reviews and comments are still welcome though!

Move i18nspector job from Travis to Cirrus

---

include/view.h
src/controller.cpp
src/formaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/view.cpp

A small improvement on top of https://github.com/newsboat/newsboat/pull/1259.
This reduces screen-flickering (caused by drawing the `EmptyFormAction`) and might be a bit faster (single curses call without waiting for 1 ms timeout).

Use flushinp() instead of ignoring input events one-by-one

---

.cirrus.yml

Fixes #1225
I am relatively new to continuous integration services, so I could be wrong about this change. It seems as though it fixes the problem.

"More warnings and errors" now do release builds

---

include/controller.h
src/controller.cpp

Fixes https://github.com/newsboat/newsboat/issues/1318.

Only create lock-file after applying `cache-file` option

---

src/regexmanager.cpp
test/regexmanager.cpp

Fixes https://github.com/newsboat/newsboat/issues/635.

RegexManager: Dump both "highlight" and "highlight-article" rules

---

include/fslock.h
rust/libnewsboat-ffi/src/fslock.rs
rust/libnewsboat/src/bin/lock-process.rs
rust/libnewsboat/src/fslock.rs
rust/libnewsboat/tests/fslock.rs
src/controller.cpp
src/fslock.cpp
src/pbcontroller.cpp
test/fslock.cpp

Fixes https://github.com/newsboat/newsboat/issues/314.
Example output when the lock file is not writable:

Provide a reason when lock-file can't be opened or locked

---

mk/mk.deps
rust/libnewsboat-ffi/build.rs
rust/libnewsboat-ffi/src/keymap.rs
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat/src/keymap.rs
rust/libnewsboat/src/lib.rs
src/keymap.cpp
src/utils.cpp
test/keymap.cpp

That title is a mouthful. This commit fixes #1200, so just read that issue for the reproduction steps.
Reviews are welcome as always. Will merge once @dennisschagt approved this, or in three days if no issues are raised.

Fix semicolons in macro operations' arguments breaking parsing

---

.github/workflows/coveralls.yaml

Coveralls CI job uses Rust Nightly, which issues numerous warnings about our code. GitHub turns those into annotations under each PR, which is annoying. I'm not interested in fixing warnings from Rust releases other than stable, so I suppress them here.
Reviews are welcome! I'll merge this in three days if no issues are raised.

CI: suppress annotations from Coveralls job

---

include/utils.h
mk/mk.deps
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/controller.cpp
src/fileurlreader.cpp
src/utils.cpp
test/fileurlreader.cpp
test/utils.cpp

Fixes https://github.com/newsboat/newsboat/issues/844.
Current output when urls file contains an invalid unicode character:
I think it would be helpful to include the line number of the first line containing an invalid unicode character.

Add `read_text_file()` function which detects and rejects invalid unicode characters

---

rust/libnewsboat-ffi/src/utils.rs

Fixes #801.
I looks like our testing framework (Catch2) does not allow testing for SIGABRT.
Manual testing showed that this works as expected,
using line `REQUIRE(utils::get_command_output("echo -e \"test:\xff\"") == "expecting a test FAIL");`:

Don't tolerate invalid utf-8 in utils::get_command_output() input argument

---

include/colormanager.h
include/configcontainer.h
include/confighandlerexception.h
include/configparser.h
include/controller.h
include/filtercontainer.h
include/keymap.h
include/regexmanager.h
include/utils.h
mk/mk.deps
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
src/colormanager.cpp
src/confighandlerexception.cpp
src/configparser.cpp
src/controller.cpp
src/fileurlreader.cpp
src/filtercontainer.cpp
src/keymap.cpp
src/pbcontroller.cpp
src/regexmanager.cpp
src/rssignores.cpp
src/utils.cpp
test/colormanager.cpp
test/configparser.cpp
test/data/config-invalid-utf-8
test/remoteapi.cpp
test/utils.cpp

This employs the new `read_text_file()` function to fix the same bug as #844, but for configs. I had to rework the bridge for `read_text_file()` so I could distinguish between "failed to open" and "failed to read" errors on the C++ side — `ConfigParser` returns `false` on the former but throws `ConfigException` on the latter. A lot of churn, but conceptually a pretty simple fix.
On an input from #723, this now errors appropriately:
```
$ newsboat
Starting newsboat r2.21-304-g2698-dirty...
Loading configuration...Failed to read line 1 (stream did not contain valid UTF-8)
```
The error message could be better, e.g. it could show the path to the file. However, this would require adding a new string to the POT file, which we already shipped off to translators (in #1339). I don't think it's …

Do not crash on invalid UTF-8 configs

---

Makefile
include/feedlistformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
src/feedlistformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp

https://github.com/newsboat/newsboat/pull/1335#issuecomment-739505009 suggests adding a new operation (`open-in-background-browser`) which will probably require code similar to the `OP_OPENINBROWSER` operation.
In this PR, I try to extract that (soon-to-be) duplicate code into separate functions.

Reduce (future) code duplication for code related to using open_in_browser()

---

src/view.cpp

Fixes https://github.com/newsboat/newsboat/issues/1369.

Don't call `run()` on empty formactions

---

src/itemlistformaction.cpp

Without this change, the list is redrawn on each iteration, which is
expensive because redrawing involves invalidation and thus re-formatting
all the items in the list.
Fixes #1372.

Itemlist: reset `do_redraw` after acting on it

---

include/cache.h
src/cache.cpp
src/controller.cpp

Feeds/items become unreachable when the user decides to delete a feed. 
This PR adds logic to remind them that they can decide to remove them with either:
* running `newsboat --cleanup` or 
* setting `cleanup-on-quit yes` in their config file
Suggested by #1184

Nudge users towards enabling `cleanup-on-quit` or running `newsboat --cleanup`

---

.github/workflows/coveralls.yaml

Specifically, this ignores code genereated by cxxbridge in `target/cxxbridge/libnewsboat-ffi/src`:

Code coverage: Ignore generated code

---

.cirrus.yml

macOS builders are a scarce resource and low parallelism (only one job
at a time). This commit combines four jobs into two, which should
hopefully make our CI a little bit faster. We *could* miss some problems
this way, but I don't think the risk is very high because:
1. I haven't seen macOS build failures in a while;
2. we have an extensive build matrix for Linux, which checks plenty of
compiler combinations. The purpose of macOS CI jobs is, then, to
ensure that Newsboat builds there at all — compiler-specific bugs
will be caught by Linux anyway.
This is just maintenance, so I think I'll merge this on a short timeline — tomorrow. Reviews are still welcome though if you feel like it ;)

CI: decrease the number of macOS jobs

---

.cirrus.yml

Also fixes the name of the job, which I forgot to update in 7b2a91d383632e26f4e279f3fbc7f37f9e013e27.
I'll merge this once macOS jobs pass in CI.

Fix Homebrew clones on macOS Catalina

---

include/rssfeed.h
src/cache.cpp
src/feedlistformaction.cpp
src/itemlistformaction.cpp
src/rssfeed.cpp
src/rssparser.cpp
test/cache.cpp
test/feedcontainer.cpp
test/itemlistformaction.cpp
test/itemrenderer.cpp
test/opml.cpp
test/rssfeed.cpp
test/rssitem.cpp

Previously, a feed's rssurl could get overwritten accidentally, leading to https://github.com/newsboat/newsboat/issues/685.
This PR makes sure we can no longer overwrite a feed's rssurl (by marking it const).

Make sure we can't accidentally overwrite a feed's rssurl

---

doc/chapter-files.asciidoc
doc/chapter-firststeps.asciidoc
doc/manpage-newsboat.asciidoc
doc/manpage-podboat.asciidoc
test/utils.cpp

The main idea behind this PR came from https://github.com/newsboat/newsboat/pull/1382#discussion_r548750032, because I was surprised that Podboat calls its locks differently depending on which file layout it uses — dotdir or XDG. The rest of changes here are just me trying to make the doc a little bit better while I'm at it.
Reviews are very much welcome, and since it's documentation and it's the New Year soon, I think I'll wait a bit longer before merging — let's say a week. As usual, I'm explicitly asking for a review from @der-lyse, who usually reviews the docs.

Document locations of lock files

---

stfl/empty.stfl

Fixes https://github.com/newsboat/newsboat/issues/1399.
I want to check a bit more thoroughly if we have any similar interactions with STFL which could be broken.
I plan to do that later today.

Add "hints" field to avoid crash when swapping title with hints

---

.cirrus.yml
Makefile
src/feedlistformaction.cpp
src/itemlistformaction.cpp

This is the PR I promised in https://github.com/newsboat/newsboat/issues/1351#issuecomment-753624763. Please read the commit messages here to get the whole story.
I plan to ship this with 2.22.1, so I'll merge tomorrow. Reviews are welcome though!

Do not trigger -Wmaybe-uninitialized on GCC 9 with -O2 (and check this in CI)

---

CHANGELOG.md
doc/cmdline-commands.dsv
doc/hackers-guide.asciidoc
include/colormanager.h
include/formaction.h
include/view.h
mk/mk.deps
src/colormanager.cpp
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/formaction.cpp
src/helpformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/pbview.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
src/view.cpp

Relevant quotes from the [`stfl_run()` documentation](http://svn.clifford.at/stfl/trunk/README):
> Return the next event. If no more prior generated events are waiting display
> the form and process one input character. The event string can be an null
> value when something changed in the form (e.g. the user changed the focus of
> the current widget) but all inputs have been handled internally inside of STFL.
>The … parameter is a timeout in ms. When no key has been pressed until this
> timeout has been reached the function returns with a "TIMEOUT" event. Set this
> parameter to 0 to disable the timeout.
> 
> When the timeout parameter is set to -1 the form is displayed independent of
> the current status of the event queue and the function returns right after
> displaying the form …

Add descriptive names for special values passed to stfl_run()

---

include/htmlrenderer.h
src/htmlrenderer.cpp
test/htmlrenderer.cpp

\<div> is a "block element", meaning it should be rendered on a new line. We treat is the same as \<p>.
Fixes #1405.
@tsipinakis, please test this, and review the code if you have a moment to spare :)

Render <div>s onto a new line

---

src/feedlistformaction.cpp

`pos` stores a position into the full list of feeds while `visible_feeds` only contains feeds which are not filtered out.
The check is not necessary as the result of the following `FeedContainer::get_feed()` is checked anyway (it returns nullptr if the index is out of bounds).
Git bisect points to https://github.com/newsboat/newsboat/commit/7f6ce535a715779e5ff937e6ff56bda4c7831c18 as the commit which introduced this small regression.

FeedList: Remove faulty position validation

---

.gitignore
Makefile
include/regexowner.h
include/scopemeasure.h
mk/mk.deps
rss/parser.cpp
rss/rssparserfactory.cpp
rss/rssparserfactory.h
test/data/test-urls.txt
test/fileurlreader.cpp
test/opml.cpp
test/test-helpers/maintempdir.cpp
test/test-helpers/maintempdir.h

It's been on my personal to-do list for a while to run CppCheck on Newsboat and see what it finds. Newsbeuter already had a Make target for that, so I updated it a bit and got a pretty short report with nothing really interesting in it. Most of the report is CppCheck being unable to parse our tests, plus a few suggestions that I don't want to apply.
It'd probably be better to add CppCheck to CI, but that would require: 1) adding suppression comments for things that I don't want to fix; 2) grepping out parse errors so they don't fail the build. Frankly, I'm too lazy for that at the moment, so I just added a monthly task for myself to re-run CppCheck manually and see what pops up. If it keeps turning up somewhat useful things, I'll probably get motivated enough to add it to CI :)
Reviews …

Address some of CppCheck's suggestions

---

.github/workflows/coveralls.yaml
docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_20.10-build-tools.dockerfile
include/utils.h
src/feedlistformaction.cpp
src/itemlistformaction.cpp
src/utils.cpp
test/test-helpers/envvar.h
test/utils.cpp

This is a little detour from #1344, but kind of productive as well. Added some tests, plus a little helper function to save on typing in a few places.
Reviews are welcome! If no issues are raised, I'll merge in three days.

Add utils::locale_to_utf8()

---

src/listformaction.cpp

Fixes https://github.com/newsboat/newsboat/issues/1449

Synchronize article-read status when executing `open-all-unread-in-browser-and-mark-read`

---

src/itemlistformaction.cpp

A copy-and-paste error in 54617872ff36d7420505e4c82cc08a14ed16f6c3
changed "false" to "true", and so `open-all-unread-in-browser` started
behaving the same as `open-all-unread-in-browser-and-mark-read`.
This is dead-simple fix, so I'll merge it tomorrow when the CI jobs are done.

Fix regression introduced by 54617872ff36d7420505e

---

.cirrus.yml
Makefile
test/utils.cpp

Turns out `--order=rand` does *not* provide random ordering on each
invocation[1] — we need `--rng-seed=time` for that. Performing tests in
randomized order is important because it helps us find and break
unintended dependencies between cases.
1. https://github.com/catchorg/Catch2/issues/2161
This change turned up a problem with tests for `utils::convert_text()`:
that function calls `utils::translit()`, which `abort()`s the whole
process if `iconv()` does not support the requested conversion. The
`abort()` is not a bug; there's nothing better we can do in that
situation. However, `abort()` is inconvenient for tests. I couldn't find
any better solution than deleting the offending test.
I ran this in a loop for 1545 times, and it never failed. This doesn't
prove much — to execute all 535 …

Run C++ tests with time-based RNG seed

---

src/controller.cpp

The return type of `opml::import()` changed from `bool` (indicating success) to `nonstd::optional` (indicating an error) in 036c637f72ec873fc4a7986138684d9ccd4de12b, but an `if` that acted on the return wasn't updated, causing the program to show error on success and report success on error.
Reported on IRC by dngray.
Reviews are welcome! Will merge in three days.

Do not misreport successful OPML import as failure

---

doc/faq.asciidoc

As per an IRC discussion, just highlighting that, regardless of the Newsboat version (to date), references to `/usr/bin` will throw error code 127 as command not found, and references to `/home` will throw 126 as permission denied. But `xdg-open` is respected, and so offers an option for invoking the default browser without making further configuration changes.
Oh, and I fixed a typo.

And a subsection re snap

---

Cargo.lock

This fixes the compile error that made 0.7.4 fail to build with recent Nightly compilers (in turn failing our PRs #1459 and #1461). The change in Nightly was reverted, giving lexical-core time to get fixed (https://github.com/Alexhuszagh/rust-lexical/issues/55). Now that that's done, we can expect the change to be re-introduced into Nightly, and so we have to update to lexical-core 0.7.5 lest our build breaks again.
This PR is just mundane maintenance, so I'll merge it once the CI is green. Feel free to leave a comment anyway if you have something to say ;)

Bump lexical-core to 0.7.5

---

Cargo.lock

This pulls in a fix for https://rustsec.org/advisories/RUSTSEC-2021-0023.html.
This vulnerability doesn't affect any released Newsboat version, since dependency on rand_core 0.6.0 was added [a day after 2.22 release](https://github.com/newsboat/newsboat/commit/f1286147379c72fa3bf2bb04fcd3c5d18acbdb74). 2.22.1 is not affected because patch releases are based off the minor release, not the master branch.
I'll merge this once CI is green.

Bump rand_core to 0.6.2 to patch RUSTSEC-2021-0023

---

.cirrus.yml
docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_20.10-build-tools.dockerfile
rust/libnewsboat/tests/configpaths_create_dirs_returns_false_if_xdg_config_dir_exists_but_data_dir_doesnt_and_couldnt_be_created.rs
rust/libnewsboat/tests/configpaths_create_dirs_returns_true_if_both_config_and_data_dirs_exist_now.rs
rust/libnewsboat/tests/configpaths_returns_paths_to_newsboat_xdg_dirs_if_they_exist_and_dotdir_doesnt.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_config_paths_were_specified_via_cli.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_empty_newsboat_xdg_config_dir_already_exists.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_empty_newsboat_xdg_data_dir_already_exists.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_newsboat_xdg_config_dir_couldnt_be_created.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_newsboat_xdg_data_dir_couldnt_be_created.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_urls_file_already_exists.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_migrates_default_newsbeuter_xdg_dirs_to_default_newsboat_xdg_dirs.rs
rust/libnewsboat/tests/locale_to_utf8_converts_text_from_the_locale_encoding_to_utf8.rs
rust/libnewsboat/tests/utf8_to_locale_converts_text_from_utf8_to_the_locale_encoding.rs
rust/libnewsboat/tests/utf8_to_locale_transliterates_characters_unsupported_by_the_locale_encoding.rs
rust/strprintf/src/lib.rs
rust/strprintf/src/traits.rs

section_testing crate that we use in some integration tests now trigger `non_fmt_panic` warning. I submitted [a pull request](https://github.com/evanw/section_testing/pull/1) that would fix it, and will hold this PR until that's merged (or until I run out of patience and just suppress the warning).

Bump Rust to 1.50.0

---

po/it.po

- The feed list title format wasn't showing properly with Italian localization.
In 8880ba431012964d62c8d798191995e53a58a99f I introduced a bug in the format string used by the title removing a "?" from a conditional expression used to change the string when a filter is used.
I've fixed it by adding it in again and it's showing the correct format with tags, filter as well as the normal view.
- I also removed an `s` from the English plural not needed in Italian for that sentence.
I didn't notice this problem until recently using newsboat in an Arch based PC with a newer version than the 2.18 or something like that, in the Ubuntu repositories used by my main machine.
I've tested this building the last git version to verify it works properly.
I'll take a look at the other strings with …

Fixed Italian translation feed list title format.

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/libnewsboat/tests/configpaths_create_dirs_returns_false_if_xdg_config_dir_exists_but_data_dir_doesnt_and_couldnt_be_created.rs
rust/libnewsboat/tests/configpaths_create_dirs_returns_true_if_both_config_and_data_dirs_exist_now.rs
rust/libnewsboat/tests/configpaths_returns_paths_to_newsboat_xdg_dirs_if_they_exist_and_dotdir_doesnt.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_config_paths_were_specified_via_cli.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_empty_newsboat_xdg_config_dir_already_exists.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_empty_newsboat_xdg_data_dir_already_exists.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_newsboat_xdg_config_dir_couldnt_be_created.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_newsboat_xdg_data_dir_couldnt_be_created.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_does_not_migrate_if_urls_file_already_exists.rs
rust/libnewsboat/tests/configpaths_try_migrate_from_newsbeuter_migrates_default_newsbeuter_xdg_dirs_to_default_newsboat_xdg_dirs.rs
rust/libnewsboat/tests/locale_to_utf8_converts_text_from_the_locale_encoding_to_utf8.rs
rust/libnewsboat/tests/utf8_to_locale_converts_text_from_utf8_to_the_locale_encoding.rs
rust/libnewsboat/tests/utf8_to_locale_transliterates_characters_unsupported_by_the_locale_encoding.rs

This also reverts commit 3a816b208f2340232b40e7eef86d26b6b3affd74, which suppressed the warnings which section_testing 0.0.4 produced. section_testing 0.0.5 fixed the warnings, so suppression is no longer necessary.
Fixes #1480.
Nothing controversial here, so I'll merge once CI is green.

Bump section_testing to 0.0.5

---

config.h
po/it.po
src/keymap.cpp
src/pbview.cpp

This fixes issue #1471.
I'm not sure if it's the correct way to do it, I've just re-done was removed in this commit: 73399760f987d2cdc6636792bcef95629fd83272.
It looks like it works calling `_()` instead of making a new macro used at compile time as the [documentation for gettext](https://www.gnu.org/software/gettext/manual/html_node/Special-cases.html) says in cases like this.

Fix help strings that aren't localized

---

include/formaction.h
src/formaction.cpp

Fixes https://github.com/newsboat/newsboat/issues/1491.
Tested with config:
```
macro m set mark-as-read-on-hover!
macro a set feedlist-title-format "changed title"
macro b set feedlist-title-format&
```

Re-introduce toggle (!) and reset(&) options for `set` in macros

---

src/helpformaction.cpp

The main improvement is the unrolling of a complex loop.
I believe this makes it easier to understand the function.
The changes have been split into several commits.
If useful, I'm completely fine with squashing those commits together.

Simplify formatting in HelpFormAction

---

newsboat.cpp
podboat.cpp

By default, gettext converts messages to current locale charset. This doesn't sit well with Newsboat's default of UTF-8 for all internal strings. I don't remember any bugs that got tracked down to this, but it's better to fix it anyway.
I'm surprised this didn't manifest in bugs yet, so I'm going to dogfood on this for a week and see if I spot any problems. **If your locale is not en_US.UTF-8, please build this branch and see if anything breaks!**

Ask gettext to return UTF-8

---

.github/workflows/coveralls.yaml

This fixes SIGSEGVs in the C++ test suite. I'll investigate separately why newer Nightlies break the tests.

Coveralls: pin Rust to 2021-03-04

---

src/view.cpp

Fixes https://github.com/newsboat/newsboat/issues/563.

Use maximum value for Stfl::run() timeout

---

src/htmlrenderer.cpp
test/htmlrenderer.cpp

It may be a distant edge case for `xpp.get_attribute_value("src")` to return the empty string, but because (1) we're using it as a proxy for "attribute not found" (if that method throws `std::invalid_argument`) _and_ (2) we're already guarding against things like `<video><source><source></video>`, I figured it would be good to guard against as well.
Then, if all calls to `add_media_link` must now be wrapped in a conditional to ensure the source URL is not the empty string before incrementing the appropriate counter, the check inside the function becomes redundant.
Also adds comments to explain the use of the counters and boolean flags for media elements.

HtmlRenderer: don't increment counters if src attribute is empty string

---

src/htmlrenderer.cpp
test/htmlrenderer.cpp

Fixes #1505.
`alt` is preferable to `title` since [it is specific to `<img>` and its semantics are directly related to rendering](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt), while [the latter is not and has semantics that depend on the element](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title).

Display alt attribute of <img> in article view

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/regex-rs/Cargo.toml

This is to pull in a fix for a memory safety problem which never caused us any grief, but is a problem nonetheless: https://github.com/Koka/gettext-rs/issues/34
I also simplified Cargo.toml a bit: instead of toggling `gettext-system` feature directly on gettext-sys crate, I do it through the same feature in the gettext-rs crate. This rids us of direct dependency on gettext-sys, which is inconsequential but aesthetically pleasing :)
I think Dependabot didn't do this for us because gettext-rs 0.6.0 is incompatible with gettext-sys 0.19.9 that we required, and gettext-sys 0.21.0 is not compatible with gettext-rs 0.5.0 that we require. Those two crates have to be updated simultaneously. But I'm not sure that this is what tripped Dependabot up.

Bump gettext-rs to 0.6.0

---

Makefile
po/ca.po
po/de.po
po/es.po
po/fr.po
po/hu.po
po/it.po
po/ja.po
po/nb.po
po/newsboat.pot
po/nl.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sk.po
po/sv.po
po/tr.po
po/uk.po
po/zh.po
po/zh_TW.po

Help messages are now wrapped in a new macro, `translatable()`, but I forgot to update the Makefile to account for that. See https://github.com/newsboat/newsboat/pull/1489
Issue spotted by @bitigchi: https://github.com/newsboat/newsboat/pull/1519#issuecomment-794357520

Bring back help messages into POT file

---

.github/workflows/coveralls.yaml

This works around https://github.com/rust-lang/rust/issues/76085.

Coveralls: compile with Clang 12 and latest Nightly

---

rust/libnewsboat/src/filterparser.rs
rust/libnewsboat/src/matcher.rs

This repeats the approach that our C++ filterparser takes: we store *both* the string literal and the compiled regular expression. A slight difference is that Rust can also store the error; if the expression is invalid, C++ would try to re-compile it on each match, while Rust will just produce the previously generated error. I think this is fine because Rust doesn't let anyone modify the literal, so we can be sure that the stored regex/error are always relevant to the literal.
I decided not to write any new tests because this is just an optimization. The results are still checked by the more general tests for `filterparser` and `matcher`.
This fixes #1441.
Reviews are welcome! I'll merge in three days.

Rust filterparser: compile regex only once

---

.cirrus.yml

This macro prints even in the release mode, so we should avoid it. For now, the check is not very constrained: it examines all files, not just the Rust code, and the simplistic regex can be triggered even by a comment. OTOH I'm pretty sure this check *can't* miss a legitimate dbg! call, so I prefer not to make it any more complicated at this time.
This fulfils the promise I made in https://github.com/newsboat/newsboat/pull/1533#discussion_r595640939.
The CI is not supposed to pass right now, because we do have a `dbg!` call in the filterparser. But once #1533 is merged, I'll rebase and then CI should pass (and I can merge this).

CI: check for dbg! macro

---

rust/libnewsboat/src/utils.rs

Makes the code shorter and avoids the smelly bare unwrap.

Use unwrap_or instead of is_err/unwrap in utils::to_u

---

src/itemlistformaction.cpp

Fixes https://github.com/newsboat/newsboat/issues/1364.

mark-feed-read: Only mark visible items as read

---

.cirrus.yml
Cargo.lock
rust/libnewsboat-ffi/Cargo.toml
rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat-ffi/src/fslock.rs
rust/libnewsboat-ffi/src/scopemeasure.rs
rust/libnewsboat-ffi/src/utils.rs
src/scopemeasure.cpp
src/utils.cpp

The only problem was a new restriction (which should be lifted in the
future): cxx only lets us share types that are defined in the current
crate. As a result, our libnewsboat-ffi crate can't share types from the
libnewsboat crate. To work around that, we wrap the type into
a single-field struct. This makes the bindings a bit more wordy, since
we have to access the field, but it's not too bad.
Fixes #1542.
Reviews are welcome! I will merge this in three days.

Bump cxx to 1.0

---

src/feedhqapi.cpp
src/oldreaderapi.cpp

%2F is percent-encoded space, but when passed into snprintf, it's interpreted as a floating-point field. As a result, the program's version is formatted as a floating point. To avoid that, we escape the percent sign: %%2F.
This bug was found while reviewing FreshRSS integration: https://github.com/newsboat/newsboat/pull/1559#discussion_r605192829
I don't expect any reviews on this, so I'll auto-merge once the CI pass. But if you have thoughts of where similar bugs might lurk, let's hear them!

Correctly escape %2F in remote APIs

---

doc/internal/code-style.markdown
rust/libnewsboat/src/fmtstrformatter/mod.rs
rust/libnewsboat/src/logger.rs
rust/libnewsboat/src/utils.rs
test/utils.cpp

For the rationale, please see e4f99a6ed4ca90dccf7c47aae1d436a5bdb9ad7e. If that doesn't convince you, leave a comment below :)
Some numbers:
```
$ git checkout --quiet d9580c8cf97d276e74ed6c1c805f368f83d469d2 \
&& cargo test --no-run \
&& sync \
&& TMPDIR=/dev/shm hyperfine --warmup 5 --min-runs 20 --command-name 'Prior to these changes' 'cargo test' \
&& git checkout --quiet e4f99a6ed4ca90dccf7c47aae1d436a5bdb9ad7e \
&& cargo test --no-run \
&& sync \
&& TMPDIR=/dev/shm hyperfine --warmup 5 --min-runs 20 --command-name 'After these changes' 'cargo test'
Compiling libnewsboat v2.23.0 (/home/minoru/src/newsboat/rust/libnewsboat)
Compiling libnewsboat-ffi v2.23.0 (/home/minoru/src/newsboat/rust/libnewsboat-ffi)
Finished test [unoptimized + debuginfo] target(s) in 4.88s
Benchmark #1: Prior …
```

Speed up Rust tests by turning doctests into unit tests

---

doc/docker.md

Using the [current docker-based build doc](https://github.com/newsboat/newsboat/blob/master/doc/docker.md), i.e. with `ubuntu_18.04-build-tools.dockerfile`, I get:
```
src/view.cpp:7:10: fatal error: curses.h: No such file or directory
#include <curses.h>
^~~~~~~~~~
compilation terminated.
```
So I tried with the newer `ubuntu_20.10-build-tools.dockerfile`, and it works better:
```sh
docker build --tag=newsboat-build-tools --file=docker/ubuntu_20.10-build-tools.dockerfile docker
docker run --rm --mount type=bind,source=$(pwd),target=/home/builder/src --user $(id -u):$(id -g) newsboat-build-tools make -j
docker run --rm -it --mount type=bind,source=$(pwd),target=/home/builder/src newsboat-build-tools ./newsboat
```

Use newer dockerfile for build

---

Makefile

Fixes https://github.com/newsboat/newsboat/issues/1582

test/test: Only link against object files of existing .cpp files

---

include/itemrenderer.h
src/itemrenderer.cpp
test/itemrenderer.cpp

Fixes https://github.com/newsboat/newsboat/issues/1010 and fixes https://github.com/newsboat/newsboat/issues/1022:
- Tested with https://dennisschagt.nl/tmp/1010-feed/feed.atom (based on archive in https://github.com/newsboat/newsboat/issues/1010#issuecomment-646866506. Removed the `<summary>` tags so the filter script from https://github.com/newsboat/newsboat/issues/1010#issuecomment-646871561 is no longer needed).
Fixes https://github.com/newsboat/newsboat/issues/468 (taken from https://github.com/newsboat/newsboat/issues/468#issuecomment-787450424):
- Tested with https://dennisschagt.nl/tmp/newsboat-issue-468.xml
I also successfully tested this plaintext rendering with some Youtube atom feeds, e.g.:
- https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q
- …

Use simple plaintext renderer if mime-type is "text/plain"

---

include/itemrenderer.h
src/itemrenderer.cpp
test/itemrenderer.cpp

Fixes https://github.com/newsboat/newsboat/issues/1590
While looking into that issue, I noticed that `<` is not escaped for STFL when rendering using `render_plaintext()`.

Render as HTML by default

---

README.md

Lars Wirzenius offers to review FOSS READMEs[1], so I submitted ours.
This commit addresses most of the feedback.
> A slight concern is that it doesn't explain, or link to an
> explanation, what "an RSS/Atom feed reader" is or what it's for.
> Perhaps adding words to the effect that it's good for following blogs
> and news sites? And link to
> https://en.wikipedia.org/wiki/News_aggregator for more information?
Done, although I expect my explanation of a "feed reader" can be
improved.
> A carefully arranged screenshot of a terminal with the software
> running would add some punch and give an indication of what the
> software is like.
Done. I also took an opportunity to replace the screenshot on our
website, as it was getting dated.
> I find the logo credit and licensing at the top to be …

Address part of liw's feedback on the README

---

test/itemrenderer.cpp
test/queuemanager.cpp
test/rssfeed.cpp
test/rssitem.cpp
test/rsspp_rssparser.cpp
test/test-helpers/envvar.cpp
test/test-helpers/envvar.h
test/utils.cpp

We have a test helper, `EnvVar`, which lets us automatically restore the state of the environment at the end of the test (even if the test failed). Some variables, like TZ and LC_CTYPE, require running some C function after updating it. I noticed that not all users of TZ did that. This didn't result in any bugs, but it's worrisome still.
This PR adds sub-classes of `EnvVar` that bundle the handler. The `EnvVar` constructor is updated to discourage people from using the bare `EnvVar` where a specialized version is more appropriate.
There are some more repetitive code in tests that try to set the locale, but I don't see an easy way to simplify that. Please see the commit message of https://github.com/newsboat/newsboat/commit/6bec3174c5af24fbd9dfdad3528cc94bd16e0eda for my thoughts on that. …

Simplify working with TZ and LC_CTYPE env vars in tests

---

src/tagsouppullparser.cpp
test/tagsouppullparser.cpp

This allows stack protector to work on them, fixing #1598.
(There's a curious `switch` statement in the code. I filed #1602 about it.)
Reviews are welcome! Will merge in three days.

Get rid of variable-length arrays in TagSoupPullParser

---

.cirrus.yml

Adding this to avoid regressions on #1598.
Should've done this in #1601 :) Oh well.
It's a trivial change, so will merge once the CI is done.

CI: warn about functions unprotected from stack smashing

---

doc/configcommands.dsv
mk/mk.deps
src/configcontainer.cpp
src/view.cpp
test/view.cpp

This setting allows toggling the default behavior of normalizing article names when saving to disk.
When set to `no`, Newsboat will use the name of the article as it is without making any modifications, except adding the `.txt` extension. Defaults to `yes`.
Fixes #1110.

Introduce `restrict-filename` setting

---

Makefile
mk/mk.deps

In https://github.com/newsboat/newsboat/pull/1625, the contributor ran
`make depslist` locally, but didn't pass CI because the order of entries
was different from what CI expected. This commit makes the order
independent of the locale, which should avoid similar trouble in the
future.
I'll merge this once CI is done.

Make depslist locale-independent

---

src/view.cpp

Fixes https://github.com/newsboat/newsboat/issues/1463 by skipping a redraw when returning from an `EmptyFormAction`.
Before https://github.com/newsboat/newsboat/pull/1259, those lines weren't hit when opening a browser because the local `f` variable would be a `nullptr`.

Don't redraw screen when returning from temporary EmptyFormAction

---

CHANGELOG.md
rust/libnewsboat/src/utils.rs
test/utils.cpp

A recently published a new post in Newsboat's Atom feed, and since
I write the feed by hand, I accidentally put a space inside the <a>
tag's `href` property:
<a href=" https://newsboat.org/...">hey</a>
@der-lyse reported that Newsboat 2.13 rendered this space, but
I couldn't see it in 2.23. Turns out we accidentally fixed this in 2.14
when we started handling URLs using Rust's `url` crate instead of
calling into libxml2.

Changelog: note that 2.14+ removes whitespace around URLs

---

doc/newsboat.asciidoc

We had a user on IRC who read the macro docs and missed the fact that
one has to press a comma to invoke the macro. I rewrote that section to
mention the comma in *multiple* places, and also structure it such that
the user is more likely to actually read the text :)
Will merge in three days if there are no objections, or right after Lyse's review.

Doc: explain macro invocation more prominently

---

po/de.po

I not only added the missing translations, but also unified the remaining German typographic quotes (`„` and `“`) everywhere. I think I now caught all of them and there is no other quoting variant left. I searched for `` ` ``, `'`, `´` and `"`, but only the first two were present.

Update German translations

---

newsboat.cpp
podboat.cpp

Related to https://github.com/newsboat/newsboat/issues/1665.
Changes output on unhandled exception to:
Original output:

Reset STFL in top-level exception handlers to print in normal mode

---

rust/libnewsboat/src/utils.rs

OpenBSD's libc doesn't have iconv support. Link with GNU libiconv
instead as is done for FreeBSD.

Fix iconv linking on OpenBSD.

---

src/feedlistformaction.cpp
src/itemlistformaction.cpp
src/rssfeed.cpp

When working on the German translations for the upcoming release of Newsboat 2.24, I noticed a small imperfection regarding filters.
Previously, there had been two terms for the very same thing. The much more common "filter expression" and also a rarely used "filter command". Since the "filter expression" is not only used more often, but also sounds technically more correct, let's go with this everywhere.
Another difference was the presence or lack of details. Some places already displayed both the invalid filter as well as the exact problem, others did not. I don't see a point in hiding those details from the user in these cases, so let's always behave the same and show all the details we have.
Unfortunately, there's one potential thing left, which I won't address here. There are still …

Harmonize filter expression error messages

---

mk/mk.deps
src/reloader.cpp
src/view.cpp

Fixes #1665.
This can't be merged right now because it introduces a new translatable string. However, @dennisschagt provided a good stopgap solution in #1666, so it's not a very big deal. I'll merge after the 2.24 release.

Do not exit when preparing invalid query feed

---

src/pbview.cpp

This makes the behaviour consistent with Newsboat, where similar commands (delete, toggle-read, etc.) also move to the next item.

Move to next item after marking item as finished/deleted

---

include/fmtstrformatter.h
mk/mk.deps
rust/libnewsboat-ffi/build.rs
rust/libnewsboat-ffi/src/fmtstrformatter.rs
rust/libnewsboat-ffi/src/history.rs
src/fmtstrformatter.cpp
src/history.cpp

Related issue: https://github.com/newsboat/newsboat/issues/1383
If preferred, feel free to postpone merging until after the r2.24 release.

Use cxx for FmtStrFormatter C++/rust bindings

---

include/pbcontroller.h
include/pbview.h
src/pbcontroller.cpp
src/pbview.cpp

Fixes https://github.com/newsboat/newsboat/issues/1375
https://github.com/newsboat/newsboat/commit/edf1949750db681323ec68393d1eb713ce4d4d83 contains the fix. The other commits only contain some readability improvements.

Podboat: Resolve performance regression (slow scrolling through downloads)

---

src/itemlistformaction.cpp

516392755439d84e3cf9531b44220b03eefa5759 (PR #1558) changed
mark-all-read to mark each item individually. That made mark-all-read
aware of the filters, but also made it slower. This was especially
noticeable with remote APIs, where mark-read latency is high.
We can't speed it up in the general case, but when there is no filter,
we can fall back onto the faster mark_all_read() method which marks the
entire feed in one go. I tested that this new code is indeed faster and
doesn't re-introduce #1364.
Reported by Oneiric on IRC.
Reviews are welcome! I'll merge this in three days.

Fix perf regression in mark-all-read with remote APIs

---

.cirrus.yml
.github/workflows/coveralls.yaml

This is a little step towards #1660. The heaviest jobs — the ones that compile things — are still not skipped, because Cirrus doesn't have a good function for this. [I asked for it to be added](https://github.com/cirruslabs/cirrus-ci-docs/issues/873); but even if it never happens, I can work around by writing a slightly less elegant configuration.
Reviews welcome! I'll merge in three days.

Skip some CI tasks if no relevant files changed

---

.github/workflows/coveralls.yaml

This rolls back a part of 8722d689955a859d6b7a81b7369b3f81fcd4cedf. The
problem is that `on.push.paths-ignore` doesn't just skip the job, it
doesn't even start it (that's a documented behaviour, nothing wrong
here). This doesn't play well with the fact that Coveralls job is
required, i.e. a PR can't be merged without it.
The default `job.<name>.if` mechanism would let us skip the job
properly, but it doesn't provide a ready-made way to check which paths
changed. Third-party actions don't seem to cover this either.
I ran out of interest looking into this, so I'm just rolling back the
changes. Perhaps I'll revisit this later.

Do not skip Coveralls job, ever

---

src/utils.cpp

I've recently again been bitten by the poor error-reporting, especially by the `ttrss_api`-backend in the case of curl-errors. As the backend uses `utils::retrieve_url` to do all the heavy lifitng, this is probably the place to start.
The current implementation did disregard the return value of `curl_easy_perform` and simply returned the value of `buf` in all cases. However, the value of `buf` is not really well defined in the case of transmission errors (might be a partial response, ...).
This commit therefore checks the returned `CURLcode` for errors, and further produces a meaningful error message to the log to aid debugging. The latter comes with a caveat so: To produce the errormessage, we have to clobber the value of `CURLOPT_ERRORBUFFER`, even for cached handles.
I'm not 100% …

utils::retrieve_url: Improve error reporting of curl_easy_perform

---

.cirrus.yml

Greedy containers can use more CPU than they originally requested:
https://medium.com/cirruslabs/introducing-greedy-container-instances-29aad06dc2b4
We used to request 2 CPUs and 4GB RAM, and ran 3 compilations in
parallel. Graphs show that we never use more than 2GB though, so this
commit ups the number of jobs to 6. Now, our builds should be able to
run up to 2 times faster, while never hitting OOM.
These changes do not affect FreeBSD nor macOS, and also containers where
we run single-thread stuff like asciidoctor or i18nspector.
I'll merge this once the CI turns green.

Cirrus CI: use greedy containers for compilation

---

rust/libnewsboat/src/cliargsparser.rs
test/cliargsparser.cpp

Add tests for:
- combined short options (e.g. `-vc /path/to/cache.db`)
- combined arguments and options (e.g. `-c/path/to/cache.db`)
- short options with `=` (e.g. `-c=/path/to/cache.db`)
See: https://github.com/newsboat/newsboat/issues/1549#issuecomment-882107413

cliargsparser.{cpp,rs}: add more tests for options

---

rust/libnewsboat/src/filterparser.rs
rust/libnewsboat/src/fslock.rs
src/controller.cpp
src/pbcontroller.cpp

I'm high time I fulfilled [a promise I made two weeks ago](https://github.com/newsboat/newsboat/pull/1697#issuecomment-875920449) and fixed this.
In C, it's ergonomic to write code like this:
printf(gettext("foo" PRId32 "bar"), 42);
gettext (both the function and the tool) have support for this idiom:
the message is extracted as "foo<PRId32>bar", and the .mo files seem to
store it in annotated form as well.
Rust has no PRI* constants, and string literals are concatenated via the
`concat` macro. As a result, `xtr` (Rust's replacement for `xgettext`)
doesn't support this pattern at all.
To reconcile those differences, this commit replaces all uses of PRI*
inside gettext with code like this:
prinln!(gettext("foo%sbar"), &42.to_string())
This is done even on the C++ side, to avoid mistakes …

Do not use PRI* in calls to gettext

---

doc/chapter-firststeps.asciidoc

Not sure whether we should emphasize this hazard more. I hesitated, because it's in the introduction and I don't want to scare people away. In the future we're probably better off to spend dedicated subsections on both configuration files at section "3.4 Files".
My wording might be off today, I'm happy for suggestions. @zounp would this have helped you?

Document comments in urls file

---

src/feedlistformaction.cpp

Fixes #1734. Reviews are welcome! I'll merge in three days.

Fix out-of-bounds access with `next-unread` in an empty feedlist

---

include/controller.h
include/curlhandle.h
mk/mk.deps
src/feedhqapi.cpp
src/freshrssapi.cpp
src/inoreaderapi.cpp
src/ocnewsapi.cpp
src/oldreaderapi.cpp
src/poddlthread.cpp
src/rssparser.cpp

I tried to replace all pairs of `curl_easy_init`+`curl_easy_cleanup` with a usage of `CurlHandle` (mostly for consistency).
There are still a few places where `curl_easy_init`+`curl_easy_cleanup`  are used directly.
I would prefer to get rid of those as well, but I'm not sure how.
<details>
<summary>Remaining occurrences</summary>
https://github.com/newsboat/newsboat/blob/3311426cdbd1eb48ed4a15d22d348765659e1794/rss/parser.cpp#L115-L219
https://github.com/newsboat/newsboat/blob/3311426cdbd1eb48ed4a15d22d348765659e1794/src/freshrssapi.cpp#L413-L432
https://github.com/newsboat/newsboat/blob/3311426cdbd1eb48ed4a15d22d348765659e1794/src/minifluxapi.cpp#L217-L240
https://github.com/newsboat/newsboat/blob/3311426cdbd1eb48ed4a15d22d348765659e1794/src/utils.cpp#L324-L395
</details>
While making …

Use CurlHandle as much as possible

---

src/tagsouppullparser.cpp

Adding terminating '\0' to the mbc results in a crash when pos == MB_LEN_MAX,
which is true for 4-byte characters and musl.
This is an attempt to fix it.

Fix write outside of bounds in TagSoupPullParser::decode_entity

---

doc/chapter-podcasts.asciidoc
doc/newsboat.asciidoc

This is inspired by https://github.com/newsboat/newsboat/issues/252#issuecomment-903343014.
The `warning-caption` thing adds a large emoji next to the warning.
Without this, Asciidoctor would use the text "WARNING" instead, which
doesn't look as eye-catching as an emoji. The recipe for this is taken
from [1] and [2]. The icon used is U+26A0 WARNING SIGN.
1. https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/#using-emoji-for-admonition-icons
2. https://github.com/asciidoctor/asciidoctor.org/issues/571
Reviews are welcome! I'll merge this once @der-lyse have taken a look and there are no unaddressed review comments.

Docs: mention that Inoreader API omits enclosures

---

contrib/exportOPMLWithTags.py

https://github.com/newsboat/newsboat/issues/1770
According to the [test file](https://github.com/newsboat/newsboat/blob/master/test/data/test-urls.txt), the urls can contain comments.
This minor addition can let this export script handle it properly.
I tested on my local urls file, and it works great.
_Python will stop eval once it finds a true from left to right  in `or`, thus the line[0] will always be valid._

Simple fix to let exportOPMLWithTags.py handle comments

---

doc/configcommands.dsv
src/configcontainer.cpp
src/feedlistformaction.cpp
src/itemlistformaction.cpp

This adds in a `confirm-mark-feed-read` using code from `confirm-mark-all-feeds-read`
Fixes: #1781

Add in `confirm-mark-feed-read` configuration variable

---

src/view.cpp

Fixes https://github.com/newsboat/newsboat/issues/117

Modal dialogs: Don't allow changing to other open dialogs

---

Makefile

This is akin to b5ef45a3de2edd00457ade414f8c512a7e644f2f: `sort` is
controlled by the locale, so we have to set the locale to something
portable to make sure that `sort` produces the same result on all
machines.
Fixes #1790.

Sort configcommands reproducibly

---

Makefile
include/cliargsparser.h
include/configpaths.h
include/fmtstrformatter.h
include/fslock.h
include/history.h
include/logger.h
include/scopemeasure.h
include/utils.h
mk/mk.deps
rust/libnewsboat-ffi/build.rs
rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat-ffi/src/configpaths.rs
src/cliargsparser.cpp
src/configpaths.cpp
src/keymap.cpp

Related to https://github.com/newsboat/newsboat/issues/1383
I had some trouble passing the `CliArgsParser` as an argument to `ConfigPaths::process_args()`.
It looks like types in `extern "Rust"` scopes cannot be shared (maybe it is possible, but I couldn't find out how).
I worked around it by introducing `FfiCliArgsParser` and casting on the C++ side.

Use CXX for ConfigPaths FFI

---

doc/newsboat.asciidoc

This addresses a question a user asked on IRC. We should do this for all
features, really. I looked through the rest of remote services we
support, and none of them are in our CHANGELOG, so I assume they were
added in Newsbeuter; thus, they were always in Newsboat.

Doc: note that FreshRSS requires Newsboat 2.24+

---

doc/configcommands.dsv
src/configcontainer.cpp
src/minifluxapi.cpp

For issue: https://github.com/newsboat/newsboat/issues/1814
Tested on fedora 35 and all seems fine.
Default value set as 100 to keep with current behaviour

Add Miniflux support for min-items

---

doc/newsboat.asciidoc

Miniflux when using `get_entries` don't return enclosures: https://github.com/miniflux/v2/issues/1059
So adding information similar to this PR: https://github.com/newsboat/newsboat/pull/1760

Add information about missing enclosures in miniflux API

---

doc/newsboat.asciidoc
include/rssignores.h
mk/mk.deps
src/rssignores.cpp
test/rssignores.cpp

for #1913,
adds regex matching for ignore-article if and only if the pattern is prefixed with 'regex:', otherwise the previous behaviour is used.

Allow regexes to select URLs in ignore-article

---

contrib/colorschemes/universal-color

As described in the file:
```
```
By default, some of the text is hard for me to read, because my colorscheme uses a darker color for yellow

Add "universal" colorscheme

---

src/controller.cpp

Before:
```
$ ./newsboat --import-from-opml sample-opml.xml 
Error importing OPML to urls file /home/bogdasar/.newsboat/urls: Не удалось открыть файл: Нет такого файла или каталога (os error 2)
$ echo $?
0
```
what is wrong, because 0 means successful exit.
After:
```
$ ./newsboat --import-from-opml sample-opml.xml 
Error importing OPML to urls file /home/bogdasar/.newsboat/urls: Не удалось открыть файл: Нет такого файла или каталога (os error 2)
$ echo $?
1
```

Return right exit code when importing OPML

---

contrib/kitty-img-pager.sh

This adds a custom pager to show images within the terminal emulator Kitty. I use it every day, so I thought it might also be interesting for others.
Usage instructions are included in the script. Requires the kitty terminal emulator.

Add community pager to show images with kitty

---

src/htmlrenderer.cpp
test/htmlrenderer.cpp

Fixes https://github.com/newsboat/newsboat/issues/1974

Guard against popping item from empty vector (list_elements_stack)

---

doc/manpage-newsboat.asciidoc
doc/manpage-podboat.asciidoc

I'm currently working a bit on the man pages and trying to make them a bit more readable. This is the first change, that is only minor but probably not controversial. On the other hand, some other experiment I have in mind might not end up being integrated. So I decided go go with small increments.
In most other man pages, that I looked at, the program options are formatted bold and their values are underlined. So let's do this, too, to provide an overall consistent look.
Also for newsboat's `-x` option in the synopsis the angle brackets around the `command` were removed to make it consistent to all the other options. The space in front of the ellipsis was removed because in the options section there was also no leading space. This also seems to be the common style in most other man …

Make command line options bold/underline in man pages

---

Makefile
doc/man.rb

This is the promised second change in the man pages. The documentation in the ruby file says it all.
Don't be confused, I configured my `urxvt` to show underline in blue text coloe. So here's a before (top) and after (bottom):
Yes, it's a bit sad, that if something contains spaces (see the `<config-command> …` in the middle of the pages) the spaces themselves are not underlined. But the result is still better in my opinion. Maybe something for the future.

Make inline code underlined in man pages

---

Cargo.lock

Bump regex crate to address RUSTSEC-2022-0013

---

.cirrus.yml

1. Bump 12.2 to 12.3, as 12.2 reached EOL on March 31, 2022[1]
2. Remove 11.4, as it reached EOL on September 30, 2021[1]
1. https://www.freebsd.org/security/unsupported/

CI: update FreeBSD

---

doc/chapter-tagging.asciidoc
doc/newsboat.asciidoc

knibbel on IRC pointed out that the example from the docs doesn't work. Turns out that in #1916 I updated the example without testing it. This commit fixes the example and adds notes about # operator not working with tags that contain spaces. The bug itself is tracked in #2039.
Reviews welcome! I'll merge this in three days, unless there is an ongoing discussion.

Document that # and !# don't work for tags with spaces

---

src/itemlistformaction.cpp

Without this include, newsboat does not build on my current Fedora machine (missing `strcasestr` function definition).

include cstring in itemlisformaction

---

src/feedhqapi.cpp
src/freshrssapi.cpp
src/inoreaderapi.cpp
src/newsblurapi.cpp
src/ocnewsapi.cpp
src/oldreaderapi.cpp

Fixes #2102, and prevents the same problem from happening to other APIs. Even if those other APIs never return `null`, it's better to be safe than sorry.
Since this is a fix for a segfault, I intend to merge this *before* the 2.28 release. Thus, reviews are especially welcome. @dennisschagt?

Check for `NULL` before calling `json_object_get_string()`

---

3rd-party/expected.hpp

(Yes, this only changes the version number; see https://github.com/martinmoene/expected-lite/releases/tag/v0.6.1)

Update expected-lite to 0.6.1

---

src/listwidget.cpp

Fixes https://github.com/newsboat/newsboat/issues/2138
The position in the list was updated from the `FeedListFormAction::set_pos()` function, to keep the same item selected (if it existed after filtering).
It looks like the ListWidget's scroll_offset was not updated if the newly selected position was already in view.
Tested manually with different values for `scrolloff` (0, 1, 3).
I don't think an automatic test is possible, given that `max_offset` depends on the window height, which is dependent on the terminal in which the tests run.

ListWidget: Let update_scroll_offset force offset lower than max_offset

---

doc/chapter-cmdline.asciidoc
doc/chapter-configuration.asciidoc
doc/chapter-firststeps.asciidoc
doc/chapter-password.asciidoc
doc/chapter-podboat.asciidoc
doc/chapter-tagging.asciidoc
doc/createAvailableOperationsListView.awk
doc/keycmds.dsv
doc/newsboat.asciidoc

Resolves https://github.com/newsboat/newsboat/issues/2028
I had to add the `experimental` attribute to use the `kbd` macro.
From [the Asciidoctor documentation](https://docs.asciidoctor.org/asciidoc/latest/macros/keyboard-macro/):

Use Asciidoctor's `kbd` macro to style keypresses in documentation

---

include/listwidget.h
src/listwidget.cpp

This implements a suggestion I made in https://github.com/newsboat/newsboat/pull/2153#pullrequestreview-1071992907.

Prevent ListWidget::set_scroll_offset to scroll too far

---

rust/libnewsboat/src/filterparser.rs

Relevant Clippy documentation:
https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
Probably resolves the build issues of the following open PRs:
- https://github.com/newsboat/newsboat/pull/2169
- https://github.com/newsboat/newsboat/pull/2168
- https://github.com/newsboat/newsboat/pull/2167

Let Operator derive Eq to resolve clippy warning

---

include/regexowner.h
rss/xmlutilities.cpp
src/matcherexception.cpp
src/regexowner.cpp

Cppcheck 2.9 produced some new warnings, here are the fixes. None of them are useful by themselves, but fixing them means I get a clean(-ish) cppcheck report now, so it'd be easy to notice new warnings.
I don't think any of this is controversial, so I'll auto-merge. Comments are welcome regardless!

FIx some cppcheck warnings

---

include/utils.h
rss/parser.cpp
rust/libnewsboat-ffi/src/utils.rs
src/cache.cpp
src/utils.cpp
test/utils.cpp

Fixes https://github.com/newsboat/newsboat/issues/1436
These changes might be useful for `utils::retrieve_url()` as well, but I rather find a way to merge/deduplicate the implementations of `utils::retrieve_url()` and `Parser::parse_url()` at some point (not in this PR).

Convert feed data if charset specifies encoding different from utf-8

---

rss/atomparser.cpp
rss/item.h
rss/medianamespace.cpp
rss/rss09xparser.cpp
src/freshrssapi.cpp
src/ocnewsapi.cpp
src/rssparser.cpp
src/ttrssapi.cpp

Resolves https://github.com/newsboat/newsboat/issues/2050
This implements @Minoru's idea from https://github.com/newsboat/newsboat/issues/2050#issuecomment-1114181986:
> So Newsboat is technically correct, but I still think it could do better :) Current algorithm is to pick the last enclosure of the supported type. I guess it could be changed to pick the last enclosure (regardless of the type) if the existing algorithm hasn't picked anything.

Accept enclosure with invalid type if no valid enclosure is found

---

doc/chapter-configuration.asciidoc
src/configparser.cpp
test/configparser.cpp
test/data/config-multi-line

Concatenates lines separated by a '\\' in config file.
Ignores whitespaces after '\\', if non white space characters are found (or no '\' is found) it joins the line as the last line of the multi-line and hands off parsing logic as usual to ConfigParser::parse_line.

Allow splitting a config command into multiple lines

---

docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_22.04-build-tools.dockerfile
rust/libnewsboat/build.rs
rust/libnewsboat/src/fslock.rs
rust/libnewsboat/src/matcher.rs
rust/libnewsboat/src/utils.rs
rust/libnewsboat/tests/configpaths_helpers/mod.rs
rust/libnewsboat/tests/getcwd_returns_an_error_if_current_directory_doesnt_exist.rs
rust/libnewsboat/tests/getcwd_value_depends_on_current_directory.rs

Also fix all the Clippy warning that popped up in the new release.

CI: Bump Rust to 1.65.0

---

rss/parser.cpp
rust/libnewsboat/src/utils.rs
src/utils.cpp
test/utils.cpp

Fixes https://github.com/newsboat/newsboat/issues/1437
Verified using [response.txt](https://github.com/newsboat/newsboat/files/9944745/response.txt) and urls file:
```
filter:cat:http://localhost:8000
```
while running `cat response.txt | nc -l -p 8000`
When reloading, this will result in a title with a lot of question marks, but at least Newsboat does not crash anymore.

Always convert downloaded text to utf-8, even if server says it is utf-8 already

---

doc/keycmds.dsv
include/keymap.h
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/keymap.cpp

This adds an operation to go to the currently selected article's feed. I find it useful in query feeds or searches.
First time contributing to newsboat, please let me know if I should make any modifications :)

Add article-feed operation

---

po/es.po

I use Newsboat with the Spanish localization, and I noticed when I ran `newsboat -v` I got the message:
> (Escribe `newsboat --vv' para ver el texto completo)
When I ran `newsboat --vv` it didn't work, but I noticed if I changed the command to `newsboat -vv` it worked correctly, so it was just a problem in the Spanish localization. I've fixed this in this PR

Fix incorrect command in Spanish localization

---

src/ocnewsapi.cpp

A fix for a small bug I noticed one day.
Using `string += number` treats the number as character value, which is clearly not intended.

Fix log formatting

---

rss/atomparser.cpp
rss/atomparser.h
test/data/atom10_2.xml
test/data/atom10_feed_authors.xml
test/rsspp_parser.cpp

This merge request only addresses the feed level author, but not the source element. As requested, I will create a separate MR for it. Hence, this one here just partially fixes #2256.
Three things to note upfront:
1. I'm not entirely sold on the method name `parse_and_update_author`. Maybe sb. comes up with something better.
2. Not sure if I should have created a new Atom feed for the test case or whether it's alright to reuse the already existing one.
3. Lastly, I don't consider myself an experienced C++ programmer, so please have a thorough look.

Use feed level author if entry does not have one

---

README.md
doc/newsboat.asciidoc

This would be the right syntax when using the `git` protocol.
Alternatively, we could have kept the existing url and changed the protocol to `https`, but I think probably `git` is the preferred (to force the use of SSH key).

Fix clone command

---

.cirrus.yml

Homebrew disabled libstfl formula[1], which means CI can no longer install it[2]. As a result, we can't build Newsboat on macOS right now.
This commit is a short-term fix to un-break our CI. The path to the real solution is tracked in #2280.
1. https://github.com/Homebrew/homebrew-core/blob/e29666f0788603a1c42fee6d9dd5db05e0f2d3d5/Formula/libstfl.rb#L17
2. https://github.com/newsboat/newsboat/runs/10020736154

CI: remove macOS

---

Cargo.lock
rust/libnewsboat/Cargo.toml

Disable transitive dependency on `time` crate

---

rss/atomparser.cpp
test/data/atom10_feed_authors.xml
test/rsspp_parser.cpp

This is the promised follow-up of #2259 from two weeks ago.
The Atom specification states in section 4.2.1 on 'The "atom:author" Element' (https://www.rfc-editor.org/rfc/rfc4287#section-4.2.1):
> If an atom:entry element does not contain atom:author elements, then
> the atom:author elements of the contained atom:source element are
> considered to apply. In an Atom Feed Document, the atom:author
> elements of the containing atom:feed element are considered to apply
> to the entry if there are no atom:author elements in the locations
> described above.
This commit addresses the source author part. The feed author was already implemented in 886c61005a96748107cfca2bdfe6492c221a3411.
Fixes #2256.
(Force-pushed to fix a code formatting violation regarding maximum line length detected by CI.)

Use source author if entry does not have author

---

include/listwidgetbackend.h
include/matcherexception.h

Upcoming `gcc-13` made `<string>` leaner and does not include `<cstdint>`
implicitly anymore. As a result build fails without the change as:
include/matcherexception.h:14:14: error: elaborated-type-specifier for a scoped enum must not use the «class» keyword [-Werror]
14 |         enum class Type : std::uint8_t { ATTRIB_UNAVAIL = 0, INVALID_REGEX = 1 };
|         ~~~~ ^~~~~
|              -----

add missing <cstdint> includes for gcc-13 compatibility

---

snap/snapcraft.yaml

Use personal-files interface in snap YAML file to grant R/W permissions on $HOME/.newsboat dir containing urls file.
refs:
-https://github.com/newsboat/newsboat/issues/1808 
-https://forum.snapcraft.io/t/the-personal-files-interface/9357

Fix #1808: allow reading urls file from user home in .newsboat dir

---

include/tagsouppullparser.h
test/configcontainer.cpp
test/fslock.cpp
test/keymap.cpp
test/matcher.cpp
test/queueloader.cpp
test/regexmanager.cpp
test/remoteapi.cpp
test/test_helpers/envvar.cpp
test/test_helpers/envvar.h

These were found with cppcheck 2.10. There were a bunch of false positives in Catch2 macros, but I didn't find energy to figure out how to suppress them.
The only important commit here is 0c7bddfb206dbde217d6bb4d00d8cd2d842e0407, because it fixes a potential problem. The rest are just readability and performance churn.

Fix cppcheck warnings

---

contrib/move_url.py

I'm subscribed to a Twitter (technically Nitter) RSS feed that retweets art and other tweets often. Whenever I want to hide retweets from certain accounts while keeping past retweets, I'd modify the feed URL to hide retweets from the accounts and manually modify the database, which is slightly cumbersome. I could use killfiles, but it would be nice to not have to receive the retweets in the first place.

Add contrib script for moving feed URLs in newsboat's database while keeping articles

---

.cirrus.yml

FreeBSD 12.3 in our CI is currently failing to update packages:
pkg update -f
Updating FreeBSD repository catalogue...
pkg: Repository FreeBSD has a wrong packagesite, need to re-create database
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries:
Newer FreeBSD version for package zziplib:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1204000
- running kernel: 1203000
Ignore the mismatch and continue? [y/N]: pkg: repository FreeBSD contains packages for wrong OS version: FreeBSD:12:amd64
Processing entries... done
Unable to update repository FreeBSD
Error updating repositories!
This is probably caused by 12.3 no longer being supported.
Fixed by upgrading to 12.4. I also upgraded 13.1 to 13.2 while I'm at it, even though 13.1 has two more …

CI: fix FreeBSD 12.3 job by upgrading to 12.4

---

src/rssparser.cpp

I would add a test case, but it doesn't seem like there's a file for src/rssparser.cpp. Oh well
Fixes #2434

Remove newlines from authors

---

contrib/image-pager/README.md
contrib/image-pager/bootstrap_image_pager.sh
contrib/image-pager/imagePager.scala

This adds an image pager that looks at all of the links asynchronously, finds which ones are images, and displays them using either feh or the kitty terminal in the same way as kitty-img-pager.sh.
Other than being able to display images using feh, this differs from kitty-img-pager.sh in the following ways:
- Can spot all images in a feed, for some reason I had trouble with kitty-img-pager.sh when trying to spot images such as thumbnails in Odysee and YouTube feeds.
- Can find multiple links in one line. (I don't know if kitty-img-pager.sh does that too or not, I can't tell)
Instructions on how to use it are in the README.md of the folder.

Add an image pager (using feh) to contrib

---

doc/faq.asciidoc
doc/manpage-newsboat.asciidoc
include/cliargsparser.h
include/controller.h
include/opml.h
include/rssfeed.h
newsboat.cpp
rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat/src/cliargsparser.rs
src/cliargsparser.cpp
src/controller.cpp
src/opml.cpp
src/rssfeed.cpp
test/opml.cpp
test/rssfeed.cpp

OPML, while primarily using a hierarchy of outlines, also supports tags in version 2.0 (http://opml.org/spec2.opml#1629042387000):
> category is a string of comma-separated slash-delimited category strings, in the format defined by the RSS 2.0 category element. To represent a "tag," the category string should contain no slashes. Examples: 1. category="/Boston/Weather". 2. category="/Harvard/Berkman,/Politics".
By exporting as OPML 2.0 we can include the tags in a way other programs understand. Commas are replaced with underscores. Slashes are left as-is, so when newsboat imports a hierarchical OPML file and then exports it again, that hierarchy isn't lost.
Fixes #871

Include tags in OPML feed export

---

.cirrus.yml
docker/ubuntu_23.04-build-tools.dockerfile

The new Dockerfile with Ubuntu 23.04 can't be used outside CI at the
moment because the `docker run ... --user $(id -u):$(id -g)` command
doesn't work with Ubuntu 23.04: Dockerfile attempts to create a user
with GID and UID that already exist. I want to concentrate on the new
release for now, so this issue will get addressed later (https://github.com/newsboat/newsboat/issues/2474).

CI: add new compilers

---

.cirrus.yml
CHANGELOG.md
Cargo.lock
README.md
doc/internal/howto-release.md
doc/newsboat.asciidoc
docker/code-formatting-tools.dockerfile

`regex` crate wasn't updated because it pulls in a new version of some dependency which not all of our other deps support. I don't wan't to compile some dependencies twice, so let's hold `regex` at an older version for now.

Prepare for next release

---

config.sh

Check for pkg-config existence to avoid issues like https://github.com/newsboat/newsboat/issues/2490

Show error if pkg-config (or configured `$PKG_CONFIG`) is not present

---

docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_22.04-build-tools.dockerfile
docker/ubuntu_23.04-build-tools.dockerfile
rust/libnewsboat/src/utils.rs

Also fix clippy::manual_next_back warning:
https://rust-lang.github.io/rust-clippy/master/index.html#manual_next_back

CI: bump Rust to 1.71.0

---

rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/utils.rs
rust/libnewsboat/tests/run_program_works_for_large_inputs.rs
test/utils.cpp

Previous implementation attempted to write the entire input to the program's stdin before reading anything from its stdout. With programs that work in a streaming fashion (such as `sed` and `cat`), this would deadlock on large inputs as the program is waiting to write to its stdout while Newsboat is waiting to write to program's stdin.
This affected `filter:` feeds, and could also affect bookmarks and rendering.
Fixed by moving the write into a separate thread as described in https://doc.rust-lang.org/std/process/index.html#handling-io Would be nice to do this in a single thread with non-blocking I/O, but `std::process::ChildStdout` doesn't seem to have a non-blocking `read`.
Reported by B-| on IRC (the `filter:` variant). Kudos to Dennis van der Schagt for the discussion and the …

Avoid deadlock in `utils::run_program` with large inputs

---

test/utils.cpp

Fixes an issue introduced in #2511. See the first commit message for all the details.

Prevent tests from (ocasionally) sigkilling themselves

---

.github/dependabot.yml

https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/
I did it for cxx and cxx-build because these are always updated in sync. Perhaps there are other groups we could define, but the cxx one is the most frequently updated, so let's start with that.

Dependabot: update cxx and cxx-build with a single PR

---

include/rssitem.h
rss/atomparser.cpp
rss/item.h
rss/medianamespace.cpp
rss/medianamespace.h
rss/rss09xparser.cpp
src/cache.cpp
src/freshrssapi.cpp
src/itemrenderer.cpp
src/ocnewsapi.cpp
src/rssitem.cpp
src/rssparser.cpp
src/ttrssapi.cpp
test/data/atom10_2.xml
test/data/rss20_2.xml
test/itemrenderer.cpp
test/rssparser.cpp
test/rsspp_parser.cpp

Resolves https://github.com/newsboat/newsboat/issues/2305 and resolves https://github.com/newsboat/newsboat/issues/2495
Side-by-side view of rendered output for old (left, before this PR) and new (right, with this PR):
My idea here is to show the enclosure's description if it is available, directly above the regular text.
This seems to work well for posts from Mastodon, e.g. from the feed for Minimus' posts: https://yt.artemislena.eu/feed/channel/UCXIJgqnII2ZOINSWNOGFThA
Other than that, I tried to change as little as possible.
Specifically, the enclosure description is still shown as content if no regular content element is available (just implemented in a different location).

Show image enclosure inline

---

src/cache.cpp

Looks like I forgot to update the database schema version in https://github.com/newsboat/newsboat/pull/2399.
This caused logging of "Critical" log messages:
```
[2023-08-27 14:38:35] INFO: Cache::populate_tables: DB schema version 2.22
[2023-08-27 14:38:35] INFO: Cache::populate_tables: applying DB schema patches for version 2.33
[2023-08-27 14:38:35] DEBUG: running query: UPDATE metadata SET db_schema_version_major = 2, db_schema_version_minor = 33;
[2023-08-27 14:38:35] DEBUG: running query: ALTER TABLE rss_item ADD COLUMN enclosure_description VARCHAR(1024) NOT NULL DEFAULT "";
[2023-08-27 14:38:35] CRITICAL: query "ALTER TABLE rss_item ADD COLUMN enclosure_description VARCHAR(1024) NOT NULL DEFAULT "";" failed: (1) SQL logic error
[2023-08-27 14:38:35] DEBUG: running query: ALTER …
```

Update database schema version to avoid repeated schema updates

---

rust/libnewsboat/src/utils.rs
src/rssparser.cpp
test/rssparser.cpp

Showing a numeric identifier as the title is not very useful, and it happens on Mastodon RSS feeds. Use the description instead.
Fixes #2530

Use description as title when URL ends with digits

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/logger.rs

Replaces https://github.com/newsboat/newsboat/pull/2542. Resolves deprecation warnings caused by chrono update.

Update chrono depency version to 0.4.30

---

include/links.h
src/htmlrenderer.cpp
src/itemrenderer.cpp
test/htmlrenderer.cpp
test/itemrenderer.cpp

Mainly moved code from `HtmlRenderer` to `Links` and `ItemRenderer`.
`ItemRenderer` already had some tests with rendered links.
Fixes https://github.com/newsboat/newsboat/issues/2541

Always render links if there are any

---

doc/faq.asciidoc

Previous wording implied that this limitation is only about the browser. The new wording re-iterates that Newsboat can't invoke *any* program except xdg-open.
Fixes #2117.
I'm asking for a review from Lyse because he previously reviewed our docs, but reviews from everyone else are welcome as well!

FAQ: clarify that only xdg-open can be run in Snap

---

include/dialogsformaction.h
include/dirbrowserformaction.h
include/emptyformaction.h
include/feedlistformaction.h
include/filebrowserformaction.h
include/formaction.h
include/helpformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
include/listformaction.h
include/searchresultslistformaction.h
include/selectformaction.h
include/urlviewformaction.h
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/emptyformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/formaction.cpp
src/helpformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/listformaction.cpp
src/searchresultslistformaction.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
src/view.cpp
test/itemlistformaction.cpp

This implements an idea by @Minoru in https://github.com/newsboat/newsboat/pull/2507#issuecomment-1715312777
This is done in preparation of adding a new "bind" command.
We would like to handle some operations differently without changing the behaviour for the current bind-key and macro bindings.
This obsoletes https://github.com/newsboat/newsboat/pull/2507
I've cherry-picked one of the commits:
> (if we end up closing this PR) https://github.com/newsboat/newsboat/commit/c51cabb77fd62c2dfa17ee1b080ac4c6ca960849 is a very good observation and I'd like to have it anyway.

Prepare for "bind" command by specifying binding type instead of boolean "automatic"

---

src/rssparser.cpp
test/rssparser.cpp

Fixes https://github.com/newsboat/newsboat/issues/2573

Title fallback: Use content_encoded if description is empty

---

doc/chapter-firststeps.asciidoc
doc/configcommands.dsv

This replaces the confusing "per feed" wording, and makes it clear that the setting applies to any feed.
Prompted by
https://github.com/newsboat/newsboat/issues/164#issuecomment-1767484954. @Vinfall, can you please take a look and tell me what you think of this?

Clarify docs for `max-items` setting

---

rss/parser.cpp
src/reloader.cpp

Got inspired to add this by a question on our IRC channel.
This turned out not to be useful in that case, but might still be useful for other users to find/debug slow reloads.
Example output:
```
$ grep 'ScopeMeasure: function `Reloader::reload\|Reloader::reload: starting reload of' newsboat_2023-10-28_11.00.12.log
[2023-10-28 11:00:13] INFO: Reloader::reload: starting reload of https://newsboat.org/news.atom
[2023-10-28 11:00:13] DEBUG: ScopeMeasure: function `Reloader::reload' (stop over `start retrieving') took 0.005880 s so far
[2023-10-28 11:00:14] DEBUG: ScopeMeasure: function `Reloader::reload' (stop over `start parsing') took 0.236893 s so far
[2023-10-28 11:00:14] DEBUG: ScopeMeasure: function `Reloader::reload' (stop over `start replacing feed') took 0.251727 s so far …
```

Log timing information for reloading individual feeds

---

include/formaction.h
src/formaction.cpp
src/helpformaction.cpp
src/itemviewformaction.cpp

Deduplicate movement handling to make it a bit easier to extend the list of movement options (like https://github.com/newsboat/newsboat/issues/215, although that issue is about lists instead of textviews).

Deduplicate textview movement handling

---

include/formaction.h
src/feedlistformaction.cpp
src/formaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
test/itemlistformaction.cpp

Another (relatively) small change as part of integrating work from https://github.com/newsboat/newsboat/pull/2364.
Most operations don't need changes.
For now, I've tried to switch between the `bind-key` and `macro` handling based on number of operation arguments.
@Minoru Thanks for [your suggestion on a previous PR](https://github.com/newsboat/newsboat/pull/2555#pullrequestreview-1636399950):
> This looks fairly good already, but I'd prefer for if-then-else constructs to be converted into switches, on a principle that code should resist any attempts to introduce bugs :) With switch, we'll get a compilation error when we add a new enum value, which is great because it'll highlight all the places we potentially need to update.
That actually made this change a lot easier :)

Implement operation handling specialization for new "bind"

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/libnewsboat/src/filterparser.rs
rust/libnewsboat/src/logger.rs

Rust 1.70 stabilized `OnceCell` and `OnceLock` in the standard library: https://github.com/rust-lang/rust/pull/105587/
This probably obsoletes https://github.com/newsboat/newsboat/pull/2610

Drop `once_cell` dependency in favor of built-in OnceCell/OnceLock

---

doc/newsboat.asciidoc

The documentation specifies the title format defaults in two different locations.
One of those locations was missed when removing backticks from those formats in https://github.com/newsboat/newsboat/pull/1572.
Resolves https://github.com/newsboat/newsboat/issues/2625

Update overview of title formats

---

.cirrus.yml

Supersedes https://github.com/newsboat/newsboat/pull/2631.

CI: drop FreeBSD 12.4 which reached EOL

---

doc/manpage-newsboat.asciidoc
doc/manpage-podboat.asciidoc
src/pbcontroller.cpp

https://github.com/newsboat/newsboat/pull/2324 documented the different log-levels for newsboat. It also introduced automatic generation of a filename if `--log-level` was specified without `--log-file`.
This PR applies the same changes to podboat and updates both manpages.

Make newsboat/podboat logfile handling consistent; document behaviour

---

Cargo.toml
rust/libnewsboat-ffi/Cargo.toml
rust/libnewsboat/Cargo.toml
rust/regex-rs/Cargo.toml
rust/strprintf/Cargo.toml

There are no changes to the code: `cargo fix --edition` and `cargo fix --edition-idioms` did nothing. I guess this is expected because I don't see anything that'd be particularly relevant to us in the edition guide[1].
1. https://doc.rust-lang.org/edition-guide/rust-2021/index.html

Switch all our crates to Rust 2021

---

docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_22.04-build-tools.dockerfile
docker/ubuntu_23.10-build-tools.dockerfile
rust/libnewsboat/src/cliargsparser.rs

This only required a small fix for
https://rust-lang.github.io/rust-clippy/master/index.html#/get_first

CI: update to Rust 1.75.0

---

Makefile
include/keycombination.h
include/keymap.h
mk/libboat.deps
src/helpformaction.cpp
src/keycombination.cpp
src/keymap.cpp
src/pbview.cpp
src/view.cpp
test/configparser.cpp
test/keycombination.cpp
test/keymap.cpp
test/test_helpers/stringmaker/keycombination.h

STFL events currently are regular strings containing a key name, optionally prefixed with `^` (for the "control" modifier) or capitalized (for the "shift" modifier).
I expect a replacement for STFL might contain this information in a more structured way (a separate string for the key name and some flags to indicate active modifiers, e,g,: [Crossterm's `KeyEvent`](https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html)).
I expect this PR makes it easier to move away from STFL and, at the time, easier to introduce the new `bind` option.

Split key bindings and events into a base key with some modifiers (shift, control, alt)

---

rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat-ffi/src/keymap.rs
rust/libnewsboat-ffi/src/utils.rs

- stdexcept include added in https://github.com/dtolnay/cxx/commit/96e5d5e5be60b38a129af6fcffaf044faeb5db14
- cstddef include added in https://github.com/dtolnay/cxx/commit/08679aeae2ea1b8af6979890a7356fa04408a47f

Remove obsolete includes from cxx bridge modules

---

include/filepath.h
rust/libnewsboat-ffi/src/filepath.rs
rust/libnewsboat-ffi/src/utils.rs
src/utils.cpp

Discovered that we can use `Pin<&mut ...>` to allow mutation of Rust types defined in another cxx bridge module, based on:
- https://cxx.rs/extern-c++.html#opaque-c-types
> Unlike extern Rust types and shared types, an extern C++ type is not
> permitted to be passed by plain mutable reference &mut MyType across the
> FFI bridge. For mutation support, the bridge is required to use Pin<&mut
> MyType>. This is to safeguard against things like mem::swap-ing the
> contents of two mutable references, given that Rust doesn't have
> information about the size of the underlying object and couldn't invoke
> an appropriate C++ move constructor anyway.
- https://github.com/dtolnay/cxx/issues/942
I'm already happy with this result (took me long enough to try a lot of different options which did not …

Move utils bridged methods into their own ffi module

---

include/cliargsparser.h
include/configpaths.h
include/filepath.h
include/fslock.h
rust/libnewsboat-ffi/build.rs
rust/libnewsboat-ffi/src/cliargsparser.rs
rust/libnewsboat-ffi/src/configpaths.rs
rust/libnewsboat-ffi/src/fslock.rs
rust/libnewsboat-ffi/src/logger.rs
src/cliargsparser.cpp
src/configpaths.cpp
src/controller.cpp
src/fslock.cpp
src/pbcontroller.cpp
test/scopemeasure.cpp
test/test_helpers/loggerresetter.cpp

Resolves https://github.com/newsboat/newsboat/issues/2644
There are a few places where we now convert `Filepath` into `std::string` to then directly convert into a `Filepath` again.
I decided to postpone work on that given that we will find them already when working on https://github.com/newsboat/newsboat/issues/2326#issuecomment-1872314543

Use PathBuf on FFI (replacing `&str` and `String`)

---

rust/libnewsboat/src/fmtstrformatter/mod.rs

Each padding will add one of the padding character while the result is built. The left most padding is then expanded only at the end, when we have all the surrounding context formatted.
fixes #2645
I kept the `StringParts` in the same file, and it's only tested through the use in formatting.

Fix padding in conditional branch

---

contrib/linkding/README.md
contrib/linkding/linkding.rb

Super simple plugin for Linkding. Could stand to be refactored to use Ruby's native `net:http` library to remove the dependency on `httparty`. 
README has step-by-step on how to configure and deploy.

Adds a bookmark plugin for Linkding

---

contrib/wallabag/README.md
contrib/wallabag/wallabag.rb

A super simple bookmark plugin for Wallabag. Could stand to be refactored to use Ruby's native net:http library to remove the dependency on httparty. This one only sends the URL since Wallabag does its own extraction of title and description. 
README has step-by-step on how to configure and deploy.

adds simple wallabag bookmark plugin

---

src/utils.cpp

Currently the macro guard for manually setting up the OpenSSL library for multi-threaded use is confusing.
First, `openssl/opensslv.h` has to be included to use `OPENSSL_VERSION_NUMBER`. Otherwise `OPENSSL_VERSION_NUMBER` (= 0) < 0x01010000fL always holds. There is no bug here, this just creates unnecessary complexity imo.
Second, the correct unsigned long for version 1.1.0 is 0x10100000L, not 0x(0)1010000fL. The format is 0xMNN00PP0L where M := major, N := minor and P := patch version.
I also added a macro guard for manually setting up locking procedures for GnuTLS. This has been discouraged since version 2.11.0 and deprecated since 3.7.3.
See changelog: https://gitlab.com/gnutls/gnutls/-/blob/master/NEWS?ref_type=heads#L4521
and commit: …

Fix setup for old SSL library versions

---

include/dialogsformaction.h
include/dirbrowserformaction.h
include/emptyformaction.h
include/feedlistformaction.h
include/filebrowserformaction.h
include/formaction.h
include/helpformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
include/listformaction.h
include/searchresultslistformaction.h
include/selectformaction.h
include/urlviewformaction.h
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/emptyformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/formaction.cpp
src/helpformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/listformaction.cpp
src/searchresultslistformaction.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp
src/view.cpp
test/itemlistformaction.cpp

I recently heard about clang-tidy from a colleague.
With the default list of clang-tidy checks, there are a bunch of warnings.
Most of them in `filter/` which I'm going to ignore (generated code?).
A few in `src/htmlrenderer.cpp` which I don't think are useful to change on their own:
```
src/htmlrenderer.cpp:532:6: warning: Value stored to 'inside_video' is never read [clang-analyzer-deadcode.DeadStores]
inside_video = false;
^              ~~~~~
src/htmlrenderer.cpp:583:6: warning: Value stored to 'inside_audio' is never read [clang-analyzer-deadcode.DeadStores]
inside_audio = false;
^              ~~~~~
```
And a few in `src/filebrowserformaction.cpp` and `src/dirbrowserformaction.cpp` which I'm resolving in this PR:
```
src/dirbrowserformaction.cpp:38:34: warning: Call to virtual …
```

Fix clang tidy warnings

---

include/charencoding.h
mk/libboat.deps
rust/libnewsboat-ffi/build.rs
rust/libnewsboat-ffi/src/charencoding.rs
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat/src/charencoding.rs
rust/libnewsboat/src/lib.rs
src/charencoding.cpp
test/charencoding.cpp

These commits introduce a few utility functions for detecting the character encoding of text.
This can be used in a future PR to resolve several of our encoding issues (probably extending or obsoleting https://github.com/newsboat/newsboat/pull/2340).

Add utilities for detecting text encoding based on byte-order-mark and XML declaration

---

.cirrus.yml
.clang-tidy
.gitignore
Makefile
src/htmlrenderer.cpp
src/rssfeed.cpp

I'm a sucker for static analysis, so even though I initially agreed with https://github.com/newsboat/newsboat/pull/2654#issuecomment-1937004529, I still feel like we should have clang-tidy in CI. So here goes. My expectation is that we'll gradually expand .clang-tidy with more stringent checks.

Add clang-tidy to the Makefile and CI, fix warnings it produces

---

contrib/filters/twtxt2rss.php

Twtxt is a small plain-text microblogging protocol.
Twtxt2rss converts twtxt feeds into RSS feeds and enables people to follow twtxt feeds without a dedicated client.

Add a filter to convert twtxt feeds

---

.clang-tidy
Makefile
src/controller.cpp
src/pbcontroller.cpp
test/cache.cpp
test/remoteapi.cpp
test/test_helpers/opts.cpp

As noted in the first commit, this change doesn't affect our requirements for compilers, because our current requirements are already sufficient for C++14.
Inspired by @dennisschagt's comment: https://github.com/newsboat/newsboat/pull/2683#pullrequestreview-1887240317.

Compile in C++14 mode, migrate to `std::make_unique()` where possible

---

Cargo.lock
Makefile
rust/libnewsboat-ffi/build.rs

I just noticed that the CXX documentation was updated to recommend `.std()` over using `.flag("-std=...")`:
https://github.com/dtolnay/cxx/pull/1321/commits/699a12a67a684bcf98af4c9646cb9d65e5373c21

Compile CXX FFI with C++14

---

.cirrus.yml
Cargo.lock
rust/libnewsboat/src/logger.rs

Supersedes https://github.com/newsboat/newsboat/pull/2696 (this PR fixes warnings caused by the update)

Update to chrono 0.4.35

---

.cirrus.yml
include/formaction.h
src/formaction.cpp
src/itemrenderer.cpp
src/keymap.cpp
test/rssparser.cpp

This is yet another follow-up to https://github.com/newsboat/newsboat/pull/2654. The idea is: since we declare that C++11 compiler is enough for us, we should check that. We already checked by compiling with old compilers that didn't support newer standards, but that still left some room for error: e.g. GCC and Clang are fine with using designated initializers for structures even though they only appeared in C++20.

Fix -Wpedantic warnings

---

doc/internal/code-style.markdown

For my first contribution, I ran into issues running `make fmt` locally; it would reformat a ton of files I hadn't touched. I eventually realized there was a Docker container available for formatting, but the style guide didn't mention it. This PR adds a note for future contributors who might run into the same issue.

add a note in the style guide for the code fmt dockerfile

---

contrib/slashdot-replace-newlines.xslt

User **lv8pv** mentioned on the \#newsboat IRC channel that the newlines in Slashdot articles are not shown in Newsboat.
Feed url: http://rss.slashdot.org/Slashdot/slashdotMain
I don't know if newsboat does anything wrong in parsing the feed, but this script can be used to transform newlines into explicit html `<br>` elements.

Add xslt transformation for replacing Slashdot's newlines

---

include/rssignores.h
src/matcher.cpp
src/rssignores.cpp
test/rssignores.cpp

Optimize the `RssIgnores::matches` function by changing the underlying data structure that stores `ignore-article` commands from a `std::vector` to a `std::unordered_multimap`.
Only the keys for the `RssItem` feed url as well as `*` could be looked up; if none of those were present as keys in the map, then the map still has to be iterated through in order to do [feed url RegEx checking](https://github.com/newsboat/newsboat/blob/b448e5bf202d6c5656c123d2faf3c43de117c1a5/src/rssignores.cpp#L118-L123).
Part of https://github.com/newsboat/newsboat/issues/345.

optimize RssIgnores::matches function

---

docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_22.04-build-tools.dockerfile
docker/ubuntu_23.10-build-tools.dockerfile

1.77.1 [seem to be a Windows-only fix](https://blog.rust-lang.org/2024/03/28/Rust-1.77.1.html), but let's keep up to date anyway.

CI: bump Rust to 1.77.1

---

.github/workflows/coveralls.yaml

The user/repo `ATiltedTree/setup-rust` seems to have disappeared.
Based on https://github.com/rust-lang/rustup/issues/3409, there does not seem to be one specific action implementation which others are using for Rust setup.
However, `dtolnay/rust-toolchain` was mentioned in that issue and looks good to me.

Replace setup-rust action which disappeard (repo/user no longer exist)

---

.cirrus.yml
.github/workflows/coveralls.yaml

Current rust nightly seems to be based on LLVM 18:
```
$ rustc +nightly --version --verbose
rustc 1.79.0-nightly (aa1c45908 2024-04-06)
binary: rustc
commit-hash: aa1c45908df252a5b0c14e1bcb38c6c55ae02efe
commit-date: 2024-04-06
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

Update testcoverage build dependencies

---

doc/chapter-configuration.asciidoc

Fix default color documentation according to current code ./stfl/feedlist.stfl
Commit 368048b changed listnormal_unread and listfocus_unread, then commit a8971bd fixed those, but they did not correct the documentation. Commit 602d35b added hint-keys-delimiter, hint-separator, and hint-description; then commit 63b6c2f added the wrong documentation.

Fix default color documentation

---

rust/libnewsboat/Cargo.toml

I'm not sure why an incompatible change was made in a minor release...
Edit: Or is it actually compatible just that we used the new features without restricting the minor release?

Require chrono 4.34 since Duration was renamed to TimeDelta

---

rust/libnewsboat-ffi/src/charencoding.rs
rust/libnewsboat-ffi/src/utils.rs
rust/libnewsboat/src/configpaths.rs
rust/libnewsboat/src/fslock.rs

There seem to be some issues with the `assigning_clones` Clippy lint.
I plan to remove the `#[allow(clippy::assigning_clones)]` attributes when the related issues in Clippy are resolved.

Fix clippy warnings

---

include/feedbinapi.h
include/feedretriever.h
include/freshrssapi.h
include/minifluxapi.h
include/reloader.h
include/rssparser.h
include/ttrssapi.h
rss/parser.cpp
rss/parser.h
src/feedbinapi.cpp
src/feedretriever.cpp
src/freshrssapi.cpp
src/minifluxapi.cpp
src/reloader.cpp
src/ttrssapi.cpp
test/cache.cpp
test/rssfeed.cpp

I noticed that our production code always instantiates `FeedRetriever` with a non-null `CurlHandle`.
Changed the argument to a reference to make this obvious (and updated tests to make them use `FeedRetriever` in the same way as the production code).
Extended these changes to external APIs and other places where we use a `CurlHandle`.
Additionally I noticed that my C++ Vim plugin started highlighting unused header includes.
~~I've removed those unnecessary header includes in the files I had open for this PR.
If preferred, I can take out those changes and apply them in a separate PR.~~
-> I ran into some issues so will move these changes into a separate PR

Cleanup unused overloaded methods

---

docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_22.04-build-tools.dockerfile
docker/ubuntu_23.10-build-tools.dockerfile

Resolves https://github.com/newsboat/newsboat/issues/2474
I made a previous attempt to fix uid/gid at runtime (https://github.com/newsboat/newsboat/pull/2698)
That turned out to require a lot of workarounds, partially due to limitations in cirrus options.
Specifying uid/gid at build time seems to cause a lot less issues (to be confirmed by a successful CI build and some more local testing)

Match current user's uid/gid at docker build time

---

Makefile

Fixes https://github.com/newsboat/newsboat/issues/2724
Given that Git already checks out directories with 755 permissions and files with 644 permissions(or 755 for executable scripts), a simple copy should be enough.

Copy all contrib files/directories recursively

---

po/zh.po

Ref: https://github.com/newsboat/newsboat/pull/2766#issuecomment-2156020794
I update several unresolved items by the way. `query feed` is translated into `集合种子` which means aggregated feed and with original English by its side as a navigation to docs.

Update Chinese translations

---

po/sv.po

This fixes translations in the Swedish translation marked as needing work.

sv.po: Fix translations marked as needing work

---

.cirrus.yml
.gitignore
Cargo.lock
Cargo.toml
Makefile
rust/http-test-server/Cargo.toml
rust/http-test-server/src/main.rs
test/feedretriever.cpp
test/test.cpp
test/test_helpers/httptestserver.cpp
test/test_helpers/httptestserver.h
test/test_helpers/inputoutputprocess.cpp
test/test_helpers/inputoutputprocess.h
test/test_helpers/misc.cpp
test/test_helpers/misc.h

Alternative approach to https://github.com/newsboat/newsboat/pull/2736.
Http test server is now contained in a separate binary to avoid increasing the size of the regular newsboat/podboat binaries.
The C++ test code communicates with the http test server using (piped) stdin/stdout.

Http request testing (mock server in separate binary)

---

src/configcontainer.cpp

I was grepping the codebase for `recursive_mutex` after seeing the stack traces on #2783. (No idea if this has anything to do with that bug.)
However, this guard seems unnecessary to me. From [this stackoverflow answer](https://stackoverflow.com/questions/55942966/is-it-safe-to-hold-a-stdlock-guard-in-the-destructor/55943065#55943065) I would understand that the guard only holds for the destructor's body, which is empty in this case.
Does this guard have a reason? Is it fine to remove, or could the reason be explained in a comment, or am I missing something obvious?

Remove pointless(?) lock guard

---

contrib/readeck/README.md
contrib/readeck/interactive-labels-readeck.clj
contrib/readeck/standard-readeck.clj

Hi,
This adds two scripts to allow bookmarking to your [Readeck](https://readeck.org) installation.
They are Clojure scripts which need the added dependency of [Babashka](https://github.com/babashka/babashka#installation) to run, but using babashka allows for much faster startup times and memory usage than would be possible with JVM Clojure.
See the readme for more details :)

Readeck bookmark scripts

---

rss/exception.h
rss/parser.cpp
src/reloader.cpp
test/feedretriever.cpp

Resolves https://github.com/newsboat/newsboat/issues/2732

Don't retry feed retrieval on HTTP 304 (Not Modified)

---

.github/workflows/coveralls.yaml

When I first added the Coveralls workflow (in
3176869088e6451f853e2b826f88958afa07f972), I copied instructions from the then-current README:
https://github.com/coverallsapp/github-action/tree/8cbef1dea373ebce56de0a14c68d6267baa10b44 That README suggested the use of `coverallsapp/github-action@master`, i.e. the "master" branch.
Sometime in 2023, Coveralls changed their default branch to "main" and stopped updating "master". I haven't found any mention of this in their README and GitHub Releases; they don't keep a changelog.
As time went by, GitHub Actions deprecated Node 16, so Coveralls action from "master" started throwing warnings.
This if easily fixed on our end by using the tagged version of the action.

CI: bump Coveralls action

---

include/utils.h
rust/libnewsboat-ffi/src/utils.rs
src/utils.cpp
test/feedretriever.cpp
test/rsspp_parser.cpp
test/utils.cpp

This splits of part of the work from https://github.com/newsboat/newsboat/pull/2340

Test handling of character encodings specified in xml encoding attribute and http header

---

Cargo.lock
rust/libnewsboat/Cargo.toml
rust/libnewsboat/proptest-regressions/fmtstrformatter/limited_string.txt
rust/libnewsboat/src/utils.rs
test/utils.cpp

Resolves https://github.com/newsboat/newsboat/issues/2805
It looks like our handling of limited-width strings has some trouble with the unicode sequence `⚛️` consisting of:
- U+269B (Atom symbol)
- U+FE0F (Variation selector-16, indicates that preceding character should be displayed with emoji presentation)
We add unicode code points to the result string one-by-one, checking their individual length one at a time.
We use the `unicode-width` crate to determine the width of strings and separate code points.
For the above 2 code points, `unicode-width` returns a width of 1 and 0 respectively.
However, for the combination of the 2 code points it returns a total width of 2 columns.
When the result string gets bigger than the specified max length, several places of subtractions can result in an …

Avoid underflows in limited-width string formatting

---

docker/ubuntu_18.04-build-tools.dockerfile
docker/ubuntu_18.04-i686.dockerfile
docker/ubuntu_20.04-build-tools.dockerfile
docker/ubuntu_22.04-build-tools.dockerfile
docker/ubuntu_24.04-build-tools.dockerfile
rust/libnewsboat/src/human_panic.rs

This release enabled automatic checking of `cfg`s at compile-time[1], so Clippy started warning us about the use of `#[cfg(feature = "nightly")]`. Apparently I misunderstood how it works when I was copying code from the human-panic crate.
While trying to make the warning go away, I also realized that the Nightly-only code doesn't even compile, because we declare a function to return `String` but actually return `()`.
Apparently the proper way to fix this is to add compiler auto-detection to build.rs. This will slow down compilation a bit, for what I perceive to be a very small benefit; after all, we got this far without that Nightly-only API. Thus I removed the code that used the API.
1. https://blog.rust-lang.org/2024/05/06/check-cfg.html

CI: bump Rust to 1.80.0

---

include/utils.h
mk/libboat.deps
mk/newsboat.deps
rss/parser.cpp
rss/parser.h
rust/libnewsboat-ffi/src/utils.rs
src/utils.cpp
test/rsspp_parser.cpp
test/utils.cpp

This implements the idea from https://github.com/newsboat/newsboat/pull/2660#discussion_r1449461867.
Fixes https://github.com/newsboat/newsboat/issues/1436.
It might make sense to apply the changes in this PR to `utils::retrieve_url()` as well.
Previous attempts at fixing https://github.com/newsboat/newsboat/issues/1436 had some issues.
I believe we can avoid these using the recently added tests (this PR and https://github.com/newsboat/newsboat/pull/2801)
Previous attempts with issues they caused:
- https://github.com/newsboat/newsboat/pull/2214
- HTTP headers not handled correctly in case of a redirect
- Converted data twice if encoding was specified in `Content-Type` header and XML encoding attribute
- reverted via https://github.com/newsboat/newsboat/commit/fa363edd2d61e598aff0de5848ae9 …

Convert feed to utf-8 based on Content-Type header

---

src/itemlistformaction.cpp

Fixes https://github.com/newsboat/newsboat/issues/2814
Issue was introduced in https://github.com/newsboat/newsboat/commit/0175914ee5a831fea04ecec68cf2857b9002ba3f.
Stfl style tags are placed within the text to be styled.
For example, we use `<unread>item title</>` to apply the "unread" style to a title.
Previously, we applied styles by just adding style tags at the start of the formatted string (`<unread>`, `<0>`, `<1>`, etc.).
That effectively gave them a lower priority than all of the styling already in the string.
For example, `<unread><0>Item title</></>` ignores the "unread" style because it is directly overridden with the "0" style.
With my changes from https://github.com/newsboat/newsboat/pull/2084, we use an `StflRichText` class to apply styling.
In that class, added style tags …

Fix order of applying unread/highlight styles

---

CONTRIBUTING.md
README.md
doc/internal/howto-release.md
doc/newsboat.asciidoc

There's a fork in specifications, so I want to highlight that we'm using IETF's standard (OpenPGP) rather than GnuPG's (LibrePGP): https://lwn.net/Articles/953797/

(GPG|PGP) → OpenPGP

---

rust/libnewsboat/src/utils.rs

We recently started using `utils::convert_text()` for regular feeds retrieved over http/https (in https://github.com/newsboat/newsboat/pull/2804).
It looks like that slowed down reloads, as reported in https://github.com/newsboat/newsboat/issues/2815#issuecomment-2276411526 and https://github.com/newsboat/newsboat/issues/2815#issuecomment-2276583709.
It looks like convert_text can be improved significantly by using a bigger buffer.
That avoids a lot of overhead by letting `iconv()` go through bigger parts of data at a time.
Performance informally checked with a quick testcase.
The referenced `atom.xml` file size is approximately 520 KB
```
TEST_CASE("convert_text() performance", "[utils]")
{
const auto input = test_helpers::read_binary_file("/tmp/ttt/atom.xml");
const auto text = …
```

convert_text: Improve performance by using bigger output buffer

---

src/freshrssapi.cpp

Addresses issue #2784 with the same solution as in #943. Every time an article is marked as read it spawns a new thread to do the network request, fixing the issue where network latency renders newsboat unresponsive for the duration.

freshrss: mark article in new thread

---

.cirrus.yml
Cargo.lock

Remove workaround which was introduced in https://github.com/newsboat/newsboat/pull/2691 as it is now included in gettext-rs itself.

Update gettext-sys to 0.21.4

---

include/download.h
src/download.cpp
src/queueloader.cpp
test/download.cpp
test/queueloader.cpp

Old behavior was to mark it as "queued" (which was the starting/default state of any download).
This PR marks files which have been downloaded before but which no longer exist as "missing".
I expect hits is especially helpful when people (including me) would sometimes remove a podcast file from outside of podboat (either manually or via a file sharing program like Dropbox or Syncthing)

Podboat: Mark entry as missing if downloaded file does not exist

---

contrib/newsboat.fish

I just started using fish and though it might be nice to have some completions for newsboat.

Add completions file for the fish shell

---

rss/rss09xparser.cpp
test/data/rss_091_with_bracket_author.xml
test/data/rss_092_with_bracket_author.xml
test/data/rss_094_with_bracket_author.xml
test/rsspp_parser.cpp

**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.36
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): no config
Steps to reproduce the issue:
1.  Add `https://forum.awd.ru/smartfeed.php?forum=978&limit=3_MONTH&sort_by=user&feed_type=ATOM1.0&feed_style=HTML&max_word_size=250` to `~/.newsboat/urls`
2. run `/usr/bin/newsboat -x reload`
3. get error:
```
terminate called after throwing an instance of 'std::invalid_argument'
what():  data for rust::String is not utf-8
Aborted (core dumped)
```
This happens because of the post from a user with name Лю)): https://forum.awd.ru/viewtopic.php?f=978&t=36102&p=11902305#p11902305
This username is being handled by the snippet below. It finds ')' at the end of `authorfield` and then …

Handling author name ending with ')'

---

docker/code-formatting-tools.dockerfile

This is an alternative to #2874. I don't like the changes that Astyle 3.4 introduces, so I'd avoid upgrading to it if possible. By migrating the Docker image from Alpine to Debian, we can drag our feet a while longer, maybe long enough for Astyle to get fixed.

CI: fix build of code-formatting container

---

Makefile

This was submitted via our mailing list: https://groups.google.com/g/newsboat/c/D7O99E4zhCA

makefile: use MKDIR variable everywhere

---

src/cache.cpp

Resolves https://github.com/newsboat/newsboat/issues/2871
The old code probably would have broken with dates far into the future as well (2^32 -> somewhere in 2106)

Store negative timestamps in database to support dates before 1970

---

include/dialogsformaction.h
include/dirbrowserformaction.h
include/emptyformaction.h
include/feedlistformaction.h
include/filebrowserformaction.h
include/formaction.h
include/helpformaction.h
include/itemlistformaction.h
include/itemviewformaction.h
include/searchresultslistformaction.h
include/selectformaction.h
include/urlviewformaction.h
src/dialogsformaction.cpp
src/dirbrowserformaction.cpp
src/emptyformaction.cpp
src/feedlistformaction.cpp
src/filebrowserformaction.cpp
src/helpformaction.cpp
src/itemlistformaction.cpp
src/itemviewformaction.cpp
src/searchresultslistformaction.cpp
src/selectformaction.cpp
src/urlviewformaction.cpp

Came up with the idea while looking into https://github.com/newsboat/newsboat/issues/2857.
This PR introduces a new translatable string so merging might need to wait until after the upcoming release.

Show keymap hint for "clear filter" when filter is active

---

include/cache.h
include/controller.h
include/itemrenderer.h
include/itemutils.h
include/itemviewformaction.h
include/queuemanager.h
src/cache.cpp
src/controller.cpp
src/itemlistformaction.cpp
src/itemrenderer.cpp
src/itemutils.cpp
src/itemviewformaction.cpp
src/queuemanager.cpp
src/reloader.cpp
src/rssitem.cpp
src/view.cpp
test/cache.cpp
test/controller.cpp
test/feedretriever.cpp
test/itemrenderer.cpp
test/queuemanager.cpp

I remember seeing some reports a while back about memory usage growing over time.
Not sure if we reproduced it, but I recently got reminded that cycles of `std::shared_ptr`s can lead to memory being leaked.
I would like to reduce the amount of places where a `shared_ptr` is passed instead of a simple reference to simplify analysis at a later moment.

Reduce shared_ptr usage

---

include/keycombination.h
include/keymap.h
rust/libnewsboat-ffi/src/keycombination.rs
rust/libnewsboat/src/keycombination.rs
src/keycombination.cpp
src/keymap.cpp
test/keycombination.cpp

I'm not yet sure if we need to provide any escape characters (to allow for special keys `<`, `>`, `-`).
As far as I know, this PR supports these keys if they are used on their own but might have some issues if they are used in a sequence of keys or in combination with control/alt.

Parse key sequences and store new bindings into map/tree

---

rust/libnewsboat/src/keymap.rs
rust/libnewsboat/tests/configpaths_helpers/mod.rs
rust/libnewsboat/tests/fslock.rs
rust/strprintf/src/format_specifiers_32bit.rs
rust/strprintf/src/format_specifiers_64bit.rs
rust/strprintf/src/traits.rs

Ran into this while experimenting a bit with Cargo's `+nightly` option.
Fixing them now to avoid work when updating our current stable rust compiler version.

Resolve warnings generated by clippy (nightly)

---

include/stflrichtext.h
rust/libnewsboat-ffi/build.rs
rust/libnewsboat-ffi/src/lib.rs
rust/libnewsboat-ffi/src/stflrichtext.rs
rust/libnewsboat/src/lib.rs
rust/libnewsboat/src/stflrichtext.rs
src/stflrichtext.cpp

Part of https://github.com/newsboat/newsboat/pull/2892
For now, I've left all of the tests on the C++ side, given that those cover the combination of the Rust implementation together with the FFI.
My expectation is that we can get rid of the StflRichText relatively soon after moving away from STFL (and thus can keep the C++ glue+tests alive until that time)
I plan to keep this open for review until the end of the weekend.

Port StflRichText to Rust

---

include/cliargsparser.h
include/configpaths.h
include/fmtstrformatter.h
include/fslock.h
include/history.h
include/logger.h
include/scopemeasure.h
include/stflrichtext.h
include/utils.h
src/keycombination.cpp
src/utils.cpp

[Include What You Use docs for `pragma: export`](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#user-content-iwyu-pragma-export)

Apply `IWYU pragma: export` to avoid warnings from clangd LSP

---

src/controller.cpp
src/minifluxapi.cpp

Intended to make issues like https://github.com/newsboat/newsboat/issues/2870 easier to diagnose.
I'm not sure why `get_subscribed_urls()` only logs errors without stopping startup.
Only reason I can come up with is that it might also get called after an `edit-urls` command, in which case we probably don't want to crash/stop newsboat.

Report error when miniflux authentication check fails outside 401

---

rust/libnewsboat/src/human_panic.rs

The replacement ([PanicHookInfo](https://doc.rust-lang.org/nightly/std/panic/struct.PanicHookInfo.html)) was only added in 1.81.0, and thus not yet supported in our MSRV 1.79.0.

Ignore PanicInfo deprecation until MSRV supports replacement

---

.github/workflows/coveralls.yaml
.gitignore
Makefile
test/generate_coverage_report.sh

We used to rely on `-Zprofile`, but it was recently removed from Rust Nightly: https://github.com/rust-lang/rust/pull/131829 This commit switches to a stable alternative; cf. https://github.com/mozilla/grcov/issues/1240
This change is accompanied by a change in the build environment: instead of using Clang 18 with Rust Nightly, we now use Clang 18 with Rust 1.81. That's the last Rust version based on LLVM 18. Previously we tried to match LLVM versions between C++ and Rust to avoid weird coverage results. Now, it's *required* to match them, otherwise no coverage is gathered at all.
Fixes #2912.
This doesn't seem controversial, and the issue blocks all PRs, so I'll merge in three days if there are no reviews.

Migrate to source-based code coverage

---

doc/newsboat.asciidoc
src/minifluxapi.cpp

The enclosures are retrieved from the `enclosures` field of the existing JSON response from `Get Feed Entries`.
The API JSON format for an enclosure is specified here: https://miniflux.app/docs/api.html#endpoint-get-enclosure
The relevant issue in Miniflux is miniflux/v2#1059 which was solved in miniflux/v2#2109.

Add support for enclosures from Miniflux

---

include/configcontainer.h
src/configcontainer.cpp
src/controller.cpp
src/dirbrowserformaction.cpp
src/feedretriever.cpp
src/filebrowserformaction.cpp
src/itemlistformaction.cpp
src/itemrenderer.cpp
src/itemviewformaction.cpp
src/newsblurapi.cpp
src/pbcontroller.cpp
src/queueloader.cpp
src/queuemanager.cpp
src/reloader.cpp
src/utils.cpp
src/view.cpp
test/configcontainer.cpp
test/controller.cpp
test/queueloader.cpp

This method fetches ConfigData::PATH settings and resolves tilde in them. Thus get_configvalue() no longer needs special handling for PATHs.
This commit also migrates all relevant calls to the new method.
Most of the changes were mechanical. A few required judgment calls; `QueueManager::generate_enqueue_filename()` implements support for formats inside a filepath, which I believe can lead to bugs because `FmtStrFormatter` will attempt to format a `Filepath`, which has unknown encoding. But the existing C++ code seem to work, so I ported it to Filepath as closely as possible.
This is yet another step towards #2326.

Add ConfigContainer::get_configvalue_as_filepath()

---

test/feedretriever.cpp

A user reported an issue with Curl cookiejar usage on IRC.
I've not been able to reproduce the issue yet.
While testing, thought it might be nice to have test for some basic cookie-cache functionality.
This PR adds a test which verifies the work done in https://github.com/newsboat/newsboat/pull/50
Relevant Curl documentation:
- Writing cookies: https://curl.se/libcurl/c/CURLOPT_COOKIEJAR.html
- Reading cookies: https://curl.se/libcurl/c/CURLOPT_COOKIEFILE.html

Add test to check cookie-cache functionality

---

.cirrus.yml

https://www.freebsd.org/news/newsflash/#2024-12-03:1

CI: Upgrade FreeBSD 14.1 to 14.2

---

src/reloader.cpp

Resolves https://github.com/newsboat/newsboat/issues/2935
I see some other possible solutions but I would like to get this fix in as a stopgap solution for the coming release.
Possible alternatives (not really sue if they make sense for us, probably quite a bit more complex to use correctly)
- Using separate easy handles but [setting up sharing explicitly](https://everything.curl.dev/helpers/sharing.html#sharing-between-easy-handles)
- Use curl multi (to put multiple easy-handles in a pool which shares resources)
- ...?

Set cookiejar option again to take effect during curl_easy_cleanup()

---

doc/chapter-configuration.asciidoc
doc/newsboat.asciidoc

Back in the days, we put the key strokes in double quotes. However, this convention was changed to AsciiDoc's `kbd:` syntax later. Apparently, we missed some key strokes during the migration. So, this commit changes the remaining ones to the proper syntax.
Lowercase keys in the old syntax are now converted to uppercase. The old uppercase keys still remain uppercase, but get an explicit Shift prefix.

Docs: use proper markup for key presses

---

.cirrus.yml

https://github.com/newsboat/newsboat/pull/2877 caused quite a few unnecessary CI tasks to run.
I might add a few more docker files for easy testing with one of our supported remote services.
These changes should reduce the unnecessary CI load in those cases.

Avoid most of our CI build tasks on changes in `docker/remote-testing`

---

doc/newsboat.asciidoc

Cf. https://github.com/newsboat/newsboat/issues/2976#issuecomment-2605108693

Link to `macro` and `macro-prefix` from the relevant doc section

---

.clang-tidy
Makefile

This makes it bit nicer to add & test new clang-tidy rules for the code base.
The fix-target can apply any automatic fixes, and having the rules defined as a proper list makes it easier to add (less likely to conflict).

Clang tidy fix target & config improvement

---

include/formaction.h
include/keymap.h
include/view.h
src/keymap.cpp
src/pbview.cpp
src/view.cpp
test/configparser.cpp
test/keymap.cpp

Part of https://github.com/newsboat/newsboat/pull/2364 (I've updated the list with TODOs based on code comments added in these commits)
The existing automatic tests for KeyMap were very useful in this case (caught several issues).
To test these changes manually:
- uncomment the `cfgparser.register_handler("bind", keys);` lines in `src/controller.cpp` and `src/pbcontroller.cpp`
- add a few `bind` commands to your config, e.g.:
```
bind gg everywhere home
bind G everywhere end
bind gt everywhere next-dialog
bind gT everywhere prev-dialog
```
All existing bind-key configs should still be working as before.

Store bind-key and bind configuration in the same map/tree-structure; Support multi-key sequences in a few places

---

include/configcontainer.h
src/configcontainer.cpp
src/formaction.cpp

Resolves https://github.com/newsboat/newsboat/issues/2989

Avoid crash on setting non-existent config option

---

include/stflrichtext.h
rust/libnewsboat-ffi/src/stflrichtext.rs
rust/libnewsboat/src/stflrichtext.rs
src/helpformaction.cpp
src/stflrichtext.cpp

I think case-insensitive regex search & replace is suitable for this.
There could still be some discrepancy between the case matching of this and `strcasestr`, which is used as the precondition check.
The added function is quite specific. It might also be beneficial to construct the regex once outside the `apply_highlights` lambda, but don't know if it's worth the bridging effort.
Fixes #2998

Highlight search phrase case insensitively

---

rust/libnewsboat/src/keycombination.rs
src/keycombination.cpp
src/keymap.cpp
test/keycombination.cpp
test/keymap.cpp

Part of https://github.com/newsboat/newsboat/pull/2364

Keybindings: Allow escaping `<` and `>` using `<LT>` and `<GT>`

---

.cirrus.yml
Makefile
README.md
doc/newsboat.asciidoc
rust/libnewsboat-ffi/build.rs

Fixes #3031.
I'll update compiler requirements in the README and the docs once CI failed and I see which compilers to exclude.

Draft: Compile in C++ 17 mode

---

doc/chapter-configuration.asciidoc

Added a note about things I learned from [this discussion with Dennis](https://github.com/newsboat/newsboat/pull/3037#discussion_r2006345561). After thinking about it, I decided that we can either:
* roll with the current implementation
* allow ambiguous binds, and make Newsboat wait for a timeout when the prefix is entered
The second option can be implemented later (if it's ever needed at all), so I'll be releasing `bind` as past or Newsboat 2.39 today.
Maybe we should make this into a run-time warning, so people are immediately notified if one of their `bind`s removes some of the earlier ones.
---
I also changed the "supported since" text because it looked like we didn't have any kind of bindings prior to 2.39 :)

Docs: add note about `bind`s with shared prefixes

---

src/itemviewformaction.cpp

Condition was specified the wrong way around causing a crash when using `edit-flags` configured using `bind`.
`bind-key` (and the default keybinding for `edit-flags` -> `Ctrl+E`) were not effected, as they would hit the `::BindKey` arm of the switch statement.
Caused by me in [commit 39c66a321](https://github.com/newsboat/newsboat/commit/39c66a321fad85936d925ceb1e52f6aba99ee5e6#diff-05722ea839454b7bbe5203d23a4a58a8391d9f6e2c9a6ff93398b1a58e98dab0R335)

Fix edit-flags when used from new-style binding

---

test/opml.cpp

Fields were marked deprecated in [libxml commit b34dc1e4](https://gitlab.gnome.org/GNOME/libxml2/-/commit/b34dc1e4a3afecad13b21d5ef38dc26851371abc)

Avoid using deprecated fields of xmlBuffer

---

contrib/colorschemes/monochrome

Adding beautiful monochrome readable color scheme that morph into any terminal default style.

Add "monochrome" colorscheme

---

include/configdata.h
src/configcontainer.cpp
src/configdata.cpp
test/configcontainer.cpp

Fixes https://github.com/newsboat/newsboat/issues/3104

ConfigContainer: Get rid of INVALID config type

---

include/filepath.h
rust/libnewsboat-ffi/src/filepath.rs
rust/libnewsboat/src/filepath.rs
rust/libnewsboat/src/lib.rs
src/configcontainer.cpp
src/filepath.cpp
src/poddlthread.cpp
src/queueloader.cpp
test/filepath.cpp

Yet another step towards #2326.
The complication here was that `PodDlThread` adds ".part" extension to the temporary files it creates. Rust doesn't have a stable API for that: [`PathBuf::add_extension()` is unstable](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.add_extension). I ended up re-implementing the method in stable Rust.
The other changes are trivial conversions to strings before passing them into standard APIs.

Remove implicit Filepath conversions from PodDlThread

---

doc/newsboat.asciidoc

Document quotes when query feed name contains spaces

---

rss/rss09xparser.cpp
test/rsspp_parser.cpp

Fixed possible null pointer derefence:
```console
AddressSanitizer:DEADLYSIGNAL
=================================================================
==407==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55a62d83f800 bp 0x7ffe84d27e50 sp 0x7ffe84d275f0 T0)
==407==The signal is caused by a READ memory access.
==407==Hint: address points to the zero page.
#0 0x55a62d83f800 in strcmp (/fuzz/rss_asan+0x38d800) (BuildId: 60fb1f3ae69daa2ec9150edf40877fd4aa57c418)
#1 0x55a62e3f21d2 in rsspp::Rss09xParser::parse_feed(rsspp::Feed&, _xmlNode*) /src/rss/rss09xparser.cpp:27:20
#2 0x55a62e3ec10a in rsspp::Parser::parse_xmlnode(_xmlNode*) /src/rss/parser.cpp:373:13
#3 0x55a62e3ea6a5 in rsspp::Parser::parse_buffer(std::__cxx11::basic_string<char, std::char_traits<char>, …
```

fix: add null check in rss09xparser

---

rss/parser.cpp
test/rsspp_parser.cpp

Resolves https://github.com/newsboat/newsboat/issues/3070
I've checked that the new test fails if the change in `rss/parser.cpp` is omitted.
When the test fails, it fails with the same error as reported in the linked issue (exception with message: `could not parse buffer`)

Fallback to libxml's encoding autodetection if our text conversion fails

---

config.h
include/filepath.h
src/cache.cpp
src/controller.cpp
src/dirbrowserformaction.cpp
src/filebrowserformaction.cpp
src/itemrenderer.cpp
src/pbcontroller.cpp
src/view.cpp
test/cliargsparser.cpp
test/colormanager.cpp
test/configcontainer.cpp
test/configparser.cpp
test/configpaths.cpp
test/controller.cpp
test/download.cpp
test/feedretriever.cpp
test/filepath.cpp
test/fileurlreader.cpp
test/fslock.cpp
test/history.cpp
test/opml.cpp
test/queueloader.cpp
test/queuemanager.cpp
test/remoteapi.cpp
test/rsspp_parser.cpp
test/strprintf.cpp
test/test_helpers/maintempdir.cpp
test/utils.cpp
test/view.cpp

This implements the suggestion from https://github.com/newsboat/newsboat/pull/3120#discussion_r2232843746, and cleans up some of the code quite nicely IMHO.
Cf. https://github.com/newsboat/newsboat/issues/2326.
I believe this is going to be the final PR before the rebase onto current master and the mega-PR to finally get this into the main branch.

Add user-defined literal ""_path for constructing Filepath from string

---

.github/workflows/coveralls.yaml

The issue got fixed upstream so we no longer need this workaround.

Remove workaround for .gitignore-related issue in grcov

---

src/opml.cpp
test/data/body-element-missing.opml
test/data/opml-element-missing.opml
test/opml.cpp

User kd4ihw_home reported an issue in our IRC channel. Newsboat showed a success message that the OPML file was successfully imported. However, the urls file wasn't touched at all, no URLs had been added.
It turned out that the OPML file was actually invalid. The exact problem with the OPML file wasn't confirmed, but the <body> element in the <opml> root element must have been missing, so no data were processed. The provided strace output did not include any write attempt to the urls file, supporting this theory.
Now, we show a dedicated error message if there is no <body> element. For good measure we now also abort right away if the root element is not an <opml> element. This should improve the user experience and avoid debugging effort.
Here's it in action:
```
$ LC_ALL=C ./newsboat -i …
```

Report error if OPML file is missing <opml> or <body>
