newsboat/newsboat

include/controller.h, src/controller.cpp
Closes #1.
@tsipinakis, would you please give this code a glance? `controller` is a huge messy blob, and I don't want to get into refactoring right before release. So I cobbled together something ugly but working. If you can test this too, that'd be stellar. (I did my own testing and it all seem to work as expected.)
=> Migrate Newsbeuter configuration on the first run

include/colormanager.h, include/configcontainer.h, include/configparser.h, include/dialogs_formaction.h, include/exception.h, include/exceptions.h, include/feedhq_api.h, include/feedlist_formaction.h, include/filebrowser_formaction.h, include/filtercontainer.h, include/help_formaction.h, include/itemlist_formaction.h, include/itemview_formaction.h, include/keymap.h, include/newsblur_api.h, include/ocnews_api.h, include/oldreader_api.h, include/regexmanager.h, include/rss.h, include/select_formaction.h, include/ttrss_api.h, include/urlreader.h, include/urlview_formaction.h, rss/rsspp.h, rss/rsspp_internal.h
I used clang-tidy's 'modernize-use-override' to automatically add the overrides. Hopefully no places were missed.
=> Fix issue #9

po/de.po
Time to add German translations for the new messages and fix a few older ones. FYI: I'm a German native speaker.
=> Update German translations

doc/faq.txt
Intended to do that a long time ago:
https://github.com/akrennmair/newsbeuter/issues/582#issuecomment-317113498
=> Add FAQ entry on waiting for the browser

src/fslock.cpp
Small spelling mistake reported by lintian.
=> Fix spelling mistake

src/filebrowser_formaction.cpp, src/formaction.cpp, stfl/filebrowser.stfl
These are various small-ish fixes that I couldn't justify breaking them out into their own PR each.
=> Various fixes for qna and filebrowser

po/fr.po
Following the call on the Rss feed, here is a contribution to the french translation for review.
It fixes 4 untranslated strings and reworks 4 fuzzy strings
=> Contribution to french translation

src/filebrowser_formaction.cpp
=> Fix filetype recognition in the filebrowser

include/filebrowser_formaction.h, src/filebrowser_formaction.cpp
This will add formatting to following file types:
- directories got suffix /
- links got suffix @
- executables got suffix *
Issue #127
=> Add ls --classify like formatting for filenames in filebrowser

doc/newsboat.txt
In relation to #193. @decibyte, what do you think about new wording?
=> Explain "*" pattern in `ignore-article` better

include/cliargsparser.h, include/controller.h, src/cliargsparser.cpp, src/controller.cpp, src/textformatter.cpp, src/urlreader.cpp, test/cliargsparser.cpp
This is my take on issue #205. Let me know if this seems reasonable.
=> Let CLIArgsParser collect '-x' commands

src/configcontainer.cpp
=> Sugarcoat configcontainer

src/controller.cpp
Basically name a var better + more expressive clamp (IMO, so feel free to discard this ;)).
=> Sweep controller a bit

po/sv.po
_(This is my first pull request. Hopefully I haven't made any mistake, but if I have, please let me know. :))_
This fixes issue #246.
By the way, I plan to go over the Swedish translation more extensively as soon as I have the time (probably next week).
=> Update sv.po: corrected grammatical error

po/sv.po
I completed and also made an extensive overhaul of the Swedish translation. For translation of technical terms, I have tried to follow the recommendations of the Joint Group for Swedish Computer Terminology (they have a database of Swedish computer terms at http://dataterm.termado.net/), for the terms where they have such recommendations.
=> Extensive overhaul.

doc/chapter-environment-variables.txt, src/controller.cpp
=> Source $TMPDIR variable if it exists

include/controller.h, include/reloader.h, src/controller.cpp, src/reloader.cpp
Maybe it should be pushed even further by creating a Notifier object, but I'm not sure atm. Opinions?
=> Move notify() from controller to reloader

include/rss.h, include/utils.h, mk/mk.deps, src/cache.cpp, src/controller.cpp, src/feedcontainer.cpp, src/feedhq_urlreader.cpp, src/feedlist_formaction.cpp, src/inoreader_urlreader.cpp, src/itemlist_formaction.cpp, src/newsblur_urlreader.cpp, src/ocnews_urlreader.cpp, src/oldreader_urlreader.cpp, src/rss.cpp, src/rss_parser.cpp, src/ttrss_urlreader.cpp, src/utils.cpp, src/view.cpp, test/rss.cpp, test/utils.cpp
The code duplication drove me nuts.
=> Add helper methods to check whether feed or url is a query feed or url

include/utils.h, src/controller.cpp, src/utils.cpp, test/utils.cpp
@Minoru Can you comment on the handling of `base` in the code. 
For the case when the URL is "https://example.com/notabase/?param=value", this would pick notabase as the filename. Is this acceptable?
=> Use libxml2 to read podcast episode URL

src/inoreader_api.cpp, src/oldreader_api.cpp
Resolves #175 , #188 for inoreader and old reader
It's been a while since I've done any C++ coding (read: over a decade) and I'm not a programmer by trade, but it seemed like a simple enough change
=> Escape URLs for Inoreader, Old Reader

include/controller.h, include/feedlist_formaction.h, include/itemlist_formaction.h, include/itemview_formaction.h, include/reloader.h, include/view.h, src/controller.cpp, src/feedlist_formaction.cpp, src/itemlist_formaction.cpp, src/itemview_formaction.cpp, src/reloader.cpp, src/view.cpp, test/itemlist_formaction.cpp
(This is a part of #213)
Remove one layer of indirection.
=> Remove get_cache() from controller

include/controller.h, include/feedlistformaction.h, include/itemlistformaction.h, include/view.h, src/controller.cpp, src/feedlistformaction.cpp, src/itemlistformaction.cpp, src/view.cpp, test/itemlistformaction.cpp
=> Remove get_filters() from controller

include/controller.h, include/dialogsformaction.h, include/feedlistformaction.h, include/filebrowserformaction.h, include/formaction.h, include/helpformaction.h, include/itemlistformaction.h, include/itemviewformaction.h, include/listformaction.h, include/reloader.h, include/selectformaction.h, include/urlviewformaction.h, src/controller.cpp, src/dialogsformaction.cpp, src/feedlistformaction.cpp, src/filebrowserformaction.cpp, src/formaction.cpp, src/helpformaction.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/listformaction.cpp, src/reloader.cpp, src/selectformaction.cpp, src/urlviewformaction.cpp, src/view.cpp, test/itemlistformaction.cpp
=> Remove get_cfg() from controller

include/rs_utils.h, src/utils.cpp
=> Add RustString class

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp
=> Add rust implementation of to_u

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp
addresses 2/40ths #334 
These were related and small so I did them together.
=> Add rust implementation of trim functions.

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp, test/utils.cpp
See https://github.com/newsboat/newsboat/issues/334
=> Rustify utils::is_http_url

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp
=> Rustifiy is_xx_url utility functions

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/Cargo.toml, rust/libnewsboat/src/utils.rs, src/utils.cpp
See #334. This is still work in progress, since I'm not sure how to do the error handling. See comments.
=> Rustify absolute url

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/Cargo.toml, rust/libnewsboat/src/utils.rs, rust/libnewsboat/tests/env.rs, rust/libnewsboat/tests/get_default_browser.rs, rust/libnewsboat/tests/resolve_tilde.rs, src/utils.cpp
=> Rust implementation of resolve tilde 

rust/libnewsboat/src/utils.rs
Some tabs snuck into the utils.rs file. This remove them for consistency.
=> Replace tabs with spaces in utils.rs

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/controller.cpp, src/utils.cpp, test/utils.cpp
=> Port `get_command_output` to rust

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp, test/utils.cpp
I'm glad I get blame credit for the comments on this function.
=> Part of #334: Convert make_title to rust

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp
This is the first piece of rust I've written so there's bound to be quite a few mistakes.
=> Rewrite quote* functions to Rust

Cargo.lock, include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/Cargo.toml, rust/libnewsboat/src/utils.rs, src/utils.cpp, test/utils.cpp
Added a crate on this one that has a 'database' of widths.
lib.rs looks pretty diffrent from last time, let me know if what I've done is right.
=> Rust implementation of strwidth() #334

README.md
=> README: Describe rust-fmt usage

doc/configcommands.dsv, po/ca.po, po/de.po, po/es.po, po/es_ES.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po, src/controller.cpp
I did a case insensive grep for every instance of newsblur, and then checked them manually.
I hope I got them all.
=> Correct Newsblur to NewsBlur

src/view.cpp
=> Apply keybindings when creating DialogsFormAction

contrib/image-preview/README.org, contrib/image-preview/nbparser, contrib/image-preview/nbrun, contrib/image-preview/vifmimg
=> Added contrib scripts for image preview

src/configparser.cpp, test/configparser.cpp, test/data/config-space-backticks
=> Spaces in shellout evaluate properly

include/configparser.h, include/rs_utils.h, include/utils.h, rust/libnewsboat-ffi/src/utils.rs, rust/libnewsboat/src/utils.rs, src/configparser.cpp, src/controller.cpp, src/utils.cpp, test/configparser.cpp, test/data/config-absolute-include, test/data/config-missing-include, test/data/config-recursive-include, test/data/config-relative-include, test/data/diamond-of-death/A, test/data/diamond-of-death/B, test/data/diamond-of-death/C, test/data/recursive-include-side-effect, test/utils.cpp
Fixes #489
Allows config files to be `include`d from other config files relative to eachother.
Major changes:
`ConfigParser::included_files` is now of type `std::vector`, not `std::set`
added `utils::resolve_relative`, modeled after `utils::resolve_tilde` (written in rust)
=> Relative config file paths support

doc/code-style.markdown
I made a lot of little decisions in #295, but these were never documented. This PR fixes that.
@der-lyse, you're my conscience when it comes to code style, so I guess it's fitting to have you review this (if you have the time, of course) ;)
=> Update coding style guide

include/configpaths.h, src/configpaths.cpp, src/controller.cpp, test/cache.cpp, test/cliargsparser.cpp, test/configparser.cpp, test/configpaths.cpp, test/fileurlreader.cpp, test/itemlistformaction.cpp, test/opml.cpp, test/opmlurlreader.cpp, test/test-helpers.h, test/utils.cpp
Fixes #510.
Reviews from anyone are welcome! This is a lot of boring code, and I'm not sure what I expect from a reviewer, but I guess it won't hurt either.
=> Add tests for ConfigPaths

src/pbcontroller.cpp, src/queueloader.cpp, src/queuemanager.cpp
=> Fixes for #290 and #457

test/test-helpers.cpp
The error was found while playing with GCC's address sanitizer. It doesn't seem worthy of a separate issue, so I'm just fixing it.
=> Fix use-after-free in EnvVar tests

include/cache.h, include/itemlistformaction.h, include/rssfeed.h, include/scopemeasure.h, src/cache.cpp, src/configcontainer.cpp, src/fslock.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/rssfeed.cpp, src/rssparser.cpp, src/tagsouppullparser.cpp, test/cache.cpp, test/opml.cpp, test/opmlurlreader.cpp, test/test-helpers.h
This fixes a number of problems found by Coverity Scan and PVS Studio. Nothing sensitive as far as I can tell, and nothing major (I'd love to see a tool that can found the memleak for me!).
Reviews from anyone who knows C++ are welcome. If none appear, I'll merge this in three days.
=> Static analysis fixes

include/rs_utils.h, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat-ffi/src/utils.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp, test/test-helpers.h, test/utils.cpp
This is still WIP, but I need some feedback since I'm not sure how the Rust function should look like :slightly_smiling_face: .
See #334
=> Rustify utils::getcwd

doc/configcommands.dsv, doc/newsboat.txt, include/feedcontainer.h, include/selectformaction.h, src/configcontainer.cpp, src/feedcontainer.cpp, src/selectformaction.cpp, test/feedcontainer.cpp
Hopefully this works.
https://github.com/newsboat/newsboat/issues/588
=> Issue #588.

test/feedcontainer.cpp
Nothing fancy; the title says it all.
Will merge in three days if noone stops me for a code review.
=> Improve FeedContainer test coverage

include/itemlistformaction.h, src/itemlistformaction.cpp
Just a couple tweaks I made while looking over the code.
Will merge in three days unless someone stops me for a code review.
=> Cosmetic changes to ItemListFormAction

doc/newsboat.txt
Inspired by #602.
Will merge in three days unless someone stops me for a review.
=> Mention `datetime-format` in `articlelist-format` doc

.cirrus.yml
=> Run C++ tests on FreeBSD

include/feedlistformaction.h, include/itemlistformaction.h, src/feedlistformaction.cpp, src/itemlistformaction.cpp
=> Fix filter being unapplied when a command is ran (again!)

include/rs_utils.h, rust/libnewsboat-ffi/src/utils.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp
I've been using newsboat recently and it's been top notch! I'm hoping to help out with some rust contributions.
I'm not sure whether you prefer the `if let` vs `match` approach and `unwrap` on the iterator last call (docs says there will always be at least one element). Let me know what I should change.
=> port utils::get_basename to rust #334

rust/libnewsboat-ffi/src/configpaths.rs, rust/libnewsboat/src/configpaths.rs, rust/libnewsboat/tests/configpaths_process_args_replaces_paths_with_the_ones_supplied_by_cliargsparser.rs, rust/libnewsboat/tests/configpaths_returns_paths_to_dotdir.rs, rust/libnewsboat/tests/configpaths_returns_paths_to_newsboat_xdg_dirs_if_they_exist_and_dotdir_doesnt.rs, rust/libnewsboat/tests/configpaths_set_cache_file_changes_paths_to_cache_and_lock_files.rs
This executes the plan outlined in #509.
Everyone is welcome to review. Otherwise I'll merge this in three days.
Fixes #509.
=> A few "obvious" refactors to ConfigPaths

test/opml.cpp
Fixes #621.
I'll merge this in three days unless someone stops me for a review.
=> Free libxml2 doc in Opml tests

rss/parser.cpp, src/opmlurlreader.cpp
Fixes #624.
I'll merge this in three days unless someone stops me for a review.
=> Free XML properties after using them

.cirrus.yml
Fixes #577.
Will merge in three days unless someone stops me for a review.
=> Add macOS task to Cirrus CI

include/configcontainer.h, include/itemlistformaction.h, include/rssfeed.h, include/utils.h, rss/rssparser.cpp, src/configcontainer.cpp, src/itemlistformaction.cpp, src/newsblurapi.cpp, src/ocnewsapi.cpp, src/queueloader.cpp, src/queuemanager.cpp, src/rssfeed.cpp, src/rssitem.cpp, src/ttrssapi.cpp, src/utils.cpp, src/view.cpp
This fixes three simple issues found by Clang's ThreadSanitizer. There are four more, which are harder to fix—they're reported in #672, #673, and #674.
I'll merge this in three days, unless someone—anyone—will stop me for a review.
=> Fix a couple issues found by ThreadSanitizer

README.md, logo.svg
noobilanderi created an icon for Newsboat, and [shared it on the mailing list](https://groups.google.com/forum/#!topic/newsboat/Xm5pTsbeMEk). It's [licensed under CC BY 4.0](https://groups.google.com/forum/#!msg/newsboat/Xm5pTsbeMEk/iCDDvGeGAAAJ).
I like it, and I'm going to merge it in three days unless someone sees something wrong with it.
(When I merge this, I'm going to turn it into a favicon for the site as well)
=> Add a logo

include/cache.h, src/cache.cpp, src/controller.cpp, test/cache.cpp
All the credit is due to @Brn9hrd7; I'm only a committer.
Fixes #484.
=> Take killfiles into account for print-unread

src/poddlthread.cpp
Fixes https://github.com/newsboat/newsboat/issues/725.
=> Add explicit null-termination to poddl directory string

config.h, src/cache.cpp, src/configparser.cpp, src/dirbrowserformaction.cpp, src/download.cpp, src/filebrowserformaction.cpp, src/htmlrenderer.cpp, src/itemlistformaction.cpp, src/listformatter.cpp, src/pbcontroller.cpp, src/queueloader.cpp, src/queuemanager.cpp, src/tagsouppullparser.cpp, src/textformatter.cpp, src/utils.cpp, src/view.cpp
=> Fix path navigation in FileBrowser and DirBrowser

mk/mk.deps, test/download.cpp
Definitely doesn't test all behavior of the Download class but I would like to get some feedback before writing too many tests.
=> Add some tests for Download class

include/controller.h, newsboat.cpp, po/ca.po, po/de.po, po/es.po, po/es_ES.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po, src/controller.cpp, test/itemlistformaction.cpp
Fixes #294.
I'll merge this in three days unless someone—anyone—stops me for a review.
=> Display paths to config/urls/cache in --help

CHANGELOG.md, doc/newsboat.txt, doc/podboat-cmds.dsv, include/pbview.h, po/ca.po, po/de.po, po/es.po, po/es_ES.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po, src/configcontainer.cpp, src/pbview.cpp, src/poddlthread.cpp
=> Podboat: Show human readable download speed

contrib/pinboard.pl
Pinboard/Newsboat has the ability to post a description, but the Perl script didn't use that ability. I've added that ability.
=> Add "Description" to Pinboard/Perl bookmark script.

doc/newsboat.txt, include/dirbrowserformaction.h, include/filebrowserformaction.h, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp
=> Fix filebrowser/dirbrowser title showing ".."

.cirrus.yml
This should speed the builds up (a tiny bit) and lower the impact of
network outages.
Will merge in 24 hours.
=> Cirrus CI: cache downloaded crates

include/rs_utils.h, rust/libnewsboat-ffi/src/utils.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp, test/utils.cpp
=> Port extract_filter to rust

rust/libnewsboat-ffi/src/utils.rs
This makes good [of a promise I gave in another PR](https://github.com/newsboat/newsboat/pull/758#discussion_r379823665).
=> Explain why unwrap() and expect() won't panic

doc/newsboat.asciidoc
Most of the work was done by Jonathan Siddle[1]. I just combed and
committed the results.
1. https://groups.google.com/forum/#!topic/newsboat/fh1NYGXq7dk
=> Describe how to synchronize with Bazqux

.cirrus.yml, mk/mk.deps
Fixes #770. See that issue for an explanation of this.
Will merge in 24 hours unless someone stops me for a review.
=> Run `make depslist` on CI to check if it changed

doc/newsboat.asciidoc, test/matcher.cpp, test/regexmanager.cpp
This resolves one of the TODO items for #631.
=> Document (and test) that filter language and `highlight` use POSIX ERE

mk/mk.deps, test/fslock.cpp
Added some tests for FsLock so I can more confidently make changes later (planning to fix issue #314 in a future PR).
=> Add test cases for FsLock::try_lock()

include/rs_utils.h, include/utils.h, rust/libnewsboat-ffi/src/utils.rs, rust/libnewsboat/src/utils.rs, src/utils.cpp, test/utils.cpp
=> Oxidize utils::run_interactively

doc/configcommands.dsv, doc/hackers-guide.asciidoc, doc/manpage-podboat.asciidoc, include/regexmanager.h, include/rssfeed.h, src/rssfeed.cpp, src/rssparser.cpp
I just cleaned up some stale local git branches.
While doing that, I found some small improvements which might be somewhat useful.
=> Miscellaneous small improvements

src/itemlistformaction.cpp
=> Specify width when formatting articlelist-title to get "%>-" to work

src/pbview.cpp
Fixes https://github.com/akrennmair/newsbeuter/issues/344
=> Podboat: Hide cursor

include/tagsouppullparser.h, src/tagsouppullparser.cpp, src/utils.cpp, test/tagsouppullparser.cpp, test/utils.cpp
=> HtmlRenderer: Also include whitespace when it is directly followed by an HTML tag

CHANGELOG.md, include/keymap.h, include/view.h, src/controller.cpp, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp, src/formaction.cpp, src/helpformaction.cpp, src/keymap.cpp, src/pbview.cpp, src/view.cpp, test/configparser.cpp, test/keymap.cpp
=> Let KeyMap::getkeys() return all keys bound to an operation

include/feedlistformaction.h, include/matchable.h, include/matcher.h, src/feedlistformaction.cpp, src/matcher.cpp, test/matcher.cpp
Just a couple random edits I did while working on the new filter parser implementation.
Reviews from everyone are welcome. Will merge in three days.
=> Miscellaneous improvements to Matcher interface

include/filtercontainer.h, mk/mk.deps, src/filtercontainer.cpp, src/selectformaction.cpp, test/filtercontainer.cpp
What the title says, plus a few boyscout-rule enhancements.
Reviews from everyone are welcome. Will merge in three days.
=> Add tests for FilterContainer

po/tr.po
- Fixed `#fuzzy`s
- Fixed layout issues and overflowing text
Will continue to update the missing translations as I can.
=> Update Turkish translations

doc/newsboat.asciidoc
Fixes #934. Will merge in 3 days.
=> Document HOME and END key names

src/inoreaderapi.cpp
=> speedup Inoreader mark_article_read using thread, borrowed from ttrssapi.cpp

Makefile, include/dirbrowserformaction.h, include/filebrowserformaction.h, include/listformatter.h, mk/mk.deps, mk/podboat.deps, src/dialogsformaction.cpp, src/dirbrowserformaction.cpp, src/feedlistformaction.cpp, src/filebrowserformaction.cpp, src/itemlistformaction.cpp, src/listformatter.cpp, src/pbview.cpp, src/selectformaction.cpp, src/urlviewformaction.cpp, test/listformatter.cpp
Another small step in abstracting away from STFL.
=> Use ListFormatter instead of manually constructing stfl lists

.gitignore, Makefile, src/keymap.cpp, src/view.cpp, test/keymap.cpp
This PR includes tests for `KeyMap::dump_config()` and a small improvement for that function.
I've also cherry-picked some old commits onto this branch (quite small changes I forgot/postponed to add a PR for).
=> Test and improve KeyMap::dump_config

include/controller.h, include/feedlistformaction.h, include/itemlistformaction.h, include/view.h, src/controller.cpp, src/dialogsformaction.cpp, src/dirbrowserformaction.cpp, src/feedlistformaction.cpp, src/filebrowserformaction.cpp, src/helpformaction.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/pbview.cpp, src/selectformaction.cpp, src/urlviewformaction.cpp, src/view.cpp, test/itemlistformaction.cpp
Various improvements to the `FeedListFormAction` class.
=> Improve feedlist class

src/dialogsformaction.cpp, src/dirbrowserformaction.cpp, src/feedlistformaction.cpp, src/filebrowserformaction.cpp, src/itemlistformaction.cpp, src/selectformaction.cpp, src/urlviewformaction.cpp, stfl/itemlist.stfl
This again abstracts from STFL in a few more places.
=> Reuse {get,set}_position() from list widgets.

.cirrus.yml
Fixes #816.
That issue was open for a while and didn't receive any negative feedback, so I don't expect this PR to be controversial. Thus, I'll merge it after I've tested that it works.
=> Deny Rust warnings on CI

include/configcontainer.h, include/feedlistformaction.h, include/itemlistformaction.h, mk/mk.deps, src/feedlistformaction.cpp, src/itemlistformaction.cpp
More details in the commit message of https://github.com/newsboat/newsboat/commit/abc1d38a62a6358021c45ff45c79bb5c9c827b3c. The other commit is purely to make the code more uniform across the two files.
Reviews are welcome! Will merge in three days.
=> Force ItemListFormAction to re-sort the feed on first view

.cirrus.yml, test/.undefined-sanitizer-suppressions
=> Run UndefinedBehaviorSanitizer on CI

po/ca.po, po/de.po, po/es.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po
Reviews welcome, but I don't really expect any, so I'll merge this once CI passes.
=> Update Russian and Ukrainian translations

po/nl.po
- Add translations for missing/fuzzy entries
- Expand "…" to "..." to be in line with English original strings
=> Update Dutch translation:

.cirrus.yml
Ensure that it removes everything that `make install` created. See also #1020.
=> CI: test `make uninstall`

3rd-party/catch.hpp
Just maintenance, nothing to see here :) I'll merge once the CI passes.
=> Update Catch to 2.12.3

include/scopemeasure.h, mk/mk.deps, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat-ffi/src/scopemeasure.rs, rust/libnewsboat/src/lib.rs, rust/libnewsboat/src/scopemeasure.rs, rust/libnewsboat/tests/scopemeasure_dropping_writes_a_line_to_the_log.rs, rust/libnewsboat/tests/scopemeasure_stopover_adds_an_extra_line_to_the_log_upon_each_call.rs, src/scopemeasure.cpp, test/scopemeasure.cpp, test/test-helpers/loggerresetter.cpp, test/test-helpers/loggerresetter.h
=> Port ScopeMeasure to Rust

3rd-party/catch.hpp
Submitting a PR to see if this breaks on any platforms. Will merge once everything's green.
=> Update Catch to 2.12.4

.gitattributes, doc/docker.md, docker/ubuntu_16.04-build-tools.dockerfile, docker/ubuntu_18.04-build-tools.dockerfile, docker/ubuntu_18.04-i686.dockerfile, docker/ubuntu_20.04-build-tools.dockerfile
This PR makes good of my promise: https://github.com/newsboat/newsboat/issues/1064#issuecomment-653219567 Please read the commit messages for details.
Reviews are welcome as always. I'll merge this in three days if no issues are raised.
=> Make Docker useable for end users

Cargo.lock, include/fslock.h, rust/libnewsboat-ffi/src/fslock.rs, rust/libnewsboat-ffi/src/lib.rs, rust/libnewsboat/src/bin/lock-process.rs, rust/libnewsboat/src/fslock.rs, rust/libnewsboat/src/lib.rs, rust/libnewsboat/tests/fslock.rs, src/fslock.cpp
related PR: https://github.com/newsboat/newsboat/pull/914
Hi, I did a work around to fix the `CARGO_BIN_EXE_xxx` error in Rust < 1.43
=> Pr#914 fslock

include/feedlistformaction.h, include/itemlistformaction.h, include/listformaction.h, mk/mk.deps, src/feedlistformaction.cpp, src/itemlistformaction.cpp, src/listformaction.cpp
Just a small attempt at reducing the amount of duplicated code.
=> Deduplicate movement operations by moving into ListFormAction

include/feedlistformaction.h, include/itemlistformaction.h, src/feedlistformaction.cpp, src/itemlistformaction.cpp
=> Fix search overwriting issue

src/reloader.cpp
=> After reloading, sort feeds *then* redraw the list

include/itemlistformaction.h, src/dialogsformaction.cpp, src/itemlistformaction.cpp
Mostly search related as I found the issues while working on a search related refactor.
=> A variety of small fixes

src/feedlistformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/1006
=> Ask user for confirmation before marking all feeds as read

doc/newsboat.asciidoc, rust/libnewsboat/src/fmtstrformatter/mod.rs, rust/libnewsboat/src/fmtstrformatter/parser.rs, test/fmtstrformatter.cpp
Seems like I got it working and wrote a test and documentation for it.
=> Implement a center formatting sequence

src/minifluxapi.cpp
=> Correctly follow redirects for Miniflux

rust/libnewsboat/src/utils.rs
Newsboat doesn't reap its children. This causes zombie process to linger
around. We fix this by making the Rust command-spawning functions return
a PID and periodically check if said PIDs can be reaped.
Note: this is a WIP, the code to do the actual checking hasn't been
implemented yet. I'm planning on doing the checking in the Reloader (or perhaps
make the view spawn a new thread along with the reloader?), let me know if
you'd like things to be done differently.
=> Reap notify-program children

.cirrus.yml, CHANGELOG.md, Cargo.lock, README.md, doc/internal/howto-release.md, doc/newsboat.asciidoc
A bit of an upkeep. Submitting this as a pull request because some of those crate updates might break the build.
Will merge once all the checks pass.
=> Prepare for 2.22 release

include/cache.h, include/matchable.h, include/rssfeed.h, include/rssitem.h, src/cache.cpp, src/rssfeed.cpp, src/rssitem.cpp, test/matcher.cpp, test/regexmanager.cpp
Just a small const correctness fix, I don't think it needs more justification than that :)
Reviews are welcome! I'll merge this in three days.
=> Mark Matchable::attribute_value() const

3rd-party/catch.hpp
Just regular maintenance. Will merge once CI is green.
=> Update Catch to 2.13.2

.cirrus.yml, docker/ubuntu_16.04-build-tools.dockerfile, docker/ubuntu_18.04-build-tools.dockerfile, docker/ubuntu_18.04-i686.dockerfile, docker/ubuntu_20.04-build-tools.dockerfile, rust/libnewsboat/tests/configpaths_helpers/mod.rs, rust/strprintf/src/traits.rs
Just regular maintenance. Will merge once the CI passes.
=> Bump Rust to 1.47.0 on CI

mk/mk.deps, rss/atomparser.cpp, rss/medianamespace.cpp, rss/medianamespace.h, rss/rss09xparser.cpp, rss/rss10parser.cpp, rss/rssparser.cpp, rss/rssparser.h, rss/xmlutilities.cpp, rss/xmlutilities.h, test/data/atom10_2.xml, test/data/rss20_2.xml, test/rsspp_parser.cpp
Fixes https://github.com/newsboat/newsboat/issues/595
Specification: https://www.rssboard.org/media-rss#media-description
=> Implement rss media extension

po/tr.po
Fixed consistency errors and a few ambiguities.
=> Improve Turkish localisation

.gitignore, include/colormanager.h, include/configactionhandler.h, include/configcontainer.h, include/configparser.h, include/controller.h, include/filtercontainer.h, include/keymap.h, include/nullconfigactionhandler.h, include/regexmanager.h, include/rssignores.h, include/view.h, src/colormanager.cpp, src/configcontainer.cpp, src/controller.cpp, src/filtercontainer.cpp, src/keymap.cpp, src/regexmanager.cpp, src/rssignores.cpp, test/configparser.cpp
=> add const to dump_config fix #1234

src/keymap.cpp, src/urlviewformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/1218.
=> Add help option to UrlViewFormAction

include/controller.h, include/feedhqurlreader.h, include/fileurlreader.h, include/inoreaderurlreader.h, include/minifluxurlreader.h, include/newsblururlreader.h, include/ocnewsurlreader.h, include/oldreaderurlreader.h, include/opml.h, include/opmlurlreader.h, include/ttrssurlreader.h, include/urlreader.h, mk/mk.deps, src/controller.cpp, src/feedhqurlreader.cpp, src/fileurlreader.cpp, src/inoreaderurlreader.cpp, src/minifluxurlreader.cpp, src/newsblururlreader.cpp, src/ocnewsurlreader.cpp, src/oldreaderurlreader.cpp, src/opml.cpp, src/opmlurlreader.cpp, src/ttrssurlreader.cpp, test/fileurlreader.cpp
Fixes https://github.com/newsboat/newsboat/issues/439.
Follow-up on https://github.com/newsboat/newsboat/pull/882#pullrequestreview-391894876.
=> Show error message when a URL reader cannot open the urls file

3rd-party/catch.hpp
This is just regular maintenance. Will merge once all the CI checks are done.
=> Update Catch to 2.13.3

.cirrus.yml, Makefile, README.md
Fixes #896.
Reviews are welcome! If no issues are raised, I'll merge this in three days.
=> Add `check` and `ci-check` targets to Make

rust/libnewsboat/src/filterparser.rs, rust/libnewsboat/src/fmtstrformatter/parser.rs
=> Add ContextError trait

3rd-party/optional.hpp, src/feedlistformaction.cpp
The code was adjusted to avoid `maybe-unitialized` warnings on i686:
https://cirrus-ci.com/task/4915794935021568?command=build#L68
=> Update optional-lite to 3.3.0

include/itemlistformaction.h, src/itemlistformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/1293
=> ItemList: Add items to list before changing the position

3rd-party/optional.hpp
This is just routine maintenance, so I'll merge this in one day.
=> Update optional-lite to 3.4.0

.cirrus.yml, docker/ubuntu_16.04-build-tools.dockerfile, docker/ubuntu_18.04-build-tools.dockerfile, docker/ubuntu_18.04-i686.dockerfile, docker/ubuntu_20.04-build-tools.dockerfile, docker/ubuntu_20.10-build-tools.dockerfile, rust/libnewsboat/src/fmtstrformatter/mod.rs, rust/libnewsboat/src/utils.rs
Another bit of maintenance. Will merge in three days.
=> Bump Rust on CI to 1.48.0

src/helpformaction.cpp, src/pbview.cpp
Fixes https://github.com/newsboat/newsboat/issues/1139.
=> Improve help forms

Makefile, contrib/README.md, doc/chapter-firststeps.asciidoc, doc/newsboat.asciidoc
=> contrib: add README.md, promote in documentation

include/fslock.h, mk/mk.deps, rust/libnewsboat-ffi/build.rs, rust/libnewsboat-ffi/src/fslock.rs, rust/libnewsboat/src/fslock.rs, src/controller.cpp, src/fslock.cpp, src/pbcontroller.cpp
Followup on https://github.com/newsboat/newsboat/pull/1317.
=> Update FsLock c++/rust interface to use cxx

po/ca.po, po/de.po, po/es.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po, rust/libnewsboat/src/fslock.rs, test/fileurlreader.cpp, test/utils.cpp
It's two weeks before 2.22 release, so it's time to start updating the translations! I'll merge this in one day, or even sooner if someone reviews this. I'm especially interested in feedback on https://github.com/newsboat/newsboat/commit/c787645636bae614da24d0d4c558868940cf9dfc, if any. After that, I'll ping all translators asking to update their PO files as well.
=> Update the POT file and Russian & Ukrainian translations

po/tr.po
Sorry, but I've realised that I've missed a fuzzy string (missed deleting the old part).
Better late than never, I guess.
=> Fix missed fuzzy string

src/formaction.cpp, src/view.cpp
Fixes https://github.com/newsboat/newsboat/issues/1345.
=> Handle "set" operation without re-quoting arguments

po/fr.po
Good evening and thanks for the reminder. Here is a minor contribution with update/addition to the french translation.
=> Minor update to french translations

po/pl.po
Refs: https://github.com/newsboat/newsboat/pull/1339#issuecomment-739808634
=> feat(lang): add missing Polish translations

.cirrus.yml, src/pbview.cpp
Nothing much to see here, just waiting for CI to pass.
=> CI: add macOS Big Sur

.cirrus.yml, CHANGELOG.md, Cargo.lock, README.md, doc/internal/howto-release.md, doc/newsboat.asciidoc, docker/code-formatting-tools.dockerfile, rust/libnewsboat/src/utils.rs, rust/libnewsboat/tests/configpaths_helpers/mod.rs
(Submitting this as a PR to make sure I didn't bork CI configs.)
=> Prepare for next release

doc/keycmds.dsv, include/cache.h, include/controller.h, src/cache.cpp, src/controller.cpp, src/itemlistformaction.cpp
Fixes #1360.
Reviews are welcome. Will merge in three days.
=> ItemList: make delete-all-articles affect only visible items

3rd-party/catch.hpp
Will merge once the CI builds are done.
=> Update Catch to 2.13.4

src/itemlistformaction.cpp
Fixes #1385. I have a bit more to say about this hacky fix in #1390 :) 
Will merge in three days if no issues are raised during review — which are welcome as always!
=> Fix articlelist title not updating

src/queuemanager.cpp
Fixes https://github.com/newsboat/newsboat/issues/836
=> Replace slashes with underscores in generated podcast filenames

include/dirbrowserformaction.h, include/filebrowserformaction.h, include/view.h, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp, src/view.cpp
Fixes https://github.com/newsboat/newsboat/issues/1418
=> Fix issue related to `save-all` path

doc/newsboat.asciidoc
@christosmarg, this PR is inspired by our chat on IRC yesterday; please take a look and tell me if the new version is any clearer than the old one.
Requesting a review from @der-lyse since I run all the docs by him, but everyone else is welcome to review too! I'll merge in three days if no issues are raised.
=> Doc: rewrite and expand bookmarking section

include/textformatter.h, mk/mk.deps, src/textformatter.cpp, test/htmlrenderer.cpp, test/textformatter.cpp
=> TextFormatter: do not skip space-only lines

.astylerc, include/queueloader.h, include/utils.h, mk/mk.deps, src/pbcontroller.cpp, src/queueloader.cpp, src/utils.cpp, test/configpaths.cpp, test/data/nonempty-queue-file, test/data/queue-file-for-merging, test/data/queue-file-with-empty-lines, test/data/queue-file-with-empty-lines-removed, test/data/queue-with-missing-files, test/data/queue-with-unmarked-downloaded-file, test/data/queue-without-filenames, test/data/sentry-queue-file, test/queueloader.cpp, test/test-helpers/misc.cpp, test/test-helpers/misc.h
This is a stepping stone to #1344: I'm beefing up the test suite and prettyfying the code to make it safer and easier to work on that issue.
=> Complete QueueLoader coverage

.cirrus.yml
A bit of upkeep, please see commit messages for details. I don't expect much discussion here, so I'll merge this tomorrow.
=> Make macOS and FreeBSD faster in CI

Makefile, src/urlreader.cpp, test/test-helpers/opts.h
Should've done it in #1406, but better late than never.
As always: reviews are welcome, intend to merge in three days.
=> Suppress cppcheck warnings I don't intend to address

Cargo.lock, rust/libnewsboat/Cargo.toml, rust/libnewsboat/src/utils.rs
=> Drop accidental dependency on openssl-sys crate

rust/libnewsboat/src/filterparser.rs, rust/libnewsboat/src/fslock.rs, src/controller.cpp, src/fileurlreader.cpp, src/itemviewformaction.cpp, src/keymap.cpp, src/opml.cpp, src/utils.cpp, src/view.cpp
Fixes #1354. I'll merge once I've got a review from @der-lyse, but reviews and comments from others are welcome too!
=> Correct issues spotted by translators

doc/configcommands.dsv, src/configcontainer.cpp, src/itemlistformaction.cpp
=> Add setting to confirm before deleting all articles

doc/newsboat.asciidoc, include/feedlistformaction.h, src/feedlistformaction.cpp
Resolves https://github.com/newsboat/newsboat/issues/1495.
=> Add %U format specifier (unread articles count) for feedlist-title-format

include/htmlrenderer.h, rust/libnewsboat/src/htmlrenderer.rs, src/htmlrenderer.cpp, test/htmlrenderer.cpp
=> Render <iframe> in article view

src/htmlrenderer.cpp, test/htmlrenderer.cpp
=> Render <img> with correct index and a reference to the list of links

po/it.po
As for #1519 I've updated the Italian translations.
=> i18n: Add missing Italian translations for 2.23

mk/mk.deps, src/listwidget.cpp, src/pbview.cpp, test/listwidget.cpp
Fixes https://github.com/newsboat/newsboat/issues/1546.
=> Fix index-out-of-range segmentation fault

.gitignore, src/view.cpp
Hello!
This one is for #1530. replaced all found calls to `StatusLine::show_message`
=> Use new message api in View class

include/history.h, mk/mk.deps, rust/libnewsboat-ffi/build.rs, rust/libnewsboat-ffi/src/history.rs, src/history.cpp
Related to https://github.com/newsboat/newsboat/issues/1383.
=> Use cxx for History FFI

include/queuemanager.h, mk/mk.deps, src/controller.cpp, src/queuemanager.cpp, test/configpaths.cpp, test/queueloader.cpp, test/queuemanager.cpp, test/test-helpers/misc.cpp, test/test-helpers/misc.h
This is yet another stepping stone for #1344. The test coverage for QueueManager is now at 100%, yay!
Reviews are welcome as always. I'll merge this in three days.
=> Improve test coverage for QueueManager

Makefile, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp, src/pbview.cpp, src/view.cpp
Just a couple little changes inspired by https://github.com/newsboat/newsboat/pull/1580.
Reviews welcome! I'll merge in three days.
=> Enhace `make clean` and <curses.h> → <ncurses.h>

src/feedcontainer.cpp, test/feedcontainer.cpp
Hello!
This is my attempt to fix #1561 
Making a corner-case for "unread article count" method in a separate class may be not the best ever approach, but this is why we have code reviews :)
=> [1561] Incorrect feed sorting

doc/chapter-snownews.asciidoc, doc/newsboat.asciidoc
=> Update Snownews links

.cirrus.yml, docker/ubuntu_21.04-build-tools.dockerfile
Also update sanitizer jobs, to ensure we're using the latest and
greatest sanitizers.
=> CI: add Clang 12

.cirrus.yml
Just a little change inspired by #1598. See the commit message for details.
Reviews are welcome! I'll merge in three days.
=> CI: use -fstack-protector-all

src/itemviewformaction.cpp
as discussed in #1637
Hopefully me doing this will not create more work than necessary, the change is rather straightforward however.
=> Consider toggle-article-read arguments in item view

README.md, doc/internal/howto-release.md, doc/newsboat.asciidoc, newsboat.cpp, src/pbcontroller.cpp
=> Docs: move IRC channel from Freenode to Libera.Chat

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/1656#issuecomment-855443888
=> chore(l10n): Update Polish translations

po/it.po
Hi, i've seen #1656, here's the updated Italian PO file.
=> Ita translations

include/download.h, src/download.cpp, src/poddlthread.cpp, src/queueloader.cpp, test/queueloader.cpp
Fixes #545 by showing error message to user when unable to rename podcast.
=> fixes #545 by throwing rename failure message

Cargo.lock, rust/libnewsboat/Cargo.toml, rust/libnewsboat/src/utils.rs, rust/libnewsboat/tests/configpaths_03.rs, rust/libnewsboat/tests/configpaths_helpers/mod.rs
=> Use fastrand instead of rand

doc/chapter-files.asciidoc
Fixes #1706.
@ifohancroft, can you please take a look at this? Is this any clearer than before? I suspect I might still not be explaining it too well.
=> Clarify what dir has to exist for Newsboat to use XDG

src/itemlistformaction.cpp
=> purge-deleted should try to keep the cursor where it was

3rd-party/json.hpp
Just basic housekeeping. This PR will get merged automatically once CI is green.
=> Update json.hpp to 3.10.0

doc/faq.asciidoc
This is inspired by #871, #1243, and #1735.
Reviews are welcome! I'll merge this once @der-lyse have taken a look and there is no unaddressed reviews.
=> FAQ: explain how to export OPML with tags

po/it.po
As mentioned in #1762 I've updated the Italian po file.
=> Updated Italian translations.

src/itemviewformaction.cpp
=> OP_ENQUEUE: replace "Invalid URL:" message

include/formaction.h, src/formaction.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/urlviewformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/243
=> Accept empty feed title when bookmarking on autopilot

rust/libnewsboat/src/logger.rs, rust/libnewsboat/src/utils.rs
Fixes warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
=> Fix trailing semicolon warning

contrib/bookmark-buku.sh
Just adds a simple script to send bookmarks to [buku](https://github.com/jarun/Buku).
=> Add a script to send bookmarks to buku

contrib/colorschemes/gruvbox
A simple 256-color gruvbox theme.
=> Add a gruvbox theme

po/ru.po, po/uk.po
I'll merge this once someone—anyone—took a look and didn't find any obvious flaws.
=> Update Ukrainian and Russian translations

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/1892#issuecomment-988945102
=> chore(l10n): Update Polish translation

doc/chapter-tagging.asciidoc
Cf. #33. It doesn't fix the issue, but it at least explains the
workaround.
=> Document how to get articles from hidden feeds

src/feedlistformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/1934
=> Use actual feed position in list when moving down by 1

rss/atomparser.cpp
Fix https://github.com/newsboat/newsboat/issues/1938
=> Fix bug in xml parsing

po/fr.po
Corrected last fuzzy strings. Hope this one is ok in content and form (PR on the right branch).
=> Correction of the last fuzzy strings

contrib/colorschemes/nord
Fixed UX bug on prompts not showing up due to foreground colour being too close to default. 
Also... reworked the theme slightly so uses the more canonical Nord palette generally. Much nicer.
=> Fixes to UX bugs in Nord colour scheme.

po/es.po
Only one string needed updating, as the translation was reviewed recently.
=> Update ES translation for next release

src/htmlrenderer.cpp, test/htmlrenderer.cpp
=> Preserve line breaks in tags inside <pre>

src/tagsouppullparser.cpp, test/tagsouppullparser.cpp
=> Convert all windows codepoints defined in the spec

include/searchresultslistformaction.h, src/searchresultslistformaction.cpp
fix https://github.com/newsboat/newsboat/issues/2043
=> Keep current results when repeating the same search

rss/atomparser.cpp, rss/rss09xparser.cpp, test/data/multiple_item_links.atom, test/rsspp_parser.cpp
Related to https://github.com/newsboat/newsboat/issues/2060
=> Make `http\https` default if multiple link

mk/mk.deps, src/itemviewformaction.cpp, src/textviewwidget.cpp, test/textviewwidget.cpp
Fixes https://github.com/newsboat/newsboat/issues/2073
Fixes https://github.com/newsboat/newsboat/issues/1298
=> Stop scrolling to top of article when window is resized

doc/newsboat.asciidoc
Cf. #35
@der-lyse, please take a look at the new text. Does it look okay?
=> Document Inoreader support limitations

po/es.po
Update Spanish translation for next release.
=> Update ES translation

src/htmlrenderer.cpp, test/htmlrenderer.cpp
=> Add new line for back-to-back image, audio and video tags

contrib/newsboat_reorganize.py
Added a python script that help in organizing the `urls` file by prepending the feeds title in front of the URL. See #1918.
=> Added contrib script for organizing `urls` file.

include/cache.h, src/cache.cpp
=> Fix cache db locking

CHANGELOG.md, include/feedlistformaction.h, include/filtercontainer.h, include/itemlistformaction.h, mk/mk.deps, src/feedlistformaction.cpp, src/filtercontainer.cpp, src/itemlistformaction.cpp, test/filtercontainer.cpp
Related to https://github.com/newsboat/newsboat/issues/2133#issuecomment-1200128497
=> Allow selecting filter by name

rss/parser.cpp, src/utils.cpp
Resolves https://github.com/newsboat/newsboat/issues/2152
=> Accept any encoding supported by curl (including brotli)

include/selectformaction.h, include/view.h, src/feedlistformaction.cpp, src/selectformaction.cpp, src/view.cpp
Resolves https://github.com/newsboat/newsboat/issues/2093
=> Move to currently selected tag in tag list

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2180#issuecomment-1243021481
=> chore(l10n): Update pl translation before release

doc/configcommands.dsv, doc/newsboat.asciidoc, include/minifluxapi.h, include/remoteapi.h, src/configcontainer.cpp, src/controller.cpp, src/minifluxapi.cpp, src/remoteapi.cpp
Resolves https://github.com/newsboat/newsboat/issues/2122
=> Miniflux: Add support for API Token authentication

rss/parser.cpp, src/utils.cpp
Fixes https://github.com/newsboat/newsboat/issues/2230 (at least part of it, I can't verify the roscosmos issues myself).
=> Clear received header values on redirect

include/remoteapi.h, include/ttrssapi.h, include/view.h, src/feedhqapi.cpp, src/freshrssapi.cpp, src/inoreaderapi.cpp, src/ocnewsapi.cpp, src/oldreaderapi.cpp, src/remoteapi.cpp, src/ttrssapi.cpp, src/view.cpp
Noticed a couple cases of copy-paste code. I think this would make the code more readable, especially the flag comparisons weren't exactly easy on the eye.
=> Refactoring

po/ca.po, po/de.po, po/es.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po
Just three new messages this time around, should be easy work to update translations!
=> Update .pot and .po files

po/it.po
Updated italian translations.
See: #2282
=> Updated Italian po file

src/poddlthread.cpp
Fixes https://github.com/newsboat/newsboat/issues/2297
=> Stop using deprecated curl option: CURLOPT_PROGRESSFUNCTION

doc/keycmds.dsv, include/keymap.h, include/listmovementcontrol.h, include/textviewwidget.h, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp, src/formaction.cpp, src/helpformaction.cpp, src/itemviewformaction.cpp, src/keymap.cpp, src/pbview.cpp, src/textviewwidget.cpp, test/listmovementcontrol.cpp, test/textviewwidget.cpp
Resolves https://github.com/newsboat/newsboat/issues/36
Tested using config:
```
bind-key ^U halfpageup
bind-key ^D halfpagedown
```
=> Add operations for scrolling by half a page

include/dialogsformaction.h, include/dirbrowserformaction.h, include/emptyformaction.h, include/feedlistformaction.h, include/filebrowserformaction.h, include/formaction.h, include/helpformaction.h, include/itemlistformaction.h, include/itemviewformaction.h, include/selectformaction.h, include/urlviewformaction.h, src/formaction.cpp, src/itemlistformaction.cpp, stfl/help.stfl, stfl/itemlist.stfl, stfl/itemview.stfl, stfl/selecttag.stfl
Fixes #2351. Tested on Debian unstable with stfl 0.22-3+b5.
This PR is an alternative to #2355, which [didn't work for me](https://github.com/newsboat/newsboat/pull/2355#issuecomment-1455213014).
=> Fix keybinds not working outside feedlist

.cirrus.yml, CHANGELOG.md, Cargo.lock, README.md, doc/newsboat.asciidoc, docker/code-formatting-tools.dockerfile
This finally completes the 2.31 release :)
=> Prepare for the next release

docker/ubuntu_18.04-build-tools.dockerfile, docker/ubuntu_18.04-i686.dockerfile, docker/ubuntu_20.04-build-tools.dockerfile, docker/ubuntu_22.04-build-tools.dockerfile
(Rust sure had a lot of patch releases lately...)
=> CI: bump Rust to 1.68.2

src/htmlrenderer.cpp, test/htmlrenderer.cpp
=> Give links in tags like <img> a "higher priority" to links in <a>

include/pbcontroller.h, include/pbview.h, podboat.cpp, src/pbcontroller.cpp, src/pbview.cpp
Just a small improvement introduced in https://github.com/newsboat/newsboat/pull/2364 (splitting it off so the other PR becomes slightly easier to review)
=> PbView: Change some pointers to references

src/queuemanager.cpp, test/queuemanager.cpp
Fixes https://github.com/newsboat/newsboat/issues/2367
=> Only autoenqueue podcasts with a valid or empty type

Makefile, newsboat.cpp, src/configcontainer.cpp, src/feedlistformaction.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp
Resolves https://github.com/newsboat/newsboat/issues/2441
=> Mark messages containing a percentage as translatable

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2460#issuecomment-1593779482
=> chore(l10n): Update Polish translation before 2.32 release

po/sv.po
I added translations of most (but not all) of the strings which weren't already translated into Swedish and fixed some translations which were marked as fuzzy or resulted in validation errors.
=> Edit of Swedish translation

po/sv.po
This fixes the unresolved issues from #2471, but also completes the Swedish translation as well as fixing/tweaking some previously translated strings. 
(Note: some of the diffs here comes from Poedit changing the position of line breaks in the file.)
=> Completing and fixing the Swedish translation

docker/ubuntu_18.04-build-tools.dockerfile, docker/ubuntu_18.04-i686.dockerfile, docker/ubuntu_20.04-build-tools.dockerfile, docker/ubuntu_22.04-build-tools.dockerfile, docker/ubuntu_23.04-build-tools.dockerfile
https://blog.rust-lang.org/2023/08/03/Rust-1.71.1.html
=> CI: bump Rust to 1.71.1

src/opml.cpp, test/data/category.opml, test/opml.cpp
=> `--import-from-opml` support tags

include/curldatareceiver.h, mk/libboat.deps, rss/parser.cpp, src/curldatareceiver.cpp, src/feedhqapi.cpp, src/freshrssapi.cpp, src/inoreaderapi.cpp, src/ocnewsapi.cpp, src/oldreaderapi.cpp, src/utils.cpp
Cherry-picked from discarded PR https://github.com/newsboat/newsboat/pull/2306.
This PR will probably cause merge conflicts for https://github.com/newsboat/newsboat/pull/2340. I plan to rebase either of the PRs if the other is merged.
=> Extract accumulation of received data into separate class

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2548#issuecomment-1719326233
=> chore(l10n): Update Polish translation before 2.33 release

po/sv.po
I've corrected the translation of two of the strings.
=> Fixing Swedish translation

doc/chapter-configuration.asciidoc
Inspired by the discussion with allanwind starting at https://github.com/newsboat/newsboat/issues/1951#issuecomment-1358935805
=> Clarify how line splitting works in configs

include/dialogsformaction.h, include/dirbrowserformaction.h, include/emptyformaction.h, include/feedlistformaction.h, include/filebrowserformaction.h, include/formaction.h, include/helpformaction.h, include/itemlistformaction.h, include/itemviewformaction.h, include/listformaction.h, include/searchresultslistformaction.h, include/selectformaction.h, include/urlviewformaction.h, src/dialogsformaction.cpp, src/dirbrowserformaction.cpp, src/emptyformaction.cpp, src/feedlistformaction.cpp, src/filebrowserformaction.cpp, src/formaction.cpp, src/helpformaction.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/listformaction.cpp, src/searchresultslistformaction.cpp, src/selectformaction.cpp, src/urlviewformaction.cpp, src/view.cpp, test/itemlistformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/2570
=> Fix nullptr dereference in `process_operation()` implementations

doc/internal/howto-release.md
=> Release HOWTO: bump GPG expiry date every September

rust/libnewsboat/src/keymap.rs
Extracted a small part from https://github.com/newsboat/newsboat/pull/2364 for easier reviewability (and to avoid some big rebases)
=> Add parsing logic for new "bind" syntax

src/helpformaction.cpp
Another small refactoring to simplify integration of https://github.com/newsboat/newsboat/pull/2364
=> Simplify rendering of helpform

include/itemlistformaction.h, include/view.h, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/view.cpp
https://github.com/newsboat/newsboat/pull/2561#discussion_r1357348873
=> Change `View::run_dirbrowser()` to return `nonstd::optional<std::string>`

rust/libnewsboat-ffi/src/keymap.rs, src/keymap.cpp, test/keymap.cpp
Small continuation of work done in https://github.com/newsboat/newsboat/pull/2586.
=> Add FFI for tokenize_binding()

src/cache.cpp
Issue https://github.com/newsboat/newsboat/issues/2528
=> Automation updates of `metadata` table 

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2616#issuecomment-1850666683
=>  chore(l10n): Update Polish translation before 2.34 release

po/zh.po
Ref: https://github.com/newsboat/newsboat/pull/2616#issuecomment-1850666683
Add translation for the newly added string.
I'm working on style consistency already. After that, I plan to have a complete look back at previous translations and then handle the remaining unresolved translations.
=> Update Chinese translations

po/it.po
=> Updated italian translations

doc/newsboat.asciidoc, src/rssfeed.cpp, test/rssfeed.cpp
Resolves https://github.com/newsboat/newsboat/issues/2619
=> Add feed attribute for filtering on latest article publish date

doc/chapter-files.asciidoc, doc/manpage-newsboat.asciidoc, doc/manpage-podboat.asciidoc, include/cliargsparser.h, include/configpaths.h, newsboat.cpp, rust/libnewsboat-ffi/src/cliargsparser.rs, rust/libnewsboat-ffi/src/configpaths.rs, rust/libnewsboat/src/cliargsparser.rs, rust/libnewsboat/src/configpaths.rs, rust/libnewsboat/tests/configpaths_03.rs, rust/libnewsboat/tests/configpaths_05.rs, rust/libnewsboat/tests/configpaths_06.rs, src/cliargsparser.cpp, src/configpaths.cpp, src/controller.cpp, src/pbcontroller.cpp, test/cliargsparser.cpp, test/configpaths.cpp
=> Add CLI argument to set history.cmdline, history.search, queue and pb-lock.pid

po/zh.po
Most changes are about spaces and punctuation marks.
=> Unify the style of Chinese translations

src/feedbinurlreader.cpp
Fixes build error mentioned in https://github.com/newsboat/newsboat/pull/2650#discussion_r1485613029
@juntuu Thanks for reporting it!
=> Fix size printing format specifier

include/keymap.h, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp, src/helpformaction.cpp, src/keymap.cpp, src/pbview.cpp, test/configparser.cpp, test/keymap.cpp
Implements idea by @Minoru from https://github.com/newsboat/newsboat/pull/2648#issuecomment-1894564641
=> Take and return KeyCombination on public KeyMap methods

.cirrus.yml
Resolves https://github.com/newsboat/newsboat/issues/2636
Builds on top of @Minoru's work with a workaround mentioned in https://github.com/Koka/gettext-rs/issues/114
=> CI: Add FreeBSD 14.0

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2699#issuecomment-1989341054
=> chore(l10n): Update Polish translation before 2.35 release

po/sv.po
Adding translation of new strings and tweaking translation of previously translated strings.
=> Swedish translation: new strings and updates

3rd-party/expected.hpp
https://github.com/martinmoene/expected-lite/releases/tag/v0.7.0
=> Update expected-lite to 0.7.0

newsboat.cpp, rust/libnewsboat-ffi/src/utils.rs, rust/libnewsboat/src/utils.rs, src/pbcontroller.cpp, test/utils.cpp
Resolves https://github.com/newsboat/newsboat/issues/2705
Related https://github.com/newsboat/newsboat/issues/2546
Before/After:
=> Align help text descriptions

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2766#issuecomment-2156020794
=> chore(l10n): Update Polish translation before 2.36 release

include/feedbinurlreader.h, newsboat.cpp, src/cliargsparser.cpp, src/configcontainer.cpp, src/configparser.cpp, src/configpaths.cpp, src/controller.cpp, src/feedbinurlreader.cpp, src/feedretriever.cpp, src/filepath.cpp, src/fileurlreader.cpp, src/formaction.cpp, src/fslock.cpp, src/history.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/utils.cpp
Part of https://github.com/newsboat/newsboat/issues/2326
Continuation of https://github.com/newsboat/newsboat/pull/2795
=> Remove a few implicit std::string <-> Filepath conversions

include/curlheadercontainer.h, include/utils.h, mk/newsboat.deps, rss/parser.cpp, src/curlheadercontainer.cpp, src/utils.cpp, test/curlheadercontainer.cpp, test/utils.cpp
Split off part of the work from https://github.com/newsboat/newsboat/pull/2340
=> Extract Curl header handling into separate class

src/feedlistformaction.cpp
Fixes https://github.com/newsboat/newsboat/issues/2837
=> Remove "Searching..." message when search is finished

doc/newsboat.asciidoc
Resolves small oversight reported at https://github.com/newsboat/newsboat/pull/2838#issuecomment-2323359207
Thanks @Minoru!
=> Update list of possible podboat download states

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2847#issuecomment-2338656080
=> chore(l10n): Update Polish translation before 2.37 release

po/zh.po
Ref: #2847 
Have a nice day :)
=> Update Chinese translation

src/configcontainer.cpp, test/cache.cpp, test/colormanager.cpp, test/configcontainer.cpp, test/configparser.cpp, test/fslock.cpp, test/itemlistformaction.cpp, test/opmlurlreader.cpp, test/queuemanager.cpp, test/rssfeed.cpp, test/scopemeasure.cpp, test/test_helpers/loggerresetter.cpp, test/test_helpers/tempfile.cpp, test/test_helpers/tempfile.h, test/utils.cpp
Part of https://github.com/newsboat/newsboat/issues/2326
Continuation of https://github.com/newsboat/newsboat/pull/2795
=> Remove a few more implicit std::string <-> Filepath conversions

include/stflpp.h, src/formaction.cpp, src/pbview.cpp, src/stflpp.cpp
Small preparation for https://github.com/newsboat/newsboat/pull/2892
=> Prepare for ratatui: Return an std::string from Stfl::Form::run()

include/dirbrowserformaction.h, include/filebrowserformaction.h, include/filepath.h, rust/libnewsboat-ffi/src/filepath.rs, src/dirbrowserformaction.cpp, src/filebrowserformaction.cpp, src/filepath.cpp, test/filepath.cpp
This is a small step towards #2326.
=> Remove implicit conversions from {File,Dir}BrowserFormAction

Makefile
=> Add missing prerequisite in Makefile

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/2940#issuecomment-2525906858
=> chore(l10n): Update Polish translation before 2.38 release

po/sv.po
Adding missing translations and adjusting some previous translations.
=> Edit Swedish translation

contrib/newsboat-idlefeeds.sh
Script for showing feeds not updated in X amount of time.
=> Add newsboat-idlefeeds.sh

src/keymap.cpp
The operations with an empty default key were still being registered.
That has no user visible effect (as it is not possible to input an empty keypress).
However, it does interfere with further changes I want to make so fixing this first.
=> Fix handling of operations without default key

include/controller.h, include/reloader.h, include/reloadthread.h, include/view.h, newsboat.cpp, src/controller.cpp, src/feedlistformaction.cpp, src/formaction.cpp, src/itemlistformaction.cpp, src/itemutils.cpp, src/itemviewformaction.cpp, src/listformaction.cpp, src/reloader.cpp, src/reloadthread.cpp, src/selectformaction.cpp, src/view.cpp, test/itemlistformaction.cpp, test/view.cpp
I started experimenting a bit with jj (Jujutsu).
That made me aware of some old commits/branches I had floating around.
Going through those now to see if there is still anything useful.
=> Reduce raw pointer usage

rust/libnewsboat/src/stflrichtext.rs
=> Fix `<` escape insertion in StflRichText

include/colormanager.h, src/colormanager.cpp, src/feedlistformaction.cpp, src/itemlistformaction.cpp, src/itemviewformaction.cpp, stfl/dialogs.stfl, stfl/dllist.stfl, stfl/feedlist.stfl, stfl/filebrowser.stfl, stfl/help.stfl, stfl/itemlist.stfl, stfl/itemview.stfl, stfl/selecttag.stfl, stfl/urlview.stfl, test/colormanager.cpp
Reducing defaults specified in our .stfl files as preparation for moving away from STFL.
Related to https://github.com/newsboat/newsboat/pull/2892.
Still planning to do before merging:
=> Move STFL style defaults into C++ code

include/keymap.h, src/helpformaction.cpp, src/keycombination.cpp, src/keymap.cpp, test/keymap.cpp
Part of https://github.com/newsboat/newsboat/pull/2364
Example output:
=> HelpForm: Show new bindings

po/pl.po
Ref: https://github.com/newsboat/newsboat/pull/3020#issuecomment-2708990664
=> chore(l10n): Update Polish translation before 2.39 release

.github/workflows/coveralls.yaml, test/generate_coverage_report.sh
There's a bug in recent grcov releases: https://github.com/mozilla/grcov/issues/1333 This PR works around it by pinning to an earlier version that works. I'm subscribed to the bug and will un-pin grcov once there is a fix.
=> Fix Coveralls CI job

include/opmlurlreader.h, src/controller.cpp, src/opmlurlreader.cpp, test/opmlurlreader.cpp
=> Fix missing handling of queries when urls-source is set to "opml"

Cargo.lock, rust/libnewsboat/Cargo.toml, rust/libnewsboat/src/configpaths.rs
Obsoletes https://github.com/newsboat/newsboat/pull/3060
=> Update xdg to 3.0.0

include/formaction.h, include/lineedit.h, include/view.h, mk/newsboat.deps, src/formaction.cpp, src/lineedit.cpp, src/view.cpp
Preparation for a few more STFL-related improvements.
=> Move QnA handling into FormAction and introduce LineEdit abstraction

rust/libnewsboat/src/utils.rs, src/itemlistformaction.cpp, src/itemviewformaction.cpp, src/remoteapi.cpp
A few more steps toward #2326.
=> Remove a few more implicit filepath conversions

include/filepath.h, test/cliargsparser.cpp, test/configpaths.cpp, test/controller.cpp
This is PR №3 of 3. Previous: https://github.com/newsboat/newsboat/pull/3126
Cf. https://github.com/newsboat/newsboat/issues/2326.
=> Remove all remaining implicit Filepath conversions

po/ca.po, po/de.po, po/es.po, po/fr.po, po/hu.po, po/it.po, po/ja.po, po/nb.po, po/newsboat.pot, po/nl.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_TW.po
I rolled updates to ru.po and uk.po into this PR because they're trivial and I didn't want to make a separate PR for them.
=> Update PO and POT files; update Russian and Ukrainian translations
